/**
 * Additional text animation presets beyond the basic fade/slide/pop set.
 * Categories: entrance, exit, loop, typewriter, handwriting, draw-on.
 */
export type TextAnimCategory =
	| "entrance"
	| "exit"
	| "loop"
	| "typewriter"
	| "handwriting"
	| "draw";

export interface TextAnimPreset {
	id: string;
	name: string;
	category: TextAnimCategory;
	description: string;
	keyframes: Array<{
		propertyPath:
			| "opacity"
			| "transform.positionX"
			| "transform.positionY"
			| "transform.scaleX"
			| "transform.scaleY"
			| "transform.rotate"
			| "color";
		time: number; // 0..1 normalized
		value: number;
	}>;
}

export const TEXT_ANIM_PRESETS: TextAnimPreset[] = [
	// ENTRANCE
	{
		id: "typewriter",
		name: "Typewriter",
		category: "typewriter",
		description:
			"Each character appears one at a time (clip-based approximation)",
		keyframes: [
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	{
		id: "fade-up",
		name: "Fade Up",
		category: "entrance",
		description: "Fade in while sliding up",
		keyframes: [
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.positionY", time: 0, value: 30 },
			{ propertyPath: "opacity", time: 1, value: 100 },
			{ propertyPath: "transform.positionY", time: 1, value: 0 },
		],
	},
	{
		id: "fade-down",
		name: "Fade Down",
		category: "entrance",
		description: "Fade in while sliding down",
		keyframes: [
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.positionY", time: 0, value: -30 },
			{ propertyPath: "opacity", time: 1, value: 100 },
			{ propertyPath: "transform.positionY", time: 1, value: 0 },
		],
	},
	{
		id: "slide-in-left",
		name: "Slide Left",
		category: "entrance",
		description: "Slide in from the left",
		keyframes: [
			{ propertyPath: "transform.positionX", time: 0, value: -200 },
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.positionX", time: 1, value: 0 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	{
		id: "slide-in-right",
		name: "Slide Right",
		category: "entrance",
		description: "Slide in from the right",
		keyframes: [
			{ propertyPath: "transform.positionX", time: 0, value: 200 },
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.positionX", time: 1, value: 0 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	{
		id: "pop-in",
		name: "Pop In",
		category: "entrance",
		description: "Scale up with bounce",
		keyframes: [
			{ propertyPath: "transform.scaleX", time: 0, value: 0 },
			{ propertyPath: "transform.scaleY", time: 0, value: 0 },
			{ propertyPath: "transform.scaleX", time: 0.5, value: 1.15 },
			{ propertyPath: "transform.scaleY", time: 0.5, value: 1.15 },
			{ propertyPath: "transform.scaleX", time: 0.8, value: 0.95 },
			{ propertyPath: "transform.scaleY", time: 0.8, value: 0.95 },
			{ propertyPath: "transform.scaleX", time: 1, value: 1 },
			{ propertyPath: "transform.scaleY", time: 1, value: 1 },
		],
	},
	{
		id: "rotate-in",
		name: "Rotate In",
		category: "entrance",
		description: "Rotate and scale in",
		keyframes: [
			{ propertyPath: "transform.rotate", time: 0, value: -180 },
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.rotate", time: 1, value: 0 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	{
		id: "flip-in",
		name: "Flip In",
		category: "entrance",
		description: "3D-style flip entrance",
		keyframes: [
			{ propertyPath: "transform.scaleX", time: 0, value: -1 },
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.scaleX", time: 0.5, value: 0 },
			{ propertyPath: "transform.scaleX", time: 1, value: 1 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	{
		id: "blur-in",
		name: "Blur In",
		category: "entrance",
		description: "Fade in with motion blur feel",
		keyframes: [
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.scaleX", time: 0, value: 1.1 },
			{ propertyPath: "transform.scaleY", time: 0, value: 1.1 },
			{ propertyPath: "opacity", time: 1, value: 100 },
			{ propertyPath: "transform.scaleX", time: 1, value: 1 },
			{ propertyPath: "transform.scaleY", time: 1, value: 1 },
		],
	},
	{
		id: "bounce-in",
		name: "Bounce In",
		category: "entrance",
		description: "Bouncy entrance with multiple bounces",
		keyframes: [
			{ propertyPath: "transform.positionY", time: 0, value: 200 },
			{ propertyPath: "transform.positionY", time: 0.6, value: -30 },
			{ propertyPath: "transform.positionY", time: 0.8, value: 15 },
			{ propertyPath: "transform.positionY", time: 0.9, value: -5 },
			{ propertyPath: "transform.positionY", time: 1, value: 0 },
		],
	},
	// EXIT
	{
		id: "fade-out",
		name: "Fade Out",
		category: "exit",
		description: "Fade out to invisible",
		keyframes: [
			{ propertyPath: "opacity", time: 0, value: 100 },
			{ propertyPath: "opacity", time: 1, value: 0 },
		],
	},
	{
		id: "slide-out-left",
		name: "Slide Out Left",
		category: "exit",
		description: "Slide out to the left",
		keyframes: [
			{ propertyPath: "transform.positionX", time: 0, value: 0 },
			{ propertyPath: "opacity", time: 0, value: 100 },
			{ propertyPath: "transform.positionX", time: 1, value: -200 },
			{ propertyPath: "opacity", time: 1, value: 0 },
		],
	},
	{
		id: "slide-out-right",
		name: "Slide Out Right",
		category: "exit",
		description: "Slide out to the right",
		keyframes: [
			{ propertyPath: "transform.positionX", time: 0, value: 0 },
			{ propertyPath: "opacity", time: 0, value: 100 },
			{ propertyPath: "transform.positionX", time: 1, value: 200 },
			{ propertyPath: "opacity", time: 1, value: 0 },
		],
	},
	{
		id: "zoom-out",
		name: "Zoom Out",
		category: "exit",
		description: "Scale up and fade out",
		keyframes: [
			{ propertyPath: "opacity", time: 0, value: 100 },
			{ propertyPath: "transform.scaleX", time: 0, value: 1 },
			{ propertyPath: "transform.scaleY", time: 0, value: 1 },
			{ propertyPath: "opacity", time: 1, value: 0 },
			{ propertyPath: "transform.scaleX", time: 1, value: 1.5 },
			{ propertyPath: "transform.scaleY", time: 1, value: 1.5 },
		],
	},
	{
		id: "shrink-out",
		name: "Shrink Out",
		category: "exit",
		description: "Scale down and fade out",
		keyframes: [
			{ propertyPath: "transform.scaleX", time: 0, value: 1 },
			{ propertyPath: "transform.scaleY", time: 0, value: 1 },
			{ propertyPath: "transform.scaleX", time: 1, value: 0 },
			{ propertyPath: "transform.scaleY", time: 1, value: 0 },
			{ propertyPath: "opacity", time: 1, value: 0 },
		],
	},
	// LOOP
	{
		id: "pulse",
		name: "Pulse",
		category: "loop",
		description: "Continuous pulsing scale",
		keyframes: [
			{ propertyPath: "transform.scaleX", time: 0, value: 1 },
			{ propertyPath: "transform.scaleX", time: 0.5, value: 1.1 },
			{ propertyPath: "transform.scaleX", time: 1, value: 1 },
		],
	},
	{
		id: "breathe",
		name: "Breathe",
		category: "loop",
		description: "Slow breathing scale loop",
		keyframes: [
			{ propertyPath: "transform.scaleX", time: 0, value: 1 },
			{ propertyPath: "transform.scaleX", time: 0.5, value: 1.05 },
			{ propertyPath: "transform.scaleX", time: 1, value: 1 },
		],
	},
	{
		id: "shake",
		name: "Shake",
		category: "loop",
		description: "Continuous horizontal shake",
		keyframes: [
			{ propertyPath: "transform.positionX", time: 0, value: 0 },
			{ propertyPath: "transform.positionX", time: 0.1, value: 5 },
			{ propertyPath: "transform.positionX", time: 0.2, value: -5 },
			{ propertyPath: "transform.positionX", time: 0.3, value: 5 },
			{ propertyPath: "transform.positionX", time: 0.4, value: -5 },
			{ propertyPath: "transform.positionX", time: 0.5, value: 5 },
			{ propertyPath: "transform.positionX", time: 0.6, value: -5 },
			{ propertyPath: "transform.positionX", time: 0.7, value: 5 },
			{ propertyPath: "transform.positionX", time: 0.8, value: -5 },
			{ propertyPath: "transform.positionX", time: 0.9, value: 5 },
			{ propertyPath: "transform.positionX", time: 1, value: 0 },
		],
	},
	{
		id: "wave",
		name: "Wave",
		category: "loop",
		description: "Continuous vertical wave motion",
		keyframes: [
			{ propertyPath: "transform.positionY", time: 0, value: 0 },
			{ propertyPath: "transform.positionY", time: 0.25, value: 8 },
			{ propertyPath: "transform.positionY", time: 0.75, value: -8 },
			{ propertyPath: "transform.positionY", time: 1, value: 0 },
		],
	},
	{
		id: "swing",
		name: "Swing",
		category: "loop",
		description: "Continuous swing rotation",
		keyframes: [
			{ propertyPath: "transform.rotate", time: 0, value: -5 },
			{ propertyPath: "transform.rotate", time: 0.5, value: 5 },
			{ propertyPath: "transform.rotate", time: 1, value: -5 },
		],
	},
	{
		id: "jello",
		name: "Jello",
		category: "loop",
		description: "Bouncy jello wiggle",
		keyframes: [
			{ propertyPath: "transform.scaleX", time: 0, value: 1 },
			{ propertyPath: "transform.scaleX", time: 0.25, value: 0.85 },
			{ propertyPath: "transform.scaleX", time: 0.5, value: 1.1 },
			{ propertyPath: "transform.scaleX", time: 0.75, value: 0.95 },
			{ propertyPath: "transform.scaleX", time: 1, value: 1 },
		],
	},
	{
		id: "flicker",
		name: "Flicker",
		category: "loop",
		description: "Flickering opacity loop",
		keyframes: [
			{ propertyPath: "opacity", time: 0, value: 100 },
			{ propertyPath: "opacity", time: 0.1, value: 50 },
			{ propertyPath: "opacity", time: 0.15, value: 100 },
			{ propertyPath: "opacity", time: 0.4, value: 70 },
			{ propertyPath: "opacity", time: 0.45, value: 100 },
			{ propertyPath: "opacity", time: 0.7, value: 60 },
			{ propertyPath: "opacity", time: 0.8, value: 100 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	{
		id: "neon-glow-loop",
		name: "Neon Glow",
		category: "loop",
		description: "Glow opacity loop",
		keyframes: [
			{ propertyPath: "opacity", time: 0, value: 100 },
			{ propertyPath: "opacity", time: 0.5, value: 70 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	// TYPEWRITER
	{
		id: "type-fade",
		name: "Typewriter",
		category: "typewriter",
		description: "Classic typewriter fade-in",
		keyframes: [
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	{
		id: "type-cursor",
		name: "Blink Cursor",
		category: "typewriter",
		description:
			"Text appears with a blinking cursor at the end (static approximation)",
		keyframes: [
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "opacity", time: 0.8, value: 100 },
		],
	},
	// HANDWRITING
	{
		id: "handwriting",
		name: "Handwriting",
		category: "handwriting",
		description: "Text appears as if being written (clip-in approximation)",
		keyframes: [
			{ propertyPath: "transform.scaleX", time: 0, value: 0.05 },
			{ propertyPath: "opacity", time: 0, value: 30 },
			{ propertyPath: "transform.scaleX", time: 1, value: 1 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	{
		id: "ink",
		name: "Ink Reveal",
		category: "handwriting",
		description: "Text appears as if drawn in ink",
		keyframes: [
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.scaleX", time: 0, value: 0.95 },
			{ propertyPath: "transform.scaleY", time: 0, value: 0.95 },
			{ propertyPath: "opacity", time: 0.3, value: 100 },
			{ propertyPath: "transform.scaleX", time: 1, value: 1 },
			{ propertyPath: "transform.scaleY", time: 1, value: 1 },
		],
	},
	// DRAW
	{
		id: "wipe-up",
		name: "Wipe Up",
		category: "draw",
		description: "Reveal with upward wipe",
		keyframes: [
			{ propertyPath: "transform.positionY", time: 0, value: 100 },
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.positionY", time: 1, value: 0 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	{
		id: "wipe-right",
		name: "Wipe Right",
		category: "draw",
		description: "Reveal with rightward wipe",
		keyframes: [
			{ propertyPath: "transform.positionX", time: 0, value: -100 },
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.positionX", time: 1, value: 0 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	{
		id: "mask-reveal",
		name: "Mask Reveal",
		category: "draw",
		description: "Text revealed with a mask (scale-up effect)",
		keyframes: [
			{ propertyPath: "transform.scaleX", time: 0, value: 0.1 },
			{ propertyPath: "opacity", time: 0, value: 30 },
			{ propertyPath: "transform.scaleX", time: 0.7, value: 1 },
			{ propertyPath: "opacity", time: 0.7, value: 100 },
		],
	},
	// More entrance animations
	{
		id: "fly-up-big",
		name: "Fly Up Big",
		category: "entrance",
		description: "Fly in from far below",
		keyframes: [
			{ propertyPath: "transform.positionY", time: 0, value: 500 },
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.positionY", time: 1, value: 0 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	{
		id: "fly-down-big",
		name: "Fly Down Big",
		category: "entrance",
		description: "Fly in from far above",
		keyframes: [
			{ propertyPath: "transform.positionY", time: 0, value: -500 },
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.positionY", time: 1, value: 0 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	{
		id: "fly-left-big",
		name: "Fly Left Big",
		category: "entrance",
		description: "Fly in from far right",
		keyframes: [
			{ propertyPath: "transform.positionX", time: 0, value: 800 },
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.positionX", time: 1, value: 0 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	{
		id: "fly-right-big",
		name: "Fly Right Big",
		category: "entrance",
		description: "Fly in from far left",
		keyframes: [
			{ propertyPath: "transform.positionX", time: 0, value: -800 },
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.positionX", time: 1, value: 0 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	{
		id: "spin-in",
		name: "Spin In",
		category: "entrance",
		description: "Full 360° spin entrance",
		keyframes: [
			{ propertyPath: "transform.rotate", time: 0, value: -360 },
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.rotate", time: 1, value: 0 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	{
		id: "elastic-in",
		name: "Elastic In",
		category: "entrance",
		description: "Elastic bounce entrance",
		keyframes: [
			{ propertyPath: "transform.scaleX", time: 0, value: 0 },
			{ propertyPath: "transform.scaleY", time: 0, value: 0 },
			{ propertyPath: "transform.scaleX", time: 0.6, value: 1.2 },
			{ propertyPath: "transform.scaleY", time: 0.6, value: 1.2 },
			{ propertyPath: "transform.scaleX", time: 0.8, value: 0.9 },
			{ propertyPath: "transform.scaleY", time: 0.8, value: 0.9 },
			{ propertyPath: "transform.scaleX", time: 1, value: 1 },
			{ propertyPath: "transform.scaleY", time: 1, value: 1 },
		],
	},
	{
		id: "tilt-in",
		name: "Tilt In",
		category: "entrance",
		description: "Tilted slide-in entrance",
		keyframes: [
			{ propertyPath: "transform.rotate", time: 0, value: 15 },
			{ propertyPath: "transform.positionX", time: 0, value: -300 },
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.rotate", time: 1, value: 0 },
			{ propertyPath: "transform.positionX", time: 1, value: 0 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	{
		id: "ramp-up",
		name: "Ramp Up",
		category: "entrance",
		description: "Scale up from 0 with overshoot",
		keyframes: [
			{ propertyPath: "transform.scaleX", time: 0, value: 0 },
			{ propertyPath: "transform.scaleY", time: 0, value: 0 },
			{ propertyPath: "transform.scaleX", time: 0.7, value: 1.2 },
			{ propertyPath: "transform.scaleY", time: 0.7, value: 1.2 },
			{ propertyPath: "transform.scaleX", time: 1, value: 1 },
			{ propertyPath: "transform.scaleY", time: 1, value: 1 },
		],
	},
	{
		id: "skew-in",
		name: "Skew In",
		category: "entrance",
		description: "Skewed entrance with horizontal slide",
		keyframes: [
			{ propertyPath: "transform.scaleX", time: 0, value: 0.5 },
			{ propertyPath: "transform.positionX", time: 0, value: -100 },
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.scaleX", time: 1, value: 1 },
			{ propertyPath: "transform.positionX", time: 1, value: 0 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	{
		id: "drop-down",
		name: "Drop Down",
		category: "entrance",
		description: "Drop from above with bounce",
		keyframes: [
			{ propertyPath: "transform.positionY", time: 0, value: -300 },
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.positionY", time: 0.7, value: 20 },
			{ propertyPath: "transform.positionY", time: 1, value: 0 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	// More exit animations
	{
		id: "fly-up-out",
		name: "Fly Up",
		category: "exit",
		description: "Fly out upward",
		keyframes: [
			{ propertyPath: "transform.positionY", time: 0, value: 0 },
			{ propertyPath: "opacity", time: 0, value: 100 },
			{ propertyPath: "transform.positionY", time: 1, value: -500 },
			{ propertyPath: "opacity", time: 1, value: 0 },
		],
	},
	{
		id: "fly-down-out",
		name: "Fly Down",
		category: "exit",
		description: "Fly out downward",
		keyframes: [
			{ propertyPath: "transform.positionY", time: 0, value: 0 },
			{ propertyPath: "opacity", time: 0, value: 100 },
			{ propertyPath: "transform.positionY", time: 1, value: 500 },
			{ propertyPath: "opacity", time: 1, value: 0 },
		],
	},
	{
		id: "spin-out",
		name: "Spin Out",
		category: "exit",
		description: "Spin and fade out",
		keyframes: [
			{ propertyPath: "transform.rotate", time: 0, value: 0 },
			{ propertyPath: "opacity", time: 0, value: 100 },
			{ propertyPath: "transform.rotate", time: 1, value: 360 },
			{ propertyPath: "opacity", time: 1, value: 0 },
		],
	},
	{
		id: "fall-out",
		name: "Fall",
		category: "exit",
		description: "Fall down with gravity",
		keyframes: [
			{ propertyPath: "transform.positionY", time: 0, value: 0 },
			{ propertyPath: "transform.rotate", time: 0, value: 0 },
			{ propertyPath: "transform.positionY", time: 1, value: 400 },
			{ propertyPath: "transform.rotate", time: 1, value: 90 },
			{ propertyPath: "opacity", time: 1, value: 0 },
		],
	},
	{
		id: "burst-out",
		name: "Burst",
		category: "exit",
		description: "Burst outward and fade",
		keyframes: [
			{ propertyPath: "transform.scaleX", time: 0, value: 1 },
			{ propertyPath: "transform.scaleY", time: 0, value: 1 },
			{ propertyPath: "transform.scaleX", time: 0.5, value: 1.5 },
			{ propertyPath: "transform.scaleY", time: 0.5, value: 1.5 },
			{ propertyPath: "transform.scaleX", time: 1, value: 0 },
			{ propertyPath: "transform.scaleY", time: 1, value: 0 },
			{ propertyPath: "opacity", time: 1, value: 0 },
		],
	},
	// More loops
	{
		id: "float",
		name: "Float",
		category: "loop",
		description: "Gentle float up and down",
		keyframes: [
			{ propertyPath: "transform.positionY", time: 0, value: 0 },
			{ propertyPath: "transform.positionY", time: 0.5, value: -10 },
			{ propertyPath: "transform.positionY", time: 1, value: 0 },
		],
	},
	{
		id: "wobble",
		name: "Wobble",
		category: "loop",
		description: "Side-to-side wobble",
		keyframes: [
			{ propertyPath: "transform.rotate", time: 0, value: 0 },
			{ propertyPath: "transform.rotate", time: 0.25, value: 3 },
			{ propertyPath: "transform.rotate", time: 0.75, value: -3 },
			{ propertyPath: "transform.rotate", time: 1, value: 0 },
		],
	},
	{
		id: "glitch",
		name: "Glitch",
		category: "loop",
		description: "Glitchy jitter loop",
		keyframes: [
			{ propertyPath: "transform.positionX", time: 0, value: 0 },
			{ propertyPath: "transform.positionX", time: 0.1, value: 8 },
			{ propertyPath: "transform.positionX", time: 0.15, value: -8 },
			{ propertyPath: "transform.positionX", time: 0.25, value: 4 },
			{ propertyPath: "transform.positionX", time: 0.3, value: 0 },
			{ propertyPath: "opacity", time: 0.15, value: 60 },
			{ propertyPath: "opacity", time: 0.2, value: 100 },
		],
	},
	{
		id: "heartbeat",
		name: "Heartbeat",
		category: "loop",
		description: "Double-pulse heartbeat",
		keyframes: [
			{ propertyPath: "transform.scaleX", time: 0, value: 1 },
			{ propertyPath: "transform.scaleY", time: 0, value: 1 },
			{ propertyPath: "transform.scaleX", time: 0.1, value: 1.15 },
			{ propertyPath: "transform.scaleY", time: 0.1, value: 1.15 },
			{ propertyPath: "transform.scaleX", time: 0.2, value: 1 },
			{ propertyPath: "transform.scaleY", time: 0.2, value: 1 },
			{ propertyPath: "transform.scaleX", time: 0.3, value: 1.2 },
			{ propertyPath: "transform.scaleY", time: 0.3, value: 1.2 },
			{ propertyPath: "transform.scaleX", time: 0.4, value: 1 },
			{ propertyPath: "transform.scaleY", time: 0.4, value: 1 },
			{ propertyPath: "transform.scaleX", time: 0.7, value: 1 },
			{ propertyPath: "transform.scaleY", time: 0.7, value: 1 },
			{ propertyPath: "transform.scaleX", time: 0.8, value: 1.15 },
			{ propertyPath: "transform.scaleY", time: 0.8, value: 1.15 },
			{ propertyPath: "transform.scaleX", time: 0.9, value: 1 },
			{ propertyPath: "transform.scaleY", time: 0.9, value: 1 },
		],
	},
	{
		id: "pendulum",
		name: "Pendulum",
		category: "loop",
		description: "Slow pendulum swing",
		keyframes: [
			{ propertyPath: "transform.rotate", time: 0, value: -10 },
			{ propertyPath: "transform.rotate", time: 0.5, value: 10 },
			{ propertyPath: "transform.rotate", time: 1, value: -10 },
		],
	},
	{
		id: "color-pulse",
		name: "Color Pulse",
		category: "loop",
		description: "Pulsing color shift (brightness proxy)",
		keyframes: [
			{ propertyPath: "opacity", time: 0, value: 100 },
			{ propertyPath: "opacity", time: 0.5, value: 75 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	// More draw
	{
		id: "wipe-down",
		name: "Wipe Down",
		category: "draw",
		description: "Reveal with downward wipe",
		keyframes: [
			{ propertyPath: "transform.positionY", time: 0, value: -100 },
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.positionY", time: 1, value: 0 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	{
		id: "wipe-left",
		name: "Wipe Left",
		category: "draw",
		description: "Reveal with leftward wipe",
		keyframes: [
			{ propertyPath: "transform.positionX", time: 0, value: 100 },
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.positionX", time: 1, value: 0 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	{
		id: "diagonal-wipe",
		name: "Diagonal Wipe",
		category: "draw",
		description: "Reveal with diagonal motion",
		keyframes: [
			{ propertyPath: "transform.positionX", time: 0, value: -100 },
			{ propertyPath: "transform.positionY", time: 0, value: -100 },
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.positionX", time: 1, value: 0 },
			{ propertyPath: "transform.positionY", time: 1, value: 0 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	{
		id: "split-open",
		name: "Split Open",
		category: "draw",
		description: "Split open from center",
		keyframes: [
			{ propertyPath: "transform.scaleX", time: 0, value: 0 },
			{ propertyPath: "transform.scaleY", time: 0, value: 1.2 },
			{ propertyPath: "transform.scaleX", time: 1, value: 1 },
			{ propertyPath: "transform.scaleY", time: 1, value: 1 },
		],
	},
	// More typewriter
	{
		id: "type-elastic",
		name: "Type Elastic",
		category: "typewriter",
		description: "Typewriter with elastic reveal",
		keyframes: [
			{ propertyPath: "transform.scaleX", time: 0, value: 0.1 },
			{ propertyPath: "transform.scaleY", time: 0, value: 1.4 },
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.scaleX", time: 0.8, value: 1.05 },
			{ propertyPath: "transform.scaleY", time: 0.8, value: 0.95 },
			{ propertyPath: "transform.scaleX", time: 1, value: 1 },
			{ propertyPath: "transform.scaleY", time: 1, value: 1 },
			{ propertyPath: "opacity", time: 0.7, value: 100 },
		],
	},
	{
		id: "type-bounce",
		name: "Type Bounce",
		category: "typewriter",
		description: "Typewriter with bouncy characters",
		keyframes: [
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.positionY", time: 0, value: 30 },
			{ propertyPath: "opacity", time: 0.6, value: 100 },
			{ propertyPath: "transform.positionY", time: 0.6, value: 0 },
			{ propertyPath: "transform.positionY", time: 0.7, value: -10 },
			{ propertyPath: "transform.positionY", time: 0.8, value: 0 },
		],
	},
	// More handwriting
	{
		id: "neon-write",
		name: "Neon Write",
		category: "handwriting",
		description: "Glow-in dark handwriting effect",
		keyframes: [
			{ propertyPath: "transform.scaleX", time: 0, value: 0.1 },
			{ propertyPath: "opacity", time: 0, value: 20 },
			{ propertyPath: "transform.scaleX", time: 1, value: 1 },
			{ propertyPath: "opacity", time: 0.5, value: 60 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	{
		id: "marker-write",
		name: "Marker Write",
		category: "handwriting",
		description: "Marker stroke handwriting",
		keyframes: [
			{ propertyPath: "transform.scaleX", time: 0, value: 0.05 },
			{ propertyPath: "transform.scaleY", time: 0, value: 1.1 },
			{ propertyPath: "opacity", time: 0, value: 50 },
			{ propertyPath: "transform.scaleX", time: 0.8, value: 1.02 },
			{ propertyPath: "transform.scaleY", time: 0.8, value: 0.98 },
			{ propertyPath: "transform.scaleX", time: 1, value: 1 },
			{ propertyPath: "transform.scaleY", time: 1, value: 1 },
		],
	},
	// Specialty effects
	{
		id: "neon-flicker",
		name: "Neon Flicker",
		category: "entrance",
		description: "Flickering neon light reveal",
		keyframes: [
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "opacity", time: 0.1, value: 100 },
			{ propertyPath: "opacity", time: 0.2, value: 30 },
			{ propertyPath: "opacity", time: 0.3, value: 100 },
			{ propertyPath: "opacity", time: 0.4, value: 50 },
			{ propertyPath: "opacity", time: 0.5, value: 100 },
			{ propertyPath: "opacity", time: 0.7, value: 80 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	{
		id: "holographic",
		name: "Holographic",
		category: "entrance",
		description: "Holographic materialization",
		keyframes: [
			{ propertyPath: "transform.scaleY", time: 0, value: 0.1 },
			{ propertyPath: "transform.positionY", time: 0, value: 50 },
			{ propertyPath: "opacity", time: 0, value: 20 },
			{ propertyPath: "transform.positionX", time: 0, value: -10 },
			{ propertyPath: "transform.scaleY", time: 0.5, value: 1.05 },
			{ propertyPath: "transform.positionX", time: 0.5, value: 5 },
			{ propertyPath: "transform.positionX", time: 1, value: 0 },
			{ propertyPath: "transform.scaleY", time: 1, value: 1 },
			{ propertyPath: "transform.positionY", time: 1, value: 0 },
			{ propertyPath: "opacity", time: 1, value: 100 },
		],
	},
	{
		id: "shake-in",
		name: "Shake In",
		category: "entrance",
		description: "Shake-in entrance with overshoot",
		keyframes: [
			{ propertyPath: "transform.positionX", time: 0, value: 0 },
			{ propertyPath: "transform.positionX", time: 0.05, value: 15 },
			{ propertyPath: "transform.positionX", time: 0.1, value: -15 },
			{ propertyPath: "transform.positionX", time: 0.15, value: 10 },
			{ propertyPath: "transform.positionX", time: 0.2, value: -10 },
			{ propertyPath: "transform.positionX", time: 0.25, value: 5 },
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "opacity", time: 0.3, value: 100 },
			{ propertyPath: "transform.positionX", time: 1, value: 0 },
		],
	},
	{
		id: "swing-in",
		name: "Swing In",
		category: "entrance",
		description: "Swinging pendulum entrance",
		keyframes: [
			{ propertyPath: "transform.rotate", time: 0, value: -90 },
			{ propertyPath: "transform.positionY", time: 0, value: -200 },
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.rotate", time: 0.5, value: 15 },
			{ propertyPath: "transform.rotate", time: 0.7, value: -10 },
			{ propertyPath: "transform.rotate", time: 0.85, value: 5 },
			{ propertyPath: "transform.rotate", time: 1, value: 0 },
			{ propertyPath: "transform.positionY", time: 1, value: 0 },
			{ propertyPath: "opacity", time: 0.5, value: 100 },
		],
	},
	{
		id: "vibrate",
		name: "Vibrate",
		category: "loop",
		description: "Fast vibration loop",
		keyframes: [
			{ propertyPath: "transform.positionX", time: 0, value: 0 },
			{ propertyPath: "transform.positionX", time: 0.05, value: 2 },
			{ propertyPath: "transform.positionX", time: 0.1, value: -2 },
			{ propertyPath: "transform.positionX", time: 0.15, value: 2 },
			{ propertyPath: "transform.positionX", time: 0.2, value: -2 },
			{ propertyPath: "transform.positionX", time: 0.25, value: 2 },
			{ propertyPath: "transform.positionX", time: 0.3, value: -2 },
			{ propertyPath: "transform.positionX", time: 0.35, value: 2 },
			{ propertyPath: "transform.positionX", time: 0.4, value: -2 },
			{ propertyPath: "transform.positionX", time: 0.45, value: 2 },
			{ propertyPath: "transform.positionX", time: 0.5, value: -2 },
			{ propertyPath: "transform.positionX", time: 1, value: 0 },
		],
	},
	{
		id: "zoom-loop",
		name: "Zoom Pulse",
		category: "loop",
		description: "Continuous zoom pulse",
		keyframes: [
			{ propertyPath: "transform.scaleX", time: 0, value: 1 },
			{ propertyPath: "transform.scaleY", time: 0, value: 1 },
			{ propertyPath: "transform.scaleX", time: 0.5, value: 1.08 },
			{ propertyPath: "transform.scaleY", time: 0.5, value: 1.08 },
			{ propertyPath: "transform.scaleX", time: 1, value: 1 },
			{ propertyPath: "transform.scaleY", time: 1, value: 1 },
		],
	},
	{
		id: "spin-loop",
		name: "Continuous Spin",
		category: "loop",
		description: "Continuous 360° rotation",
		keyframes: [
			{ propertyPath: "transform.rotate", time: 0, value: 0 },
			{ propertyPath: "transform.rotate", time: 1, value: 360 },
		],
	},
	{
		id: "swing-out",
		name: "Swing Out",
		category: "exit",
		description: "Swing out and fade",
		keyframes: [
			{ propertyPath: "transform.rotate", time: 0, value: 0 },
			{ propertyPath: "opacity", time: 0, value: 100 },
			{ propertyPath: "transform.rotate", time: 0.5, value: 15 },
			{ propertyPath: "transform.rotate", time: 1, value: -90 },
			{ propertyPath: "transform.positionY", time: 1, value: 200 },
			{ propertyPath: "opacity", time: 1, value: 0 },
		],
	},
	{
		id: "explode-out",
		name: "Explode",
		category: "exit",
		description: "Explode outward with rotation",
		keyframes: [
			{ propertyPath: "transform.scaleX", time: 0, value: 1 },
			{ propertyPath: "transform.scaleY", time: 0, value: 1 },
			{ propertyPath: "opacity", time: 0, value: 100 },
			{ propertyPath: "transform.scaleX", time: 0.5, value: 1.3 },
			{ propertyPath: "transform.scaleY", time: 0.5, value: 1.3 },
			{ propertyPath: "transform.rotate", time: 0.5, value: 20 },
			{ propertyPath: "transform.scaleX", time: 1, value: 2 },
			{ propertyPath: "transform.scaleY", time: 1, value: 2 },
			{ propertyPath: "transform.rotate", time: 1, value: 90 },
			{ propertyPath: "opacity", time: 1, value: 0 },
		],
	},
	{
		id: "type-scramble",
		name: "Type Scramble",
		category: "typewriter",
		description: "Typewriter with random letter positions (approximation)",
		keyframes: [
			{ propertyPath: "transform.positionY", time: 0, value: 20 },
			{ propertyPath: "opacity", time: 0, value: 0 },
			{ propertyPath: "transform.positionX", time: 0.1, value: 10 },
			{ propertyPath: "transform.positionX", time: 0.2, value: -10 },
			{ propertyPath: "transform.positionY", time: 0.3, value: 10 },
			{ propertyPath: "transform.positionX", time: 0.4, value: 5 },
			{ propertyPath: "transform.positionY", time: 0.5, value: -5 },
			{ propertyPath: "transform.positionX", time: 0.6, value: 0 },
			{ propertyPath: "transform.positionY", time: 0.6, value: 0 },
			{ propertyPath: "opacity", time: 0.6, value: 100 },
		],
	},
	{
		id: "rubber-band",
		name: "Rubber Band",
		category: "loop",
		description: "Rubber band stretch loop",
		keyframes: [
			{ propertyPath: "transform.scaleX", time: 0, value: 1 },
			{ propertyPath: "transform.scaleY", time: 0, value: 1 },
			{ propertyPath: "transform.scaleX", time: 0.3, value: 1.25 },
			{ propertyPath: "transform.scaleY", time: 0.3, value: 0.75 },
			{ propertyPath: "transform.scaleX", time: 0.5, value: 0.85 },
			{ propertyPath: "transform.scaleY", time: 0.5, value: 1.15 },
			{ propertyPath: "transform.scaleX", time: 0.7, value: 1.1 },
			{ propertyPath: "transform.scaleY", time: 0.7, value: 0.9 },
			{ propertyPath: "transform.scaleX", time: 1, value: 1 },
			{ propertyPath: "transform.scaleY", time: 1, value: 1 },
		],
	},
	{
		id: "ken-burns",
		name: "Ken Burns",
		category: "entrance",
		description: "Slow zoom and pan (cinematic)",
		keyframes: [
			{ propertyPath: "transform.scaleX", time: 0, value: 0.85 },
			{ propertyPath: "transform.scaleY", time: 0, value: 0.85 },
			{ propertyPath: "transform.positionX", time: 0, value: -20 },
			{ propertyPath: "transform.positionY", time: 0, value: -20 },
			{ propertyPath: "transform.scaleX", time: 1, value: 1.15 },
			{ propertyPath: "transform.scaleY", time: 1, value: 1.15 },
			{ propertyPath: "transform.positionX", time: 1, value: 20 },
			{ propertyPath: "transform.positionY", time: 1, value: 20 },
		],
	},
];

export const TEXT_ANIM_CATEGORIES: { id: TextAnimCategory; label: string }[] = [
	{ id: "entrance", label: "In" },
	{ id: "exit", label: "Out" },
	{ id: "loop", label: "Loop" },
	{ id: "typewriter", label: "Typewriter" },
	{ id: "handwriting", label: "Handwriting" },
	{ id: "draw", label: "Draw" },
];
