/**
 * 500 AI chat suggestions for the EmptyState component.
 *
 * Each suggestion has a short label and a full prompt text. The
 * EmptyState picks 4 at random on each mount so the user sees fresh
 * ideas every time they open a new chat.
 *
 * Categories are mixed (text, video, audio, effects, color, motion,
 * workflow, social) to cover the full range of what the AI copilot
 * can do. Icons are assigned by category at render time, not stored
 * here, to keep the data compact.
 */

export interface Suggestion {
	label: string;
	text: string;
}

export const SUGGESTIONS: Suggestion[] = [
	// ── Text & Typography ──────────────────────────────────────────
	{ label: "Text animation", text: "Add a 'Subscribe' text animation at the end of the timeline." },
	{ label: "Kinetic type", text: "Create kinetic typography from the first 10 seconds of audio." },
	{ label: "Title card", text: "Add a bold title card with a fade-in over 1 second at the start." },
	{ label: "Lower third", text: "Add a lower-third name banner that slides in from the left." },
	{ label: "End screen", text: "Create an end-screen with 'Thanks for watching' and a subscribe button overlay." },
	{ label: "Caption pop", text: "Make the captions pop in with a scale bounce on each word." },
	{ label: "Typewriter", text: "Add a typewriter effect to the intro text, 15 characters per second." },
	{ label: "Glitch text", text: "Apply a glitch text effect to the title with RGB split and jitter." },
	{ label: "Neon glow", text: "Add a neon glow text layer that pulses with the beat." },
	{ label: "3D text", text: "Create a 3D extruded text title that rotates slightly on the Y axis." },
	{ label: "Text reveal", text: "Mask-reveal the heading text from left to right over 0.8 seconds." },
	{ label: "Word-by-word", text: "Reveal the caption one word at a time, synced to the audio." },
	{ label: "Subtitle style", text: "Style all subtitles with a yellow background and bold black text." },
	{ label: "Call to action", text: "Add a 'Swipe up' call-to-action text that fades in at the 3-second mark." },
	{ label: "Quote card", text: "Display a motivational quote in serif font, centered, with a slow zoom." },
	{ label: "Chapter marker", text: "Add chapter marker text overlays at 0:00, 0:30, and 1:15." },
	{ label: "Counter text", text: "Create an animated counter from 0 to 1000 over 3 seconds." },
	{ label: "Marquee", text: "Add a scrolling marquee text at the bottom showing the channel name." },
	{ label: "Text shadow", text: "Add a soft drop shadow to all text layers for readability." },
	{ label: "Bold intro", text: "Create a bold full-screen intro text that slams in with a shake." },

	// ── Cutting & Pacing ───────────────────────────────────────────
	{ label: "Auto-cut", text: "Cut every 2 seconds, alternating between two clips." },
	{ label: "Beat sync", text: "Cut on every beat detected in the audio track." },
	{ label: "Jedag-jedug", text: "Make this jedag-jedug: detect beats in the audio, then split the video clip on every beat." },
	{ label: "Skew (nyerong)", text: "Apply a skew transform to this clip — pull the top-right up and bottom-left down for a slanted look." },
	{ label: "Quick cuts", text: "Make rapid 0.3-second cuts during the chorus section." },
	{ label: "Jump cut", text: "Remove all silence gaps and jump-cut the talking head segments together." },
	{ label: "Smooth pacing", text: "Slow down the cut frequency after the 30-second mark for a calmer middle section." },
	{ label: "Match cut", text: "Create match cuts between clips where the motion direction aligns." },
	{ label: "Montage", text: "Build a 15-second montage with 1-second cuts from all available clips." },
	{ label: "Speed ramp", text: "Speed ramp the first clip from 50% to 100% over 2 seconds." },
	{ label: "Whip pan", text: "Add whip-pan transition effects between each cut." },
	{ label: "Flash cut", text: "Insert a 2-frame white flash between every cut." },
	{ label: "J-cut", text: "Create J-cuts where the audio starts 0.5s before the video cut." },
	{ label: "L-cut", text: "Create L-cuts where the audio extends 0.5s past the video cut." },
	{ label: "Crossfade", text: "Replace all hard cuts with 0.3-second crossfades." },
	{ label: "Hard cut intro", text: "Start with 5 hard cuts in the first 3 seconds for a punchy intro." },
	{ label: "Slow build", text: "Gradually increase cut frequency from 4s cuts to 1s cuts over 30 seconds." },
	{ label: "Trailer cut", text: "Build a trailer-style cut: slow intro, fast middle, dramatic pause, fast finale." },
	{ label: "Loop segment", text: "Loop the 2-second segment at 0:15 three times for emphasis." },
	{ label: "Reverse cut", text: "Play the last clip in reverse for 1 second before the final cut." },
	{ label: "Freeze frame", text: "Freeze-frame on the last frame of the first clip for 1.5 seconds." },
	{ label: "Time remap", text: "Time-remap the middle section to 200% speed for a comedic effect." },

	// ── Color & Grading ────────────────────────────────────────────
	{ label: "Cinematic grade", text: "Apply a cinematic teal-and-orange color grade to all clips." },
	{ label: "Vintage film", text: "Add a vintage film look with warm tones and slight vignette." },
	{ label: "Black & white", text: "Convert the first 5 seconds to black and white for a flashback effect." },
	{ label: "High contrast", text: "Push the contrast up and saturation down for a moody look." },
	{ label: "Warm sunset", text: "Apply a warm sunset color grade with golden highlights." },
	{ label: "Cool blue", text: "Apply a cool blue tint for a cold, clinical atmosphere." },
	{ label: "Bleach bypass", text: "Apply a bleach bypass look: high contrast, low saturation." },
	{ label: "VHS look", text: "Add a VHS aesthetic with color bleeding and scan lines." },
	{ label: "Sepia tone", text: "Apply a sepia tone to the entire timeline for a nostalgic feel." },
	{ label: "Pastel wash", text: "Apply a soft pastel color wash with lifted shadows." },
	{ label: "Neon grade", text: "Apply a neon cyberpunk grade with magenta and cyan tones." },
	{ label: "Faded film", text: "Apply a faded film look with lifted blacks and muted colors." },
	{ label: "Color pop", text: "Keep the subject in color and desaturate the background." },
	{ label: "Day for night", text: "Apply a day-for-night grade with blue tones and darkened exposure." },
	{ label: "Orange highlight", text: "Boost the orange in highlight areas for a golden hour look." },
	{ label: "Matte finish", text: "Apply a matte finish by lifting blacks to 15 and reducing contrast." },
	{ label: "Cross process", text: "Apply a cross-processed color look with shifted greens." },
	{ label: "LUT apply", text: "Apply a film emulation LUT to all video clips." },
	{ label: "Saturation boost", text: "Boost saturation by 30% on all clips for a vibrant look." },
	{ label: "Color match", text: "Match the color grade of clip 1 to all other clips." },

	// ── Effects & Filters ──────────────────────────────────────────
	{ label: "Remove background", text: "Remove the background from this clip — isolate the subject and drop the backdrop to transparent." },
	{ label: "Cut out subject", text: "Apply the Remove Background effect to all video clips so only the subjects remain." },
	{ label: "Green screen", text: "Apply a chroma key to remove the green screen background from this clip." },
	{ label: "Vignette", text: "Add a subtle vignette to all clips, darkening the edges by 20%." },
	{ label: "Gaussian blur", text: "Add a 5px Gaussian blur to the background layer only." },
	{ label: "Glow effect", text: "Add a soft glow effect to the bright areas of each clip." },
	{ label: "Chromatic aberration", text: "Add chromatic aberration to the edges of the frame." },
	{ label: "Film grain", text: "Add film grain at 15% intensity across the whole timeline." },
	{ label: "Lens flare", text: "Add a lens flare at the 5-second mark that sweeps across the frame." },
	{ label: "Light leak", text: "Add a warm light leak overlay that drifts across the frame." },
	{ label: "Halation", text: "Add a halation effect around bright areas for a filmic glow." },
	{ label: "Mirror flip", text: "Mirror-flip the video horizontally at the halfway point." },
	{ label: "Pixelate", text: "Pixelate the screen for 1 second at the 10-second mark." },
	{ label: "Zoom blur", text: "Add a zoom blur transition between the first two clips." },
	{ label: "Radial blur", text: "Add a radial blur that spins during the transition." },
	{ label: "Edge detect", text: "Apply an edge-detection effect for a sketch look on one clip." },
	{ label: "Posterize", text: "Posterize the colors to 4 levels for a stylized look." },
	{ label: "Kaleidoscope", text: "Apply a kaleidoscope effect with 6 segments for 2 seconds." },
	{ label: "Shake effect", text: "Add a camera shake effect at 0.5 intensity during the drop." },
	{ label: "RGB split", text: "Add an RGB split effect with 3px offset during fast cuts." },
	{ label: "Scan lines", text: "Add CRT scan lines overlay at 30% opacity." },
	{ label: "Bokeh overlay", text: "Add a bokeh light overlay in the background." },
	{ label: "Prism effect", text: "Add a prism light split effect during the intro." },

	// ── Motion & Animation ─────────────────────────────────────────
	{ label: "Parallax intro", text: "Build a 3-layer parallax intro that resolves in 1.5 seconds." },
	{ label: "Zoom in", text: "Add a slow zoom-in from 100% to 120% over the entire clip." },
	{ label: "Zoom out", text: "Add a slow zoom-out from 130% to 100% over 5 seconds." },
	{ label: "Pan right", text: "Pan the camera from left to right over 3 seconds." },
	{ label: "Ken Burns", text: "Apply a Ken Burns effect with slow pan and zoom to each photo." },
	{ label: "Scale pulse", text: "Make the video scale-pulse on every beat of the audio." },
	{ label: "Slide in", text: "Slide each clip in from the right with a 0.3-second ease." },
	{ label: "Bounce in", text: "Make text elements bounce in with an elastic ease." },
	{ label: "Spin transition", text: "Add a 360-degree spin transition between clips." },
	{ label: "Push transition", text: "Add a push transition where each clip pushes the previous one off screen." },
	{ label: "Wipe transition", text: "Add a left-to-right wipe transition between all clips." },
	{ label: "Iris transition", text: "Add a circular iris transition between the intro and main content." },
	{ label: "Morph transition", text: "Add a smooth morph transition between the two title cards." },
	{ label: "Glitch transition", text: "Add a glitch transition with 3 frames of RGB split between clips." },
	{ label: "Smooth ease", text: "Apply a smooth ease-in-out to all keyframe animations." },
	{ label: "Snap zoom", text: "Add a snap-zoom from 100% to 150% and back over 0.2 seconds." },
	{ label: "Dolly zoom", text: "Create a dolly zoom effect by scaling the background and foreground differently." },
	{ label: "Floating text", text: "Make the title text float gently up and down with a sine wave." },
	{ label: "Orbit camera", text: "Create a 180-degree orbit camera move around the subject." },
	{ label: "Tilt up", text: "Add a slow tilt-up camera movement over 4 seconds." },

	// ── Audio & Music ──────────────────────────────────────────────
	{ label: "Audio → motion", text: "Take the audio waveform and turn it into a motion path." },
	{ label: "Fade in audio", text: "Fade in the audio from 0 to full over 2 seconds at the start." },
	{ label: "Fade out audio", text: "Fade out the audio over the last 3 seconds." },
	{ label: "Duck music", text: "Duck the music volume by 12dB whenever there's speech." },
	{ label: "Beat marker", text: "Add a visual beat marker flash on every kick drum hit." },
	{ label: "Audio spectrum", text: "Create an audio spectrum visualizer bar at the bottom of the screen." },
	{ label: "Normalize audio", text: "Normalize the audio to -14 LUFS for platform delivery." },
	{ label: "Reverb tail", text: "Add a 1-second reverb tail to the final audio segment." },
	{ label: "Speed up audio", text: "Speed up the audio by 150% without changing pitch." },
	{ label: "Slow down audio", text: "Slow down the audio to 75% speed without changing pitch." },
	{ label: "EQ boost", text: "Boost the bass frequencies by 6dB for a warmer sound." },
	{ label: "High-pass", text: "Apply a high-pass filter at 80Hz to remove rumble." },
	{ label: "Audio reverse", text: "Reverse the audio for a 2-second dream sequence at 0:20." },
	{ label: "Stutter effect", text: "Add a 0.1-second stutter effect on the audio at the drop." },
	{ label: "Vinyl crackle", text: "Add a vinyl crackle sound effect at 10% volume during the intro." },
	{ label: "Echo delay", text: "Add a quarter-note echo delay to the final word of the voiceover." },
	{ label: "Sidechain", text: "Add a sidechain compression effect to the music, pumping with the kick." },
	{ label: "Mute gaps", text: "Mute all audio gaps shorter than 0.5 seconds." },
	{ label: "Audio swap", text: "Swap the background music with a more upbeat track." },
	{ label: "Voice enhance", text: "Enhance the voice track with compression and de-essing." },

	// ── Social Media Formats ───────────────────────────────────────
	{ label: "60s reel", text: "Make this a 60-second reel: trim the longest clip, add captions, drop a beat-synced zoom on each cut." },
	{ label: "TikTok format", text: "Resize to 9:16 vertical and reposition all elements for TikTok." },
	{ label: "YouTube intro", text: "Create a 5-second YouTube intro with the channel name and logo." },
	{ label: "Instagram story", text: "Resize to 9:16 and add a 'Swipe up' sticker at the bottom." },
	{ label: "Short teaser", text: "Create a 15-second teaser from the best moments." },
	{ label: "Square crop", text: "Resize to 1:1 square for Instagram feed." },
	{ label: "Portrait crop", text: "Resize to 4:5 portrait for Instagram feed." },
	{ label: "Thumbnail", text: "Create a YouTube thumbnail frame at 0:05 with bold text overlay." },
	{ label: "End card", text: "Add a 10-second end card with video suggestions and subscribe button." },
	{ label: "Stinger", text: "Create a 3-second brand stinger with logo animation." },
	{ label: "Bumper ad", text: "Create a 6-second bumper ad version of the video." },
	{ label: "Vertical safe", text: "Ensure all text is within the 9:16 safe zone for vertical formats." },
	{ label: "Caption burn", text: "Burn in captions for social media where subtitles are turned off by default." },
	{ label: "Watermark", text: "Add a small channel logo watermark in the top-right corner." },
	{ label: "Progress bar", text: "Add a progress bar at the top for Reels and Shorts format." },
	{ label: "Hook frame", text: "Move the most visually striking frame to the 0:00 position as the hook." },
	{ label: "Loop point", text: "Set a seamless loop point at 0:00 and 0:15 for a boomerang effect." },
	{ label: "CTA overlay", text: "Add a 'Follow for more' CTA overlay that appears at the 10-second mark." },
	{ label: "Tag overlay", text: "Add '@username' tag overlays on featured people in the video." },
	{ label: "Brand colors", text: "Apply brand colors to all text and graphic elements." },

	// ── Workflow & Productivity ────────────────────────────────────
	{ label: "Auto-caption", text: "Generate captions for the entire video and style them with a clean white font." },
	{ label: "Remove silence", text: "Remove all silent gaps longer than 0.5 seconds to tighten the edit." },
	{ label: "Batch resize", text: "Resize all images to fit the canvas without distortion." },
	{ label: "Organize tracks", text: "Organize all elements into tracks by type: video, text, audio, effects." },
	{ label: "Clean timeline", text: "Remove all empty gaps and overlapping elements from the timeline." },
	{ label: "Export preset", text: "Set up the project for 1080p 30fps MP4 export with H.264." },
	{ label: "Backup snapshot", text: "Create a snapshot of the current timeline state before making changes." },
	{ label: "Template save", text: "Save the current text animation as a reusable template." },
	{ label: "Batch apply", text: "Apply the same color grade to all clips at once." },
	{ label: "Auto-level", text: "Auto-level the audio across all clips to consistent volume." },
	{ label: "Scene detect", text: "Detect scene changes and add a cut at each transition point." },
	{ label: "Marker add", text: "Add timeline markers at every beat for easy reference." },
	{ label: "Track color", text: "Color-code each track by content type for visual organization." },
	{ label: "Lock audio", text: "Lock the audio track to prevent accidental edits." },
	{ label: "Rename clips", text: "Rename all clips with descriptive names based on their content." },
	{ label: "Sort by length", text: "Sort clips on the timeline from shortest to longest." },
	{ label: "Duplicate scene", text: "Duplicate the first scene and modify the copy for a before/after comparison." },
	{ label: "Reset transforms", text: "Reset all transform properties to default on selected elements." },
	{ label: "Align center", text: "Align all text layers to the horizontal center of the canvas." },
	{ label: "Snap to grid", text: "Snap all elements to a 20px grid for clean alignment." },

	// ── Transitions ────────────────────────────────────────────────
	{ label: "Smooth dissolve", text: "Add 0.5-second cross-dissolves between all clips." },
	{ label: "Flash transition", text: "Add a white flash transition between each clip." },
	{ label: "Zoom transition", text: "Add a quick zoom-in transition between clips." },
	{ label: "Slide transition", text: "Add a horizontal slide transition between clips." },
	{ label: "Wipe transition", text: "Add a diagonal wipe transition between scenes." },
	{ label: "Blur transition", text: "Add a blur transition that fades from blurred to sharp." },
	{ label: "Glitch transition", text: "Add a digital glitch transition with 3 frames of distortion." },
	{ label: "Spin transition", text: "Add a 180-degree spin transition between clips." },
	{ label: "Push transition", text: "Add a push transition where the new clip slides over the old one." },
	{ label: "Iris transition", text: "Add a circular iris open transition at the start." },
	{ label: "Cube transition", text: "Add a 3D cube rotation transition between scenes." },
	{ label: "Morph transition", text: "Add a smooth morph transition between two similar clips." },
	{ label: "Light transition", text: "Add a light sweep transition that flashes across the frame." },
	{ label: "Ink transition", text: "Add an ink bleed transition for an artistic effect." },
	{ label: "Pixel transition", text: "Add a pixel dissolve transition between clips." },
	{ label: "Ripple transition", text: "Add a ripple distortion transition between scenes." },
	{ label: "Burn transition", text: "Add a film burn transition for a vintage effect." },
	{ label: "Door transition", text: "Add a sliding door transition that opens to reveal the next clip." },
	{ label: "Venetian blind", text: "Add a venetian blind wipe transition between clips." },
	{ label: "Checkerboard", text: "Add a checkerboard dissolve transition between scenes." },

	// ── Background & Environment ───────────────────────────────────
	{ label: "Blur background", text: "Set the background to blur mode with intensity 12." },
	{ label: "Color background", text: "Set the background to a dark navy color (#0a0a1a)." },
	{ label: "Gradient bg", text: "Create a gradient background from dark blue to black." },
	{ label: "Animated bg", text: "Add a slowly moving particle background behind the text." },
	{ label: "Solid white", text: "Set the background to solid white for a clean product look." },
	{ label: "Solid black", text: "Set the background to solid black for a cinematic look." },
	{ label: "Image bg", text: "Use the first frame of the video as a blurred background." },
	{ label: "Pattern bg", text: "Add a subtle dot pattern background at 5% opacity." },
	{ label: "Gradient overlay", text: "Add a bottom-to-top dark gradient overlay for text readability." },
	{ label: "Vignette bg", text: "Add a radial vignette to the background, darkening the edges." },
	{ label: "Noise bg", text: "Add a subtle noise texture to the background at 8% opacity." },
	{ label: "Mesh gradient", text: "Create an animated mesh gradient background that slowly shifts colors." },
	{ label: "Aurora bg", text: "Add an aurora-like flowing color background behind the main content." },
	{ label: "Star field", text: "Add a starfield background with slowly twinkling stars." },
	{ label: "Bokeh bg", text: "Add a bokeh light background with soft circular highlights." },
	{ label: "Grid bg", text: "Add a subtle 40px grid background for a tech aesthetic." },
	{ label: "Paper texture", text: "Add a paper texture background for a handmade feel." },
	{ label: "Glassmorphism", text: "Add a glassmorphism backdrop blur behind text panels." },
	{ label: "Spotlight bg", text: "Add a spotlight gradient background focusing on the center." },
	{ label: "Color wash", text: "Add a slow color wash that cycles through warm tones." },

	// ── Speed & Time Effects ───────────────────────────────────────
	{ label: "Slow motion", text: "Slow down the middle section to 40% speed for dramatic effect." },
	{ label: "Speed ramp", text: "Speed ramp from 100% to 300% and back during the transition." },
	{ label: "Time freeze", text: "Freeze the frame at 0:10 for 2 seconds, then resume." },
	{ label: "Hyper lapse", text: "Speed up the landscape clip to 500% for a hyperlapse effect." },
	{ label: "Reverse clip", text: "Reverse the last 3 seconds of the video for a rewind effect." },
	{ label: "Loop back", text: "Play the clip forward then immediately reverse it for a ping-pong loop." },
	{ label: "Step motion", text: "Create a step-motion effect by dropping to 12fps for a stop-motion look." },
	{ label: "Echo effect", text: "Add a motion echo with 3 trailing copies at 20% opacity each." },
	{ label: "Time slice", text: "Create a bullet-time effect by freezing and rotating around the subject." },
	{ label: "Speed gradient", text: "Gradually increase speed from 50% to 200% across the entire clip." },
	{ label: "Strobe freeze", text: "Freeze every 4th frame for 0.1 seconds for a strobe effect." },
	{ label: "Reverse intro", text: "Play the intro in reverse, then play it forward for a reveal." },
	{ label: "Slow zoom", text: "Combine a slow zoom with 50% speed for a dramatic slow-motion push-in." },
	{ label: "Speed cut", text: "Alternate between 200% speed and 50% speed on each cut." },
	{ label: "Frame hold", text: "Hold on frame 0 for 1 second, then play at normal speed." },
	{ label: "Time stretch", text: "Stretch the final 2 seconds to 5 seconds for a dramatic ending." },
	{ label: "Burst speed", text: "Speed up to 800% for 0.2 seconds between each normal-speed segment." },
	{ label: "Ghost trail", text: "Add a ghosting trail effect that lingers for 5 frames during fast motion." },
	{ label: "Skip frames", text: "Skip every other frame for a choppy, energetic look." },
	{ label: "Morph time", text: "Create a time morph that smoothly transitions from slow to fast." },

	// ── Creative & Artistic ────────────────────────────────────────
	{ label: "Dream sequence", text: "Create a dream sequence with soft focus, glow, and slow motion at 0:20." },
	{ label: "Memory flashback", text: "Add a sepia-toned flashback with film grain at the 15-second mark." },
	{ label: "Split screen", text: "Create a 2-way split screen showing two clips side by side." },
	{ label: "Picture in picture", text: "Add a picture-in-picture overlay of the reaction cam in the corner." },
	{ label: "Collage", text: "Build a 4-panel video collage with different angles." },
	{ label: "Double exposure", text: "Create a double exposure effect blending two clips together." },
	{ label: "Silhouette", text: "Create a silhouette effect by darkening the subject against a bright background." },
	{ label: "Shadow play", text: "Create a shadow puppet effect with high contrast and warm light." },
	{ label: "Stop motion", text: "Convert the footage to a stop-motion look with 6fps and slight jitter." },
	{ label: "Paper cutout", text: "Create a paper cutout animation style with flat colors and hard edges." },
	{ label: "Watercolor", text: "Apply a watercolor painting effect to the video." },
	{ label: "Comic book", text: "Apply a comic book halftone effect with bold outlines." },
	{ label: "Sketch effect", text: "Apply a pencil sketch effect to one clip for an artistic transition." },
	{ label: "Mosaic", text: "Create a mosaic tile effect with 20px blocks." },
	{ label: "Stained glass", text: "Apply a stained glass effect with geometric color regions." },
	{ label: "Origami fold", text: "Create an origami fold transition where the frame folds into a triangle." },
	{ label: "Ink splash", text: "Add an ink splash reveal transition from black to the video." },
	{ label: "Cloud transition", text: "Transition through a cloud layer that dissipates to reveal the next clip." },
	{ label: "Glass shatter", text: "Add a glass shatter transition where the frame cracks and breaks apart." },
	{ label: "Paint drip", text: "Add a paint drip transition where colors melt down the frame." },

	// ── Text Styling ───────────────────────────────────────────────
	{ label: "Bold serif", text: "Style the title with a bold serif font in white at 48px." },
	{ label: "Clean sans", text: "Use a clean sans-serif font at 24px for all captions." },
	{ label: "Mono code", text: "Style the tech text with a monospace font in green on black." },
	{ label: "Handwritten", text: "Use a handwritten-style font for the personal message section." },
	{ label: "Gradient text", text: "Apply a gradient fill to the title text from pink to purple." },
	{ label: "Outline text", text: "Add a white outline to all text for readability on busy backgrounds." },
	{ label: "Bold caps", text: "Make all heading text uppercase, bold, with wide letter spacing." },
	{ label: "Text gradient", text: "Apply a gold gradient to the 'Subscribe' text." },
	{ label: "Animated underline", text: "Add an animated underline that draws in under the heading." },
	{ label: "Text bracket", text: "Add decorative brackets around the title text." },
	{ label: "Text badge", text: "Put the section title inside a rounded badge with a solid color background." },
	{ label: "Strikethrough", text: "Add a strikethrough animation on the old price, revealing the new price." },
	{ label: "Text scatter", text: "Make the text letters scatter and reform on the beat." },
	{ label: "Vertical text", text: "Rotate the side label text 90 degrees for a vertical reading style." },
	{ label: "Text arc", text: "Curve the title text into an arc shape." },
	{ label: "Glow text", text: "Add a soft outer glow to the text in a matching color." },
	{ label: "3D shadow", text: "Add a 3D extruded shadow to the text for depth." },
	{ label: "Text mask", text: "Use the video as a mask inside the text letters." },
	{ label: "Typing cursor", text: "Add a blinking cursor after the typewriter text effect." },
	{ label: "Text counter", text: "Animate a number counter from 1 to 100 in the text layer." },

	// ── Multi-cam & Angles ─────────────────────────────────────────
	{ label: "Multi-cam switch", text: "Switch between camera angles every 4 seconds for a multi-cam edit." },
	{ label: "Angle cut on beat", text: "Switch camera angles on every beat for a music video feel." },
	{ label: "Reaction cam", text: "Add a reaction cam in the bottom-right corner that pops in during key moments." },
	{ label: "Drone shot", text: "Feature the drone shot as the opening clip with a slow descent." },
	{ label: "POV angle", text: "Start with the POV angle clip for an immersive intro." },
	{ label: "Wide to close", text: "Go from wide shot to close-up over 3 cuts for increasing tension." },
	{ label: "Close to wide", text: "Start close-up and pull back to wide for a reveal moment." },
	{ label: "Over-the-shoulder", text: "Alternate between over-the-shoulder angles for a conversation scene." },
	{ label: "Top-down", text: "Feature the top-down angle clip as a section break." },
	{ label: "Low angle", text: "Use the low-angle shot for the dramatic moment at 0:25." },
	{ label: "Dutch tilt", text: "Add a 15-degree Dutch tilt to the tension section." },
	{ label: "Bird's eye", text: "Cut to the bird's eye view for the montage section." },
	{ label: "Two-shot", text: "Use the two-shot angle for the dialogue section." },
	{ label: "Insert shot", text: "Cut to an insert shot of the hands at 0:15 for detail." },
	{ label: "Match angle", text: "Match the camera angle across cuts for seamless continuity." },
	{ label: "Cross-cut", text: "Cross-cut between two simultaneous actions to build suspense." },
	{ label: "Rack focus", text: "Simulate a rack focus from foreground to background." },
	{ label: "Whip pan cut", text: "Use whip pans to hide cuts between different angle shots." },
	{ label: "Zoom to close", text: "Slowly zoom from the wide angle to a close-up over 5 seconds." },
	{ label: "Angle contrast", text: "Alternate between high-angle and low-angle shots for visual variety." },

	// ── Export & Delivery ──────────────────────────────────────────
	{ label: "4K export", text: "Set up the project for 4K UHD export at 60fps." },
	{ label: "Web optimize", text: "Optimize the export settings for web delivery with a 10Mbps bitrate." },
	{ label: "GIF export", text: "Create a 3-second looping GIF from the best moment." },
	{ label: "PNG sequence", text: "Export the title animation as a PNG sequence for overlay use." },
	{ label: "Audio extract", text: "Extract just the audio track as a separate MP3 file." },
	{ label: "WebM export", text: "Set up WebM export with VP9 codec for web embedding." },
	{ label: "ProRes export", text: "Set up ProRes 422 export for post-production handoff." },
	{ label: "GIF loop", text: "Create a perfectly looping GIF from the 2-second segment at 0:10." },
	{ label: "Thumbnail export", text: "Export a high-quality thumbnail frame at 0:05." },
	{ label: "GIF sticker", text: "Export the text animation as a transparent GIF sticker." },
	{ label: "Lower thirds", text: "Export the lower-third animation as a transparent overlay video." },
	{ label: "Short clip", text: "Export just the first 15 seconds as a separate preview clip." },
	{ label: "Stinger export", text: "Export the 3-second brand stinger as a standalone video." },
	{ label: "Audio stem", text: "Export the music and voice tracks as separate audio stems." },
	{ label: "Frame export", text: "Export every 10th frame as a JPEG for a contact sheet." },
	{ label: "Vertical export", text: "Export a 9:16 vertical version alongside the main 16:9 export." },
	{ label: "Square export", text: "Export a 1:1 square version for Instagram feed." },
	{ label: "Low res preview", text: "Export a low-resolution 480p preview for quick sharing." },
	{ label: "High quality", text: "Set export to maximum quality with 20Mbps bitrate and 4:2:2 color." },
	{ label: "Compressed", text: "Set export to a compressed 5Mbps for email-friendly file size." },

	// ── Advanced Compositing ───────────────────────────────────────
	{ label: "Layer mask", text: "Add a layer mask to the top clip revealing only the left half." },
	{ label: "Track matte", text: "Use the text layer as a track matte to show video inside the letters." },
	{ label: "Blend mode", text: "Set the overlay layer blend mode to 'Screen' for a light effect." },
	{ label: "Multiply blend", text: "Set the texture overlay to 'Multiply' blend mode at 40% opacity." },
	{ label: "Overlay blend", text: "Set the grain layer to 'Overlay' blend mode at 15% opacity." },
	{ label: "Alpha channel", text: "Export the title animation with an alpha channel for transparency." },
	{ label: "Depth matte", text: "Create a depth-based matte that blurs the background progressively." },
	{ label: "Color key", text: "Key out the green screen background and replace it with a gradient." },
	{ label: "Luma key", text: "Use a luma key to remove the bright background from the product shot." },
	{ label: "Rotoscope", text: "Create a rotoscope mask around the subject for isolated color grading." },
	{ label: "Shadow layer", text: "Add a separate shadow layer below the text, offset by 3px." },
	{ label: "Reflection", text: "Add a mirrored reflection of the product at 30% opacity below it." },
	{ label: "Glow layer", text: "Add a separate glow layer behind the text at 50% opacity." },
	{ label: "Particle layer", text: "Add a floating particle layer at 20% opacity for atmosphere." },
	{ label: "Light ray", text: "Add animated light rays emanating from the title text." },
	{ label: "Lens distortion", text: "Add a subtle lens distortion to the overlay layer for depth." },
	{ label: "Parallax layers", text: "Set up 3 parallax layers with different speeds for a 2.5D effect." },
	{ label: "Ambient occlusion", text: "Add fake ambient occlusion shadows around text elements." },
	{ label: "Bloom pass", text: "Add a bloom pass to brighten highlights across all layers." },
	{ label: "Depth of field", text: "Add a depth-of-field blur that focuses on the center subject." },

	// ── Music Video Style ──────────────────────────────────────────
	{ label: "Music video cut", text: "Edit this like a music video with fast cuts on every beat." },
	{ label: "Beat drop", text: "Add a massive visual effect at the beat drop at 0:30." },
	{ label: "Build-up", text: "Create a visual build-up with increasing speed and intensity before the drop." },
	{ label: "Verse-chorus", text: "Edit verse sections with slow cuts and chorus sections with fast cuts." },
	{ label: "Lip sync", text: "Cut to the lip-sync clip on every vocal phrase." },
	{ label: "Performance mix", text: "Mix performance and B-roll clips, cutting to performance on vocals." },
	{ label: "Beat zoom", text: "Add a quick zoom punch on every kick drum hit." },
	{ label: "Flash on snare", text: "Add a single-frame white flash on every snare hit." },
	{ label: "Color shift on drop", text: "Shift the color grade dramatically at the beat drop." },
	{ label: "Strobe on build", text: "Add a strobe effect that increases in speed during the build-up." },
	{ label: "Mirror on bridge", text: "Mirror the frame during the bridge section for a dreamy feel." },
	{ label: "Reverse on drop", text: "Play the clip in reverse for 1 second right before the drop." },
	{ label: "Freeze on pause", text: "Freeze the frame during the musical pause at 0:45." },
	{ label: "Speed ramp on fill", text: "Speed ramp during the drum fill leading into the chorus." },
	{ label: "Glitch on drop", text: "Add a glitch effect on the beat drop with RGB split." },
	{ label: "Zoom on hook", text: "Slowly zoom in during the hook section for intimacy." },
	{ label: "Wide on verse", text: "Use wide shots during verses and close-ups during the chorus." },
	{ label: "Vignette pulse", text: "Make the vignette pulse with the bass line." },
	{ label: "Text on hook", text: "Display the song title text during the hook section." },
	{ label: "End fade", text: "Fade to black with the music at the end of the video." },

	// ── Documentary & Interview ────────────────────────────────────
	{ label: "Interview clean", text: "Clean up the interview: remove ums, tighten gaps, add lower thirds." },
	{ label: "B-roll cutaway", text: "Add B-roll cutaways over the talking head every 5 seconds." },
	{ label: "Name title", text: "Add a name and title lower-third for the speaker at their first appearance." },
	{ label: "Chapter title", text: "Add chapter title cards between each topic section." },
	{ label: "Quote highlight", text: "Pull the best quote and display it full-screen for 3 seconds." },
	{ label: "Stat overlay", text: "Add an animated statistic overlay with a counter during the data section." },
	{ label: "Map graphic", text: "Add a map graphic showing the location being discussed." },
	{ label: "Timeline graphic", text: "Add an animated timeline graphic for the historical section." },
	{ label: "Archival look", text: "Apply an archival film look to the historical footage sections." },
	{ label: "Subtle zoom", text: "Add a very slow zoom on the interview subject to keep it dynamic." },
	{ label: "Cut on thought", text: "Cut the interview on natural thought breaks, not just sentences." },
	{ label: "Reaction shot", text: "Add reaction shots from the interviewer at key emotional moments." },
	{ label: "Text emphasis", text: "Highlight key words from the interview as text overlays." },
	{ label: "Transition topic", text: "Use a distinct transition between topic sections for clarity." },
	{ label: "Pacing vary", text: "Vary the pacing: slow for emotional parts, faster for informational parts." },
	{ label: "Music bed", text: "Add a subtle music bed at 15% volume under the interview." },
	{ label: "Establishing shot", text: "Add an establishing shot at the beginning of each new location." },
	{ label: "Voiceover layer", text: "Add a voiceover layer explaining the B-roll footage." },
	{ label: "Date stamp", text: "Add a date stamp overlay on archival footage sections." },
	{ label: "End card credit", text: "Add a credits end card thanking all interview participants." },

	// ── Gaming Content ─────────────────────────────────────────────
	{ label: "Gaming highlight", text: "Create a gaming highlight reel from the best 5 moments, each 3 seconds long." },
	{ label: "Kill feed", text: "Add a kill feed overlay in the top-right corner showing recent eliminations." },
	{ label: "Slow-mo replay", text: "Add a slow-motion replay of the best moment at 25% speed." },
	{ label: "Zoom to action", text: "Zoom into the action area during the clutch moment." },
	{ label: "Flash on hit", text: "Add a subtle screen flash on every critical hit moment." },
	{ label: "Combo counter", text: "Add an animated combo counter that increments on each successive hit." },
	{ label: "Victory text", text: "Add a 'VICTORY' text animation at the end of the clip." },
	{ label: "Game over", text: "Add a 'GAME OVER' text animation with a glitch effect." },
	{ label: "Speed up boring", text: "Speed up the slow parts to 400% and keep the action at normal speed." },
	{ label: "Reaction pop", text: "Pop in a reaction face cam during the funniest moments." },
	{ label: "Health bar", text: "Add a fake health bar overlay that depletes during the fight." },
	{ label: "Score popup", text: "Add animated score popups when points are scored." },
	{ label: "Level up", text: "Add a 'LEVEL UP' animation with a golden glow effect." },
	{ label: "Boss intro", text: "Create a boss intro card with dramatic text and a dark vignette." },
	{ label: "Final kill", text: "Add a slow-motion zoom on the final kill with a flash transition." },
	{ label: "Gaming montage", text: "Create a 30-second gaming montage with beat-synced cuts." },
	{ label: "Tutorial step", text: "Add numbered step overlays for the tutorial section." },
	{ label: "Bug highlight", text: "Highlight the bug with a red circle and arrow." },
	{ label: "Speed run", text: "Create a speedrun compilation with a timer overlay." },
	{ label: "Loot reveal", text: "Add a golden glow effect when rare loot is revealed." },

	// ── Product & Commercial ───────────────────────────────────────
	{ label: "Product showcase", text: "Create a product showcase with a 360-degree rotation and clean white background." },
	{ label: "Feature highlight", text: "Add feature highlight text callouts pointing to product details." },
	{ label: "Before/after", text: "Create a before-and-after split screen comparison." },
	{ label: "Price reveal", text: "Add an animated price reveal with a confetti burst effect." },
	{ label: "Logo sting", text: "Create a 2-second logo sting with a metallic shine sweep." },
	{ label: "Product spin", text: "Add a smooth 360-degree product spin over 3 seconds." },
	{ label: "Feature list", text: "Display 3 key features as animated bullet points." },
	{ label: "CTA button", text: "Add a 'Buy Now' call-to-action button that pulses gently." },
	{ label: "Testimonial", text: "Overlay a customer testimonial quote with a star rating." },
	{ label: "Limited offer", text: "Add a 'Limited Time Offer' banner with a countdown timer." },
	{ label: "Product zoom", text: "Zoom into the product detail at 0:05 for a close-up feature." },
	{ label: "Brand intro", text: "Create a brand intro animation with the company colors and logo." },
	{ label: "Social proof", text: "Add a 'Join 10,000+ customers' social proof overlay." },
	{ label: "Benefit text", text: "Display the main benefit as large text: 'Save 10 hours every week'." },
	{ label: "Demo flow", text: "Create a product demo flow: problem, solution, result in 15 seconds." },
	{ label: "Unboxing", text: "Create an unboxing-style reveal with the product emerging from a box." },
	{ label: "Comparison", text: "Create a side-by-side product comparison with checkmarks." },
	{ label: "Guarantee badge", text: "Add a '100% Satisfaction Guarantee' badge with a shield icon." },
	{ label: "Free shipping", text: "Add a 'Free Shipping' banner at the bottom of the screen." },
	{ label: "End logo", text: "End with the brand logo centered on a clean background for 2 seconds." },

	// ── Event & Wedding ────────────────────────────────────────────
	{ label: "Wedding highlight", text: "Create a 60-second wedding highlight reel with romantic music and soft transitions." },
	{ label: "Event recap", text: "Build a 2-minute event recap with the best moments from all footage." },
	{ label: "Ceremony edit", text: "Edit the ceremony with multiple camera angles and clean audio." },
	{ label: "Reception party", text: "Create a high-energy reception party montage with beat-synced cuts." },
	{ label: "Vow highlight", text: "Pull the vow exchange as a highlighted 30-second clip with text overlay." },
	{ label: "First dance", text: "Feature the first dance with a slow-motion effect and soft glow." },
	{ label: "Guest messages", text: "Compile guest messages into a 2-minute heartfelt compilation." },
	{ label: "Venue establishing", text: "Add establishing shots of the venue at the start of each section." },
	{ label: "Detail shots", text: "Insert detail shots (rings, flowers, table settings) between key moments." },
	{ label: "Drone venue", text: "Feature the drone shot of the venue as the opening shot." },
	{ label: "Slow dance", text: "Add a slow-motion effect to the dance sections at 50% speed." },
	{ label: "Golden hour", text: "Apply a warm golden hour grade to the outdoor shots." },
	{ label: "Bouquet toss", text: "Highlight the bouquet toss with a freeze-frame and zoom." },
	{ label: "Cake cutting", text: "Feature the cake cutting with a close-up and a flash transition." },
	{ label: "Send-off", text: "End with the send-off shot in slow motion with a fade to white." },
	{ label: "Conference talk", text: "Edit the conference talk with slides as picture-in-picture." },
	{ label: "Panel discussion", text: "Edit the panel with angle switches on each speaker change." },
	{ label: "Award ceremony", text: "Highlight the award moment with a dramatic zoom and applause audio." },
	{ label: "Backstage", text: "Add a backstage B-roll section with candid moments." },
	{ label: "Sponsor logos", text: "Add animated sponsor logo lower-thirds during the intro." },

	// ── Education & Tutorial ───────────────────────────────────────
	{ label: "Tutorial intro", text: "Create a tutorial intro with 'In this video, you'll learn...' text overlay." },
	{ label: "Step numbers", text: "Add numbered step indicators for each part of the tutorial." },
	{ label: "Code highlight", text: "Add syntax-highlighted code overlays for the programming tutorial." },
	{ label: "Screen zoom", text: "Zoom into the relevant part of the screen during each step." },
	{ label: "Progress bar", text: "Add a tutorial progress bar showing how far through the lesson we are." },
	{ label: "Key takeaway", text: "Display 'Key Takeaway' text overlays at the end of each section." },
	{ label: "Quiz card", text: "Add a quiz question card overlay at the 2-minute mark." },
	{ label: "Recap section", text: "Add a 10-second recap of all steps at the end of the tutorial." },
	{ label: "Resource link", text: "Display a resource link overlay with a QR code for download." },
	{ label: "Chapter list", text: "Add a chapter list overlay at the start showing all sections." },
	{ label: "Diagram overlay", text: "Add an animated diagram overlay explaining the concept." },
	{ label: "Before tutorial", text: "Show the before state at the start for context." },
	{ label: "After result", text: "Show the finished result at the end for satisfaction." },
	{ label: "Tip callout", text: "Add 'Pro Tip' callout boxes during advanced sections." },
	{ label: "Warning callout", text: "Add 'Warning' callout boxes for common mistakes." },
	{ label: "Shortcut display", text: "Display keyboard shortcuts as animated text overlays." },
	{ label: "Cursor highlight", text: "Add a highlight circle around the cursor for click visibility." },
	{ label: "Section divider", text: "Add clear section dividers between tutorial parts." },
	{ label: "Summary card", text: "Add a summary card at the end listing all steps covered." },
	{ label: "Subscribe prompt", text: "Add a 'Subscribe for more tutorials' prompt at the end." },

	// ── Mood & Atmosphere ──────────────────────────────────────────
	{ label: "Dreamy glow", text: "Add a dreamy glow with soft focus and lifted highlights throughout." },
	{ label: "Dark moody", text: "Create a dark, moody atmosphere with crushed blacks and cool tones." },
	{ label: "Bright cheerful", text: "Make it bright and cheerful with lifted exposure and warm tones." },
	{ label: "Tense build", text: "Build tension with a slowly tightening vignette and increasing contrast." },
	{ label: "Calm serene", text: "Create a calm, serene mood with slow motion and soft pastel colors." },
	{ label: "Energetic punch", text: "Add energetic punch with fast cuts, high saturation, and bright colors." },
	{ label: "Mysterious fog", text: "Add a mysterious fog overlay with low contrast and cool tones." },
	{ label: "Nostalgic warm", text: "Create a nostalgic warm mood with sepia tones and film grain." },
	{ label: "Futuristic cool", text: "Create a futuristic cool mood with blue tones and clean lines." },
	{ label: "Romantic soft", text: "Add a romantic soft focus with warm golden tones and gentle glow." },
	{ label: "Horror dark", text: "Create a horror atmosphere with extreme contrast, desaturation, and vignette." },
	{ label: "Summer bright", text: "Create a bright summer vibe with high saturation and warm highlights." },
	{ label: "Winter cold", text: "Create a cold winter mood with blue tones and frosty highlights." },
	{ label: "Sunset golden", text: "Add a golden sunset mood with warm orange tones and soft glow." },
	{ label: "Night neon", text: "Create a neon night mood with vibrant magenta and cyan colors." },
	{ label: "Vintage retro", text: "Add a vintage retro mood with faded colors and film grain." },
	{ label: "Clean modern", text: "Create a clean modern look with crisp contrast and neutral colors." },
	{ label: "Ethereal light", text: "Add an ethereal light atmosphere with soft bloom and lifted shadows." },
	{ label: "Gritty raw", text: "Create a gritty raw look with high contrast and muted colors." },
	{ label: "Soft pastel", text: "Add a soft pastel mood with gentle colors and low contrast." },

	// ── Technical Fixes ────────────────────────────────────────────
	{ label: "Stabilize", text: "Stabilize the shaky footage in the first clip." },
	{ label: "Fix exposure", text: "Fix the underexposed clip by lifting the exposure by 1.5 stops." },
	{ label: "White balance", text: "Correct the white balance on the indoor clips to remove the orange tint." },
	{ label: "Remove noise", text: "Apply noise reduction to the low-light clips." },
	{ label: "Fix audio sync", text: "Fix the audio sync drift by aligning the audio to the first clap." },
	{ label: "Remove hum", text: "Remove the 60Hz electrical hum from the audio track." },
	{ label: "De-interlace", text: "De-interlace the footage for a clean progressive look." },
	{ label: "Lens correct", text: "Apply lens distortion correction to the wide-angle clips." },
	{ label: "Fix rolling shutter", text: "Fix the rolling shutter wobble in the fast pan clips." },
	{ label: "Audio cleanup", text: "Clean up the audio: remove background noise, hum, and clicks." },
	{ label: "Flicker fix", text: "Fix the flickering in the time-lapse footage." },
	{ label: "Color match", text: "Match the color temperature between the indoor and outdoor clips." },
	{ label: "Sharpen", text: "Apply subtle sharpening to the soft-focus clips." },
	{ label: "Defocus fix", text: "Fix the slightly out-of-focus clip with a deblur filter." },
	{ label: "Aspect fix", text: "Fix the aspect ratio distortion on the imported clips." },
	{ label: "Frame rate", text: "Convert the 60fps footage to 30fps with motion blur for a cinematic look." },
	{ label: "Audio level", text: "Balance the audio levels so all clips are at -6dB." },
	{ label: "Remove echo", text: "Remove the room echo from the voiceover audio." },
	{ label: "Fix green cast", text: "Remove the green color cast from the fluorescent-lit footage." },
	{ label: "Crop fix", text: "Re-crop the footage to remove the black bars on the sides." },

	// ── Creative Transitions ───────────────────────────────────────
	{ label: "Match cut motion", text: "Create match cuts where the motion direction aligns between clips." },
	{ label: "Shape transition", text: "Use a circle expanding from the center as a transition between scenes." },
	{ label: "Text transition", text: "Use the next scene's title text as a wipe transition." },
	{ label: "Light flash", text: "Transition with a quick light flash that fills the frame." },
	{ label: "Shadow transition", text: "Transition by sweeping a shadow across the frame from left to right." },
	{ label: "Zoom blur cut", text: "Use a zoom blur to transition between clips, zooming into the cut point." },
	{ label: "Pan transition", text: "Pan across to the next clip as if the camera moved to the next scene." },
	{ label: "Block transition", text: "Use colored blocks that slide in to cover and reveal the next clip." },
	{ label: "Stripe transition", text: "Use horizontal stripes that alternate between the two clips." },
	{ label: "Circle wipe", text: "Use a circle wipe from center outward as the transition." },
	{ label: "Bar transition", text: "Use vertical bars that close and open like curtains." },
	{ label: "Dissolve mask", text: "Dissolve between clips using a gradient mask." },
	{ label: "Flicker transition", text: "Add a flicker transition with 5 rapid cuts between the two clips." },
	{ label: "Scale transition", text: "Scale the current clip down to nothing, then scale the next up from nothing." },
	{ label: "Rotate transition", text: "Rotate the frame 90 degrees to transition to the next clip." },
	{ label: "Slide up", text: "Slide the current clip up and the next clip in from the bottom." },
	{ label: "Reveal transition", text: "Reveal the next clip by lifting a cover from bottom to top." },
	{ label: "Morph cut", text: "Use a morph cut to hide a jump cut in the interview." },
	{ label: "Whip transition", text: "Use a whip pan to blur the transition between two locations." },
	{ label: "Flash white", text: "Flash to white, then reveal the next clip from white." },

	// ── Holiday & Seasonal ─────────────────────────────────────────
	{ label: "Holiday greeting", text: "Create a holiday greeting card animation with snow particles." },
	{ label: "New year countdown", text: "Add a 5-second New Year countdown with animated numbers." },
	{ label: "Halloween spooky", text: "Add a spooky Halloween effect with fog, flickering lights, and orange tones." },
	{ label: "Christmas lights", text: "Add twinkling Christmas light bokeh in the background." },
	{ label: "Valentine hearts", text: "Add floating heart particles for a Valentine's Day video." },
	{ label: "Birthday celebration", text: "Add a birthday celebration overlay with confetti and balloons." },
	{ label: "Summer vibes", text: "Add a summer vibes overlay with sun flares and warm tones." },
	{ label: "Autumn leaves", text: "Add falling autumn leaves particle effect over the video." },
	{ label: "Spring flowers", text: "Add blooming flower animations as a transition effect." },
	{ label: "Winter snow", text: "Add a gentle snowfall overlay across the entire video." },
	{ label: "Fireworks", text: "Add a fireworks celebration overlay at the climax of the video." },
	{ label: "Easter eggs", text: "Add hidden Easter egg animations for viewers to find." },
	{ label: "St Patrick green", text: "Add a green color wash with clover particles for St. Patrick's Day." },
	{ label: "4th of July", text: "Add red, white, and blue confetti for a 4th of July celebration." },
	{ label: "Halloween pumpkins", text: "Add glowing jack-o-lantern silhouettes in the corners." },
	{ label: "Thanksgiving warm", text: "Add a warm Thanksgiving color grade with golden tones." },
	{ label: "Black Friday", text: "Create a Black Friday sale animation with bold text and flashing colors." },
	{ label: "Cyber Monday", text: "Add a Cyber Monday tech-themed overlay with glitch effects." },
	{ label: "Back to school", text: "Add a back-to-school themed intro with chalkboard text." },
	{ label: "Graduation", text: "Create a graduation celebration video with cap-toss animation." },

	// ── Abstract & Experimental ────────────────────────────────────
	{ label: "Abstract loop", text: "Create an abstract looping background with morphing geometric shapes." },
	{ label: "Liquid metal", text: "Add a liquid metal chrome text effect that ripples." },
	{ label: "Fractal zoom", text: "Create a fractal zoom transition that infinitely recurses." },
	{ label: "Particle dissolve", text: "Dissolve the clip into floating particles that reform as the next clip." },
	{ label: "Glass refraction", text: "Add a glass refraction effect that distorts the video behind it." },
	{ label: "Hologram effect", text: "Create a hologram effect with scan lines, blue tint, and glitch." },
	{ label: "Matrix rain", text: "Add a Matrix-style digital rain overlay in the background." },
	{ label: "Data glitch", text: "Create a data corruption effect with random pixel blocks and color shifts." },
	{ label: "Infinite mirror", text: "Create an infinite mirror tunnel effect with recursive zoom." },
	{ label: "Fluid simulation", text: "Add a fluid simulation background with swirling colors." },
	{ label: "Wireframe mode", text: "Convert the video to a wireframe 3D mesh look." },
	{ label: "ASCII art", text: "Convert the video to animated ASCII art for a retro tech look." },
	{ label: "Sound wave bg", text: "Use the audio waveform as an animated background visualization." },
	{ label: "Light painting", text: "Create a light painting effect with trailing light strokes." },
	{ label: "Crystal effect", text: "Add a crystalline refraction effect with faceted light breaks." },
	{ label: "Smoke transition", text: "Transition between clips with a swirling smoke reveal." },
	{ label: "Energy ball", text: "Add an energy ball effect that expands and explodes on the beat." },
	{ label: "Digital rain", text: "Add falling digital code characters as a background layer." },
	{ label: "Prism split", text: "Split the frame into a prism rainbow effect during transitions." },
	{ label: "Gravity shift", text: "Add a gravity shift effect where elements fall in different directions." },

	// ── Quick Fixes & Polish ───────────────────────────────────────
	{ label: "Quick polish", text: "Add a final polish pass: color grade, audio level, and smooth transitions." },
	{ label: "Tighten edit", text: "Tighten the edit by removing 0.2s from the start and end of each clip." },
	{ label: "Add fade in", text: "Add a 1-second fade-in from black at the start of the video." },
	{ label: "Add fade out", text: "Add a 2-second fade-out to black at the end of the video." },
	{ label: "Smooth audio", text: "Smooth all audio transitions with 0.1-second crossfades." },
	{ label: "Color consistency", text: "Make all clips have consistent color temperature and exposure." },
	{ label: "Remove jitter", text: "Remove micro-jitter from handheld footage." },
	{ label: "Add breathing room", text: "Add 0.5 seconds of breathing room between each major section." },
	{ label: "Balance levels", text: "Balance the audio levels so no clip is louder than another." },
	{ label: "Final color check", text: "Do a final color check and fix any clips that look inconsistent." },
	{ label: "Transition polish", text: "Polish all transitions to be smooth and consistent in style." },
	{ label: "Text check", text: "Check all text for readability against the background." },
	{ label: "Pacing check", text: "Review the pacing and adjust any sections that feel too slow or too fast." },
	{ label: "Audio ducking", text: "Add audio ducking so the music dips when someone speaks." },
	{ label: "Background blur", text: "Add a subtle background blur to all text overlay sections." },
	{ label: "Safe margin", text: "Ensure all important content is within the title-safe area." },
	{ label: "Export check", text: "Set the export settings to match the project's resolution and frame rate." },
	{ label: "Loudness target", text: "Set the final audio loudness to -14 LUFS for web delivery." },
	{ label: "Sharpen final", text: "Apply a subtle final sharpening pass to the entire video." },
	{ label: "Vignette final", text: "Add a final subtle vignette for a polished cinematic look." },

	// ── Fun & Creative Prompts ─────────────────────────────────────
	{ label: "Movie trailer", text: "Turn this into a dramatic movie trailer with deep voiceover text and epic music." },
	{ label: "News broadcast", text: "Add a news broadcast style with a lower-third ticker and breaking news graphic." },
	{ label: "Retro game", text: "Add an 8-bit retro game aesthetic with pixelated graphics and chiptune audio." },
	{ label: "ASMR edit", text: "Create an ASMR-style edit with very slow cuts and soft audio." },
	{ label: "Vapor wave", text: "Add a vaporwave aesthetic with pink/purple gradients and retro grid." },
	{ label: "Synthwave", text: "Create a synthwave-style edit with neon grids and 80s sunset colors." },
	{ label: "Lo-fi study", text: "Create a lo-fi study video aesthetic with warm tones and a vintage film look." },
	{ label: "Y2K style", text: "Add a Y2K aesthetic with chrome text, lens flares, and early 2000s graphics." },
	{ label: "Baroque style", text: "Add a baroque-style ornate frame overlay and classical color grade." },
	{ label: "Minimalist", text: "Create a minimalist edit with lots of negative space and clean typography." },
	{ label: "Maximalist", text: "Create a maximalist edit with overlapping elements, bold colors, and rapid cuts." },
	{ label: "Vintage TV", text: "Add a vintage TV look with CRT curvature, scan lines, and slight static." },
	{ label: "Old film", text: "Add an old film projector look with flickering light, dust, and scratches." },
	{ label: "Anime style", text: "Add anime-style speed lines and impact frames during action moments." },
	{ label: "Comic strip", text: "Create a comic strip layout with panels and speech bubbles." },
	{ label: "Silent film", text: "Convert to a silent film style with sepia, title cards, and piano music." },
	{ label: "Nature doc", text: "Edit like a nature documentary with slow pacing and observation-style shots." },
	{ label: "Reality TV", text: "Edit like a reality TV show with quick cutaways and reaction shots." },
	{ label: "Infomercial", text: "Create an infomercial-style edit with enthusiastic text and 'But wait, there's more!' overlays." },
	{ label: "Art film", text: "Create an art film edit with long takes, minimal cuts, and ambient sound." },

	// ── Additional Mixed ───────────────────────────────────────────
	{ label: "Logo build", text: "Animate the logo building piece by piece over 2 seconds." },
	{ label: "Text cascade", text: "Make multiple text lines cascade in from top to bottom sequentially." },
	{ label: "Color flash", text: "Add a single-frame color flash on each cut, alternating between red and blue." },
	{ label: "Audio waveform bg", text: "Display the audio waveform as a subtle background element." },
	{ label: "Beat text", text: "Show the BPM number as text that pulses on every beat." },
	{ label: "Timecode overlay", text: "Add a timecode overlay in the corner for reference." },
	{ label: "Split transition", text: "Split the frame diagonally and slide each half to reveal the next clip." },
	{ label: "Zoom to text", text: "Zoom into the area where text will appear, then reveal the text." },
	{ label: "Pan to subject", text: "Pan from the environment to focus on the main subject." },
	{ label: "Tilt reveal", text: "Tilt the camera up to reveal the full scene from bottom to top." },
	{ label: "Orbit shot", text: "Create a fake orbit by panning the clip in a circular motion." },
	{ label: "Dolly forward", text: "Add a slow dolly-forward effect by gradually scaling up the clip." },
	{ label: "Crane shot", text: "Simulate a crane shot by slowly moving up and scaling slightly." },
	{ label: "Handheld feel", text: "Add a subtle handheld camera shake for a documentary feel." },
	{ label: "Steady cam", text: "Stabilize the footage to look like it was shot on a steady cam." },
	{ label: "Drone reveal", text: "Simulate a drone reveal by slowly pulling back and up." },
	{ label: "Time-lapse", text: "Speed up the clip to 1000% for a time-lapse effect." },
	{ label: "Hyperlapse", text: "Create a hyperlapse by speeding up and adding motion to a static shot." },
	{ label: "Astro-lapse", text: "Create an astro-lapse effect with a star trail overlay." },
	{ label: "Cloud time-lapse", text: "Speed up the sky clip to 800% for a dramatic cloud time-lapse." },
	{ label: "Sunrise speed", text: "Speed up the sunrise clip to 600% for a condensed sunrise." },
	{ label: "Crowd time-lapse", text: "Speed up the crowd footage to 500% for a bustling time-lapse." },
	{ label: "Traffic flow", text: "Create a traffic flow time-lapse at 800% speed with light trails." },
	{ label: "Plant growth", text: "Create a plant growth time-lapse effect with a slow scale-up." },
	{ label: "Shadow time-lapse", text: "Speed up the clip to show shadow movement across the scene." },
	{ label: "Season transition", text: "Create a season transition from summer to winter with a color shift." },
	{ label: "Day to night", text: "Transition from day to night by gradually darkening and cooling the grade." },
	{ label: "Weather change", text: "Add a weather change effect from clear to rainy with an overlay." },
	{ label: "Lighting shift", text: "Gradually shift the lighting from warm to cool over 10 seconds." },
	{ label: "Mood shift", text: "Shift the mood from happy to sad by changing color and pacing at the midpoint." },
	{ label: "Genre shift", text: "Start as a comedy and shift to a thriller at the 30-second mark." },
	{ label: "Perspective shift", text: "Shift from first-person POV to third-person at the key moment." },
	{ label: "Tone shift", text: "Shift from casual to formal tone in both text and pacing at the midpoint." },
	{ label: "Energy build", text: "Build energy gradually from calm to chaotic over 30 seconds." },
	{ label: "Calm after storm", text: "After a high-energy section, drop to complete silence and stillness for 2 seconds." },
	{ label: "False ending", text: "Add a false ending: fade to black, then cut back to a surprise final shot." },
	{ label: "Post-credits", text: "Add a post-credits scene after the end card for 5 seconds." },
	{ label: "Easter egg", text: "Hide a subtle Easter egg frame at 0:33 for viewers to pause and find." },
	{ label: "Secret message", text: "Flash a single-frame secret message at the 15-second mark." },
	{ label: "Hidden frame", text: "Insert a hidden subliminal frame at 0:07 for one frame only." },
	{ label: "Blink text", text: "Add a 'blink and you'll miss it' text flash during the fast cuts." },
	{ label: "Loop hint", text: "Add a visual hint at the end that suggests the video loops back to the start." },
	{ label: "Interactive prompt", text: "Add a 'What would you do?' text prompt at the end for engagement." },
	{ label: "Poll overlay", text: "Add a poll overlay asking viewers to vote in the comments." },
	{ label: "Question card", text: "Add a question card at the end to encourage comments." },
	{ label: "Teaser text", text: "Add 'Part 2 coming soon' teaser text at the very end." },
	{ label: "Countdown end", text: "Add a 3-2-1 countdown at the end before the final cut." },
	{ label: "Beat countdown", text: "Add a beat-synced countdown before the drop." },
	{ label: "Rising tension", text: "Build rising tension with a crescendo music bed and tightening cuts." },
	{ label: "Release tension", text: "After the climax, release tension with a wide static shot for 5 seconds." },
	{ label: "Pattern break", text: "Break an established pattern unexpectedly at the 45-second mark for surprise." },
	{ label: "Rule of thirds", text: "Reposition the subject to follow the rule of thirds." },
	{ label: "Center compose", text: "Center the main subject for a symmetrical composition." },
	{ label: "Leading lines", text: "Enhance the leading lines in the frame to draw attention to the subject." },
	{ label: "Negative space", text: "Add negative space around the subject for a minimalist composition." },
	{ label: "Frame within frame", text: "Create a frame-within-frame composition using doorways or windows." },
	{ label: "Symmetry", text: "Create a perfectly symmetrical frame for a striking shot." },
	{ label: "Golden ratio", text: "Compose the shot following the golden ratio spiral." },
	{ label: "Depth layers", text: "Ensure each shot has foreground, midground, and background depth layers." },
	{ label: "Foreground interest", text: "Add foreground interest elements to make flat shots more dynamic." },
];
