import type { TextElement } from "@/lib/timeline";
import { DEFAULT_NEW_ELEMENT_DURATION } from "@/lib/timeline/creation";

export type TextPresetCategory =
	| "title"
	| "subtitle"
	| "lower-third"
	| "callout"
	| "quote";

export interface TextPreset {
	id: string;
	type: string;
	name: string;
	keywords: string[];
	category: TextPresetCategory;
	build: () => Omit<TextElement, "id" | "startTime">;
}

const baseDefaults = {
	duration: DEFAULT_NEW_ELEMENT_DURATION,
	trimStart: 0,
	trimEnd: 0,
	textAlign: "center" as const,
	fontWeight: "normal" as const,
	fontStyle: "normal" as const,
	textDecoration: "none" as const,
	letterSpacing: 0,
	lineHeight: 1.2,
	hidden: false,
	transform: {
		scaleX: 1,
		scaleY: 1,
		position: { x: 0, y: 0 },
		rotate: 0,
	},
	opacity: 1,
};

export const textPresets: TextPreset[] = [
	{
		id: "title-bold",
		type: "title-bold",
		name: "Big Title",
		keywords: ["title", "headline", "bold"],
		category: "title",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Big Title",
			content: "Your Title",
			fontSize: 24,
			fontFamily: "Arial",
			fontWeight: "bold",
			color: "#ffffff",
			background: {
				enabled: false,
				color: "#000000",
				cornerRadius: 0,
				paddingX: 0,
				paddingY: 0,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "title-minimal",
		type: "title-minimal",
		name: "Minimal Title",
		keywords: ["title", "minimal", "clean"],
		category: "title",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Minimal Title",
			content: "Minimal",
			fontSize: 20,
			fontFamily: "Helvetica",
			fontWeight: "normal",
			color: "#ffffff",
			background: {
				enabled: false,
				color: "#000000",
				cornerRadius: 0,
				paddingX: 0,
				paddingY: 0,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "title-pop",
		type: "title-pop",
		name: "Pop Title",
		keywords: ["title", "pop", "colorful"],
		category: "title",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Pop Title",
			content: "POP!",
			fontSize: 28,
			fontFamily: "Impact",
			fontWeight: "bold",
			color: "#ffeb3b",
			background: {
				enabled: false,
				color: "#000000",
				cornerRadius: 0,
				paddingX: 0,
				paddingY: 0,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "subtitle-classic",
		type: "subtitle-classic",
		name: "Classic Subtitle",
		keywords: ["subtitle", "caption", "classic"],
		category: "subtitle",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Subtitle",
			content: "Subtitle text",
			fontSize: 12,
			fontFamily: "Arial",
			color: "#ffffff",
			background: {
				enabled: true,
				color: "#000000",
				cornerRadius: 4,
				paddingX: 16,
				paddingY: 8,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "subtitle-bold",
		type: "subtitle-bold",
		name: "Bold Subtitle",
		keywords: ["subtitle", "caption", "bold"],
		category: "subtitle",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Bold Subtitle",
			content: "Bold subtitle",
			fontSize: 14,
			fontFamily: "Arial",
			fontWeight: "bold",
			color: "#ffffff",
			background: {
				enabled: true,
				color: "#000000",
				cornerRadius: 6,
				paddingX: 18,
				paddingY: 10,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "lower-third",
		type: "lower-third",
		name: "Lower Third",
		keywords: ["lower", "third", "name", "title"],
		category: "lower-third",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Lower Third",
			content: "Name | Title",
			fontSize: 12,
			fontFamily: "Arial",
			color: "#ffffff",
			textAlign: "left",
			background: {
				enabled: true,
				color: "#000000",
				cornerRadius: 0,
				paddingX: 24,
				paddingY: 14,
				offsetX: -200,
				offsetY: 200,
			},
			transform: {
				...baseDefaults.transform,
				position: { x: 0, y: 250 },
			},
		}),
	},
	{
		id: "lower-third-accent",
		type: "lower-third-accent",
		name: "Lower Third Accent",
		keywords: ["lower", "third", "accent", "color"],
		category: "lower-third",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Lower Third Accent",
			content: "Speaker Name",
			fontSize: 14,
			fontFamily: "Arial",
			fontWeight: "bold",
			color: "#ffffff",
			textAlign: "left",
			background: {
				enabled: true,
				color: "#f97316",
				cornerRadius: 4,
				paddingX: 24,
				paddingY: 14,
				offsetX: 0,
				offsetY: 0,
			},
			transform: {
				...baseDefaults.transform,
				position: { x: 0, y: 250 },
			},
		}),
	},
	{
		id: "callout-rounded",
		type: "callout-rounded",
		name: "Rounded Callout",
		keywords: ["callout", "rounded", "bubble"],
		category: "callout",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Callout",
			content: "Tap to read more",
			fontSize: 11,
			fontFamily: "Arial",
			color: "#ffffff",
			background: {
				enabled: true,
				color: "#ec4899",
				cornerRadius: 16,
				paddingX: 18,
				paddingY: 10,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "callout-emoji",
		type: "callout-emoji",
		name: "Emoji Callout",
		keywords: ["callout", "emoji", "fun"],
		category: "callout",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Emoji Callout",
			content: "WOW!",
			fontSize: 20,
			fontFamily: "Arial",
			fontWeight: "bold",
			color: "#ffffff",
			background: {
				enabled: true,
				color: "#8b5cf6",
				cornerRadius: 12,
				paddingX: 20,
				paddingY: 12,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "quote",
		type: "quote",
		name: "Quote",
		keywords: ["quote", "citation"],
		category: "quote",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Quote",
			content: '"Inspiring words go here"',
			fontSize: 14,
			fontFamily: "Georgia",
			fontStyle: "italic",
			color: "#f5f5f5",
			background: {
				enabled: false,
				color: "#000000",
				cornerRadius: 0,
				paddingX: 0,
				paddingY: 0,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "quote-with-author",
		type: "quote-with-author",
		name: "Quote + Author",
		keywords: ["quote", "author", "attribution"],
		category: "quote",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Quote with Author",
			content: '"Quote" — Author',
			fontSize: 12,
			fontFamily: "Georgia",
			fontStyle: "italic",
			color: "#fbbf24",
			background: {
				enabled: false,
				color: "#000000",
				cornerRadius: 0,
				paddingX: 0,
				paddingY: 0,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "headline-stamp",
		type: "headline-stamp",
		name: "Headline Stamp",
		keywords: ["headline", "stamp", "bold"],
		category: "title",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Headline Stamp",
			content: "BREAKING",
			fontSize: 18,
			fontFamily: "Arial",
			fontWeight: "bold",
			color: "#ffffff",
			background: {
				enabled: true,
				color: "#dc2626",
				cornerRadius: 0,
				paddingX: 14,
				paddingY: 8,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "title-kinetic",
		type: "title-kinetic",
		name: "Kinetic Title",
		keywords: ["title", "kinetic", "motion", "bold"],
		category: "title",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Kinetic Title",
			content: "MAKE IT MOVE",
			fontSize: 26,
			fontFamily: "Impact",
			fontWeight: "bold",
			letterSpacing: 1.5,
			color: "#0f172a",
			background: {
				enabled: true,
				color: "#facc15",
				cornerRadius: 2,
				paddingX: 18,
				paddingY: 8,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "title-glass",
		type: "title-glass",
		name: "Glass Title",
		keywords: ["title", "glass", "clean", "modern"],
		category: "title",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Glass Title",
			content: "Glass Title",
			fontSize: 18,
			fontFamily: "Helvetica",
			fontWeight: "bold",
			color: "#ffffff",
			background: {
				enabled: true,
				color: "rgba(255,255,255,0.14)",
				cornerRadius: 18,
				paddingX: 24,
				paddingY: 12,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "subtitle-clean-pill",
		type: "subtitle-clean-pill",
		name: "Clean Caption Pill",
		keywords: ["subtitle", "caption", "pill", "clean"],
		category: "subtitle",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Clean Caption Pill",
			content: "Caption text",
			fontSize: 12,
			fontFamily: "Arial",
			color: "#111827",
			background: {
				enabled: true,
				color: "#f8fafc",
				cornerRadius: 18,
				paddingX: 18,
				paddingY: 8,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "lower-third-social",
		type: "lower-third-social",
		name: "Social Handle",
		keywords: ["lower", "third", "social", "handle"],
		category: "lower-third",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Social Handle",
			content: "@username",
			fontSize: 13,
			fontFamily: "Arial",
			fontWeight: "bold",
			color: "#ffffff",
			textAlign: "left",
			background: {
				enabled: true,
				color: "#2563eb",
				cornerRadius: 12,
				paddingX: 18,
				paddingY: 10,
				offsetX: 0,
				offsetY: 0,
			},
			transform: {
				...baseDefaults.transform,
				position: { x: -250, y: 230 },
			},
		}),
	},
	{
		id: "callout-alert",
		type: "callout-alert",
		name: "Alert Callout",
		keywords: ["callout", "alert", "notice", "warning"],
		category: "callout",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Alert Callout",
			content: "Important!",
			fontSize: 14,
			fontFamily: "Arial",
			fontWeight: "bold",
			color: "#ffffff",
			background: {
				enabled: true,
				color: "#ef4444",
				cornerRadius: 10,
				paddingX: 16,
				paddingY: 10,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "quote-editorial",
		type: "quote-editorial",
		name: "Editorial Quote",
		keywords: ["quote", "editorial", "magazine"],
		category: "quote",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Editorial Quote",
			content: "“A strong pull quote goes here.”",
			fontSize: 18,
			fontFamily: "Georgia",
			fontStyle: "italic",
			color: "#ffffff",
			lineHeight: 1.35,
			background: {
				enabled: true,
				color: "rgba(15,23,42,0.72)",
				cornerRadius: 8,
				paddingX: 26,
				paddingY: 16,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
];
