import type { TextElement } from "@/lib/timeline";
import { DEFAULT_NEW_ELEMENT_DURATION } from "@/lib/timeline/creation";

export type TextPresetCategory =
	| "basic"
	| "title"
	| "subtitle"
	| "lower-third"
	| "callout"
	| "quote"
	| "social"
	| "bold"
	| "handwritten"
	| "neon";

export interface TextPreset {
	id: string;
	type: string;
	name: string;
	keywords: string[];
	category: TextPresetCategory;
	build: () => Omit<TextElement, "id" | "startTime">;
}

const baseDefaults = {
	duration: DEFAULT_NEW_ELEMENT_DURATION,
	trimStart: 0,
	trimEnd: 0,
	textAlign: "center" as const,
	fontWeight: "normal" as const,
	fontStyle: "normal" as const,
	textDecoration: "none" as const,
	letterSpacing: 0,
	lineHeight: 1.2,
	hidden: false,
	transform: {
		scaleX: 1,
		scaleY: 1,
		position: { x: 0, y: 0 },
		rotate: 0,
	},
	opacity: 1,
};

/** No background box (the common case). */
const NO_BG = {
	enabled: false,
	color: "#000000",
	cornerRadius: 0,
	paddingX: 0,
	paddingY: 0,
	offsetX: 0,
	offsetY: 0,
};

/** A filled, padded background box (for pills, captions, stickers). */
function box(color: string, cornerRadius: number) {
	return {
		enabled: true,
		color,
		cornerRadius,
		paddingX: 16,
		paddingY: 8,
		offsetX: 0,
		offsetY: 0,
	};
}

export const textPresets: TextPreset[] = [
	{
		id: "title-bold",
		type: "title-bold",
		name: "Big Title",
		keywords: ["title", "headline", "bold"],
		category: "title",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Big Title",
			content: "Your Title",
			fontSize: 24,
			fontFamily: "Arial",
			fontWeight: "bold",
			color: "#ffffff",
			background: {
				enabled: false,
				color: "#000000",
				cornerRadius: 0,
				paddingX: 0,
				paddingY: 0,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "title-minimal",
		type: "title-minimal",
		name: "Minimal Title",
		keywords: ["title", "minimal", "clean"],
		category: "title",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Minimal Title",
			content: "Minimal",
			fontSize: 20,
			fontFamily: "Helvetica",
			fontWeight: "normal",
			color: "#ffffff",
			background: {
				enabled: false,
				color: "#000000",
				cornerRadius: 0,
				paddingX: 0,
				paddingY: 0,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "title-pop",
		type: "title-pop",
		name: "Pop Title",
		keywords: ["title", "pop", "colorful"],
		category: "title",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Pop Title",
			content: "POP!",
			fontSize: 28,
			fontFamily: "Impact",
			fontWeight: "bold",
			color: "#ffeb3b",
			background: {
				enabled: false,
				color: "#000000",
				cornerRadius: 0,
				paddingX: 0,
				paddingY: 0,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "subtitle-classic",
		type: "subtitle-classic",
		name: "Classic Subtitle",
		keywords: ["subtitle", "caption", "classic"],
		category: "subtitle",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Subtitle",
			content: "Subtitle text",
			fontSize: 12,
			fontFamily: "Arial",
			color: "#ffffff",
			background: {
				enabled: true,
				color: "#000000",
				cornerRadius: 4,
				paddingX: 16,
				paddingY: 8,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "subtitle-bold",
		type: "subtitle-bold",
		name: "Bold Subtitle",
		keywords: ["subtitle", "caption", "bold"],
		category: "subtitle",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Bold Subtitle",
			content: "Bold subtitle",
			fontSize: 14,
			fontFamily: "Arial",
			fontWeight: "bold",
			color: "#ffffff",
			background: {
				enabled: true,
				color: "#000000",
				cornerRadius: 6,
				paddingX: 18,
				paddingY: 10,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "lower-third",
		type: "lower-third",
		name: "Lower Third",
		keywords: ["lower", "third", "name", "title"],
		category: "lower-third",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Lower Third",
			content: "Name | Title",
			fontSize: 12,
			fontFamily: "Arial",
			color: "#ffffff",
			textAlign: "left",
			background: {
				enabled: true,
				color: "#000000",
				cornerRadius: 0,
				paddingX: 24,
				paddingY: 14,
				offsetX: -200,
				offsetY: 200,
			},
			transform: {
				...baseDefaults.transform,
				position: { x: 0, y: 250 },
			},
		}),
	},
	{
		id: "lower-third-accent",
		type: "lower-third-accent",
		name: "Lower Third Accent",
		keywords: ["lower", "third", "accent", "color"],
		category: "lower-third",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Lower Third Accent",
			content: "Speaker Name",
			fontSize: 14,
			fontFamily: "Arial",
			fontWeight: "bold",
			color: "#ffffff",
			textAlign: "left",
			background: {
				enabled: true,
				color: "#f97316",
				cornerRadius: 4,
				paddingX: 24,
				paddingY: 14,
				offsetX: 0,
				offsetY: 0,
			},
			transform: {
				...baseDefaults.transform,
				position: { x: 0, y: 250 },
			},
		}),
	},
	{
		id: "callout-rounded",
		type: "callout-rounded",
		name: "Rounded Callout",
		keywords: ["callout", "rounded", "bubble"],
		category: "callout",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Callout",
			content: "Tap to read more",
			fontSize: 11,
			fontFamily: "Arial",
			color: "#ffffff",
			background: {
				enabled: true,
				color: "#ec4899",
				cornerRadius: 16,
				paddingX: 18,
				paddingY: 10,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "callout-emoji",
		type: "callout-emoji",
		name: "Emoji Callout",
		keywords: ["callout", "emoji", "fun"],
		category: "callout",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Emoji Callout",
			content: "WOW!",
			fontSize: 20,
			fontFamily: "Arial",
			fontWeight: "bold",
			color: "#ffffff",
			background: {
				enabled: true,
				color: "#8b5cf6",
				cornerRadius: 12,
				paddingX: 20,
				paddingY: 12,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "quote",
		type: "quote",
		name: "Quote",
		keywords: ["quote", "citation"],
		category: "quote",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Quote",
			content: '"Inspiring words go here"',
			fontSize: 14,
			fontFamily: "Georgia",
			fontStyle: "italic",
			color: "#f5f5f5",
			background: {
				enabled: false,
				color: "#000000",
				cornerRadius: 0,
				paddingX: 0,
				paddingY: 0,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "quote-with-author",
		type: "quote-with-author",
		name: "Quote + Author",
		keywords: ["quote", "author", "attribution"],
		category: "quote",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Quote with Author",
			content: '"Quote" — Author',
			fontSize: 12,
			fontFamily: "Georgia",
			fontStyle: "italic",
			color: "#fbbf24",
			background: {
				enabled: false,
				color: "#000000",
				cornerRadius: 0,
				paddingX: 0,
				paddingY: 0,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "headline-stamp",
		type: "headline-stamp",
		name: "Headline Stamp",
		keywords: ["headline", "stamp", "bold"],
		category: "title",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Headline Stamp",
			content: "BREAKING",
			fontSize: 18,
			fontFamily: "Arial",
			fontWeight: "bold",
			color: "#ffffff",
			background: {
				enabled: true,
				color: "#dc2626",
				cornerRadius: 0,
				paddingX: 14,
				paddingY: 8,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "title-kinetic",
		type: "title-kinetic",
		name: "Kinetic Title",
		keywords: ["title", "kinetic", "motion", "bold"],
		category: "title",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Kinetic Title",
			content: "MAKE IT MOVE",
			fontSize: 26,
			fontFamily: "Impact",
			fontWeight: "bold",
			letterSpacing: 1.5,
			color: "#0f172a",
			background: {
				enabled: true,
				color: "#facc15",
				cornerRadius: 2,
				paddingX: 18,
				paddingY: 8,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "title-glass",
		type: "title-glass",
		name: "Glass Title",
		keywords: ["title", "glass", "clean", "modern"],
		category: "title",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Glass Title",
			content: "Glass Title",
			fontSize: 18,
			fontFamily: "Helvetica",
			fontWeight: "bold",
			color: "#ffffff",
			background: {
				enabled: true,
				color: "rgba(255,255,255,0.14)",
				cornerRadius: 18,
				paddingX: 24,
				paddingY: 12,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "subtitle-clean-pill",
		type: "subtitle-clean-pill",
		name: "Clean Caption Pill",
		keywords: ["subtitle", "caption", "pill", "clean"],
		category: "subtitle",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Clean Caption Pill",
			content: "Caption text",
			fontSize: 12,
			fontFamily: "Arial",
			color: "#111827",
			background: {
				enabled: true,
				color: "#f8fafc",
				cornerRadius: 18,
				paddingX: 18,
				paddingY: 8,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "lower-third-social",
		type: "lower-third-social",
		name: "Social Handle",
		keywords: ["lower", "third", "social", "handle"],
		category: "lower-third",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Social Handle",
			content: "@username",
			fontSize: 13,
			fontFamily: "Arial",
			fontWeight: "bold",
			color: "#ffffff",
			textAlign: "left",
			background: {
				enabled: true,
				color: "#2563eb",
				cornerRadius: 12,
				paddingX: 18,
				paddingY: 10,
				offsetX: 0,
				offsetY: 0,
			},
			transform: {
				...baseDefaults.transform,
				position: { x: -250, y: 230 },
			},
		}),
	},
	{
		id: "callout-alert",
		type: "callout-alert",
		name: "Alert Callout",
		keywords: ["callout", "alert", "notice", "warning"],
		category: "callout",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Alert Callout",
			content: "Important!",
			fontSize: 14,
			fontFamily: "Arial",
			fontWeight: "bold",
			color: "#ffffff",
			background: {
				enabled: true,
				color: "#ef4444",
				cornerRadius: 10,
				paddingX: 16,
				paddingY: 10,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},
	{
		id: "quote-editorial",
		type: "quote-editorial",
		name: "Editorial Quote",
		keywords: ["quote", "editorial", "magazine"],
		category: "quote",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Editorial Quote",
			content: "“A strong pull quote goes here.”",
			fontSize: 18,
			fontFamily: "Georgia",
			fontStyle: "italic",
			color: "#ffffff",
			lineHeight: 1.35,
			background: {
				enabled: true,
				color: "rgba(15,23,42,0.72)",
				cornerRadius: 8,
				paddingX: 26,
				paddingY: 16,
				offsetX: 0,
				offsetY: 0,
			},
		}),
	},

	/* --------------------------------- basic --------------------------------- */
	{
		id: "basic-plain",
		type: "basic-plain",
		name: "Plain",
		keywords: ["plain", "basic", "simple", "body"],
		category: "basic",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Plain",
			content: "Text",
			fontSize: 18,
			fontFamily: "Helvetica",
			fontWeight: "normal",
			color: "#ffffff",
			background: NO_BG,
		}),
	},
	{
		id: "basic-caption",
		type: "basic-caption",
		name: "Caption",
		keywords: ["caption", "basic", "small", "label"],
		category: "basic",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Caption",
			content: "Caption text",
			fontSize: 13,
			fontFamily: "Arial",
			fontWeight: "normal",
			color: "#e5e7eb",
			background: NO_BG,
		}),
	},
	{
		id: "basic-highlight",
		type: "basic-highlight",
		name: "Highlight",
		keywords: ["highlight", "marker", "bar", "basic"],
		category: "basic",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Highlight",
			content: "Highlight",
			fontSize: 18,
			fontFamily: "Arial",
			fontWeight: "bold",
			color: "#0a0a0a",
			background: box("#facc15", 2),
		}),
	},

	/* --------------------------------- social -------------------------------- */
	{
		id: "social-caption",
		type: "social-caption",
		name: "Auto Caption",
		keywords: ["tiktok", "caption", "social", "subtitle"],
		category: "social",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Auto Caption",
			content: "auto caption",
			fontSize: 18,
			fontFamily: "Arial",
			fontWeight: "bold",
			color: "#ffffff",
			background: box("rgba(0,0,0,0.85)", 6),
		}),
	},
	{
		id: "social-hashtag",
		type: "social-hashtag",
		name: "Hashtag",
		keywords: ["hashtag", "tag", "social", "pill"],
		category: "social",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Hashtag",
			content: "#trending",
			fontSize: 16,
			fontFamily: "Arial",
			fontWeight: "bold",
			color: "#22d3ee",
			background: box("rgba(8,47,73,0.9)", 999),
		}),
	},
	{
		id: "social-subscribe",
		type: "social-subscribe",
		name: "Subscribe",
		keywords: ["subscribe", "cta", "social", "youtube"],
		category: "social",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Subscribe",
			content: "SUBSCRIBE",
			fontSize: 18,
			fontFamily: "Arial",
			fontWeight: "bold",
			color: "#ffffff",
			background: box("#dc2626", 6),
		}),
	},
	{
		id: "social-meme",
		type: "social-meme",
		name: "Meme",
		keywords: ["meme", "impact", "social", "caption"],
		category: "social",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Meme",
			content: "TOP TEXT",
			fontSize: 26,
			fontFamily: "Impact",
			fontWeight: "bold",
			color: "#ffffff",
			letterSpacing: 1,
			background: NO_BG,
		}),
	},

	/* ---------------------------------- bold --------------------------------- */
	{
		id: "bold-impact",
		type: "bold-impact",
		name: "Impact",
		keywords: ["impact", "bold", "heavy", "all-caps"],
		category: "bold",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Impact",
			content: "IMPACT",
			fontSize: 30,
			fontFamily: "Impact",
			fontWeight: "bold",
			color: "#ffffff",
			letterSpacing: 2,
			background: NO_BG,
		}),
	},
	{
		id: "bold-sticker",
		type: "bold-sticker",
		name: "Sticker",
		keywords: ["sticker", "bold", "rounded", "badge"],
		category: "bold",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Sticker",
			content: "Sticker",
			fontSize: 20,
			fontFamily: "Arial",
			fontWeight: "bold",
			color: "#0a0a0a",
			background: box("#ffffff", 14),
		}),
	},

	/* ------------------------------ handwritten ------------------------------ */
	{
		id: "handwritten-script",
		type: "handwritten-script",
		name: "Script",
		keywords: ["script", "cursive", "handwritten", "signature"],
		category: "handwritten",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Script",
			content: "Beautiful",
			fontSize: 28,
			fontFamily: "Brush Script MT",
			fontStyle: "italic",
			color: "#ffffff",
			background: NO_BG,
		}),
	},
	{
		id: "handwritten-marker",
		type: "handwritten-marker",
		name: "Marker",
		keywords: ["marker", "felt", "handwritten", "casual"],
		category: "handwritten",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Marker",
			content: "Marker",
			fontSize: 22,
			fontFamily: "Comic Sans MS",
			fontWeight: "bold",
			color: "#fde68a",
			background: NO_BG,
		}),
	},

	/* ---------------------------------- neon --------------------------------- */
	{
		id: "neon-pink",
		type: "neon-pink",
		name: "Neon Pink",
		keywords: ["neon", "pink", "glow", "night"],
		category: "neon",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Neon Pink",
			content: "NEON",
			fontSize: 26,
			fontFamily: "Arial",
			fontWeight: "bold",
			color: "#ff4dd2",
			letterSpacing: 2,
			background: NO_BG,
		}),
	},
	{
		id: "neon-cyan",
		type: "neon-cyan",
		name: "Neon Cyan",
		keywords: ["neon", "cyan", "glow", "electric"],
		category: "neon",
		build: () => ({
			...baseDefaults,
			type: "text",
			name: "Neon Cyan",
			content: "GLOW",
			fontSize: 26,
			fontFamily: "Arial",
			fontWeight: "bold",
			color: "#34fff0",
			letterSpacing: 2,
			background: NO_BG,
		}),
	},
];

/** Compact authoring helper: one real, named preset (no auto-numbers). */
function tp(
	id: string,
	name: string,
	category: TextPresetCategory,
	content: string,
	style: Partial<Omit<TextElement, "id" | "startTime" | "type" | "name">>,
	keywords: string[] = [],
): TextPreset {
	return {
		id,
		type: id,
		name,
		keywords: [category, ...keywords],
		category,
		build: () => ({
			...baseDefaults,
			type: "text",
			name,
			content,
			fontSize: 18,
			fontFamily: "Inter",
			color: "#ffffff",
			background: NO_BG,
			...style,
		}),
	};
}

// Distinct, hand-named presets (replaced the old "Style N" / "Premium N" filler).
// Each differs by font, weight, size, color, spacing, or background — no clones.
textPresets.push(
	tp("title-cinematic", "Cinematic", "title", "CINEMATIC", {
		fontFamily: "Oswald", fontSize: 30, fontWeight: "bold", letterSpacing: 6,
	}, ["wide", "film"]),
	tp("title-serif-hero", "Serif Hero", "title", "Headline", {
		fontFamily: "Playfair Display", fontSize: 30, fontWeight: "bold", letterSpacing: -1,
	}, ["serif", "elegant"]),
	tp("title-outline-pop", "Sunburst", "title", "BIG NEWS", {
		fontFamily: "Impact", fontSize: 28, fontWeight: "bold", color: "#fcd34d", letterSpacing: 2,
	}, ["yellow", "loud"]),
	tp("title-gradient-cool", "Cool Glass", "title", "Smooth", {
		fontFamily: "Poppins", fontSize: 26, fontWeight: "bold", color: "#67e8f9",
	}, ["cyan", "modern"]),
	tp("subtitle-news-bar", "News Bar", "subtitle", "Breaking story", {
		fontFamily: "Roboto", fontSize: 13, color: "#ffffff",
		background: box("#be123c", 2), letterSpacing: 1,
	}, ["news", "bar", "red"]),
	tp("subtitle-soft-pill", "Soft Pill", "subtitle", "Now playing", {
		fontFamily: "Inter", fontSize: 13, color: "#0f172a",
		background: box("#e2e8f0", 999),
	}, ["pill", "light"]),
	tp("subtitle-mono-tag", "Mono Tag", "subtitle", "v1.0 · build", {
		fontFamily: "monospace", fontSize: 12, color: "#a7f3d0",
		background: box("#052e16", 4), letterSpacing: 1,
	}, ["mono", "code"]),
	tp("lower-third-anchor", "Anchor", "lower-third", "Jane Doe", {
		fontFamily: "Montserrat", fontSize: 16, fontWeight: "bold", color: "#ffffff",
		background: box("#1d4ed8", 6), textAlign: "left",
	}, ["name", "host"]),
	tp("lower-third-minimal", "Hairline", "lower-third", "Reporter · Live", {
		fontFamily: "Raleway", fontSize: 13, color: "#f8fafc", textAlign: "left", letterSpacing: 2,
	}, ["clean", "thin"]),
	tp("callout-warning", "Warning", "callout", "⚠ Heads up", {
		fontFamily: "Inter", fontSize: 15, fontWeight: "bold", color: "#451a03",
		background: box("#f59e0b", 8),
	}, ["alert", "amber"]),
	tp("callout-success", "Success", "callout", "✓ Done", {
		fontFamily: "Inter", fontSize: 15, fontWeight: "bold", color: "#052e16",
		background: box("#22c55e", 999),
	}, ["green", "ok"]),
	tp("callout-link", "Swipe Link", "callout", "Swipe up →", {
		fontFamily: "Poppins", fontSize: 14, color: "#ffffff",
		background: box("#7c3aed", 999),
	}, ["cta", "purple"]),
	tp("quote-bold-mark", "Bold Quote", "quote", "“Stay hungry.”", {
		fontFamily: "Playfair Display", fontSize: 22, fontStyle: "italic", color: "#fafafa",
	}, ["italic", "serif"]),
	tp("quote-card", "Quote Card", "quote", "“Less, but better.”", {
		fontFamily: "Georgia", fontSize: 18, fontStyle: "italic", color: "#1c1917",
		background: box("#fef3c7", 10),
	}, ["card", "warm"]),
	tp("social-handle", "Handle", "social", "@username", {
		fontFamily: "Inter", fontSize: 15, fontWeight: "bold", color: "#ffffff",
		background: box("#0ea5e9", 999),
	}, ["tag", "blue"]),
	tp("social-hot-take", "Hot Take", "social", "unpopular opinion:", {
		fontFamily: "Roboto", fontSize: 16, color: "#fdf2f8",
		background: box("#db2777", 6),
	}, ["pink", "meme"]),
	tp("social-caption-clean", "Clean Caption", "social", "watch till the end", {
		fontFamily: "Inter", fontSize: 14, color: "#ffffff", letterSpacing: 1,
	}, ["caption", "white"]),
	tp("bold-stamp", "Stamp", "bold", "SOLD OUT", {
		fontFamily: "Impact", fontSize: 26, fontWeight: "bold", color: "#ffffff",
		background: box("#dc2626", 4), letterSpacing: 3,
	}, ["red", "stamp"]),
	tp("bold-marquee", "Marquee", "bold", "ON SALE NOW", {
		fontFamily: "Oswald", fontSize: 22, fontWeight: "bold", color: "#fde047", letterSpacing: 4,
	}, ["sale", "yellow"]),
	tp("handwritten-note", "Note", "handwritten", "thank you!", {
		fontFamily: "Comic Sans MS", fontSize: 22, color: "#f472b6",
	}, ["script", "casual"]),
	tp("handwritten-signature", "Signature", "handwritten", "— from the team", {
		fontFamily: "Brush Script MT", fontSize: 24, fontStyle: "italic", color: "#fafafa",
	}, ["sign", "cursive"]),
	tp("neon-electric", "Electric", "neon", "GLOW", {
		fontFamily: "Oswald", fontSize: 28, fontWeight: "bold", color: "#22d3ee", letterSpacing: 4,
	}, ["cyan", "glow"]),
	tp("neon-magenta", "Magenta", "neon", "VIBE", {
		fontFamily: "Montserrat", fontSize: 28, fontWeight: "bold", color: "#f0abfc", letterSpacing: 4,
	}, ["pink", "glow"]),
	tp("basic-watermark", "Watermark", "basic", "© your brand", {
		fontFamily: "Inter", fontSize: 12, color: "#94a3b8", letterSpacing: 1,
	}, ["credit", "subtle"]),
);
