// Effects — 180 preset definitions (15 per category across 12 categories).
// Shape per user spec:
//   { type, name, category, description, params, previewCss?, renderPreview? }

import type {
	EffectPresetCategory,
	EffectPresetDefinition,
	EffectPresetParams,
} from "./types";

const ef = (
	type: string,
	name: string,
	category: EffectPresetCategory,
	description: string,
	params: EffectPresetParams,
	previewCss?: string,
	renderPreview?: EffectPresetDefinition["renderPreview"],
): EffectPresetDefinition => ({
	type,
	name,
	category,
	description,
	params,
	previewCss,
	renderPreview,
});

export const effects: EffectPresetDefinition[] = [
	// ── Blur (15)
	ef(
		"fx-blur-soft",
		"Soft Blur",
		"Blur",
		"Subtle gaussian blur",
		{ radius: 4 },
		"filter:blur(4px);",
	),
	ef(
		"fx-blur-strong",
		"Strong Blur",
		"Blur",
		"Heavy gaussian blur",
		{ radius: 20 },
		"filter:blur(20px);",
	),
	ef(
		"fx-blur-radial",
		"Radial Blur",
		"Blur",
		"Radial zoom blur from center",
		{ radius: 12 },
		"filter:blur(12px);",
	),
	ef(
		"fx-blur-motion",
		"Motion Blur",
		"Blur",
		"Directional motion blur",
		{ angle: 0, distance: 10 },
		"filter:blur(10px);",
	),
	ef(
		"fx-blur-tilt",
		"Tilt Blur",
		"Blur",
		"Tilt-shift miniature look",
		{ radius: 8, y: 50 },
		"filter:blur(8px);",
	),
	ef(
		"fx-blur-gaussian",
		"Gaussian Blur",
		"Blur",
		"Pure gaussian blur",
		{ radius: 6 },
		"filter:blur(6px);",
	),
	ef(
		"fx-blur-box",
		"Box Blur",
		"Blur",
		"Box-style blur",
		{ radius: 5 },
		"filter:blur(5px);",
	),
	ef(
		"fx-blur-zoom",
		"Zoom Blur",
		"Blur",
		"Radial zoom-blur",
		{ strength: 15 },
		"filter:blur(15px);",
	),
	ef(
		"fx-blur-bokeh",
		"Bokeh Blur",
		"Blur",
		"Out-of-focus bokeh blur",
		{ radius: 10 },
		"filter:blur(10px);",
	),
	ef(
		"fx-blur-frosted",
		"Frosted Glass",
		"Blur",
		"Frosted glass blur",
		{ radius: 14 },
		"filter:blur(14px);",
	),
	ef(
		"fx-blur-dream",
		"Dream Blur",
		"Blur",
		"Soft dream haze blur",
		{ radius: 7 },
		"filter:blur(7px);",
	),
	ef(
		"fx-blur-foreground",
		"FG Blur",
		"Blur",
		"Foreground blur for depth",
		{ radius: 9 },
		"filter:blur(9px);",
	),
	ef(
		"fx-blur-tiny",
		"Tiny Blur",
		"Blur",
		"Very mild blur",
		{ radius: 2 },
		"filter:blur(2px);",
	),
	ef(
		"fx-blur-vignette-blur",
		"Vignette Blur",
		"Blur",
		"Blur stronger at edges",
		{ radius: 8 },
		"filter:blur(8px);",
	),
	ef(
		"fx-blur-anamorphic",
		"Anamorphic Blur",
		"Blur",
		"Horizontal-only blur",
		{ radius: 10, direction: "horizontal" },
		"filter:blur(10px);",
	),

	// ── Glow (15)
	ef(
		"fx-glow-soft",
		"Soft Glow",
		"Glow",
		"Subtle outer glow",
		{ intensity: 0.5, color: "#ffffff" },
		"filter:drop-shadow(0 0 8px #fff);",
	),
	ef(
		"fx-glow-neon",
		"Neon Glow",
		"Glow",
		"Hot neon glow",
		{ intensity: 1.5, color: "#ff00aa" },
		"filter:drop-shadow(0 0 20px #ff00aa);",
	),
	ef(
		"fx-glow-outer",
		"Outer Glow",
		"Glow",
		"Outer drop-shadow glow",
		{ intensity: 0.8, color: "#00e5ff" },
		"filter:drop-shadow(0 0 12px #00e5ff);",
	),
	ef(
		"fx-glow-inner",
		"Inner Glow",
		"Glow",
		"Inset inner glow",
		{ intensity: 0.6, color: "#ffffff" },
		"box-shadow:inset 0 0 20px #fff;",
	),
	ef(
		"fx-glow-warm",
		"Warm Glow",
		"Glow",
		"Warm golden glow",
		{ intensity: 1.0, color: "#fcd34d" },
		"filter:drop-shadow(0 0 14px #fcd34d);",
	),
	ef(
		"fx-glow-cool",
		"Cool Glow",
		"Glow",
		"Cool cyan glow",
		{ intensity: 1.0, color: "#22d3ee" },
		"filter:drop-shadow(0 0 14px #22d3ee);",
	),
	ef(
		"fx-glow-fiery",
		"Fiery Glow",
		"Glow",
		"Hot red-orange glow",
		{ intensity: 1.2, color: "#ff5722" },
		"filter:drop-shadow(0 0 16px #ff5722);",
	),
	ef(
		"fx-glow-electric",
		"Electric Glow",
		"Glow",
		"Electric blue glow",
		{ intensity: 1.4, color: "#3b82f6" },
		"filter:drop-shadow(0 0 18px #3b82f6);",
	),
	ef(
		"fx-glow-magic",
		"Magic Glow",
		"Glow",
		"Magical purple glow",
		{ intensity: 1.1, color: "#a855f7" },
		"filter:drop-shadow(0 0 16px #a855f7);",
	),
	ef(
		"fx-glow-dream",
		"Dreamy Bloom",
		"Glow",
		"Soft dreamy bloom",
		{ intensity: 0.7, color: "#fce7f3" },
		"filter:drop-shadow(0 0 10px #fce7f3);",
	),
	ef(
		"fx-glow-strong",
		"Strong Glow",
		"Glow",
		"High-intensity glow",
		{ intensity: 2.0, color: "#ffffff" },
		"filter:drop-shadow(0 0 24px #fff);",
	),
	ef(
		"fx-glow-mist",
		"Mist Glow",
		"Glow",
		"Misty diffuse glow",
		{ intensity: 0.4, color: "#e0f2fe" },
		"filter:drop-shadow(0 0 6px #e0f2fe);",
	),
	ef(
		"fx-glow-toxic",
		"Toxic Glow",
		"Glow",
		"Toxic green glow",
		{ intensity: 1.0, color: "#84cc16" },
		"filter:drop-shadow(0 0 12px #84cc16);",
	),
	ef(
		"fx-glow-amber",
		"Amber Glow",
		"Glow",
		"Amber honey glow",
		{ intensity: 0.9, color: "#fbbf24" },
		"filter:drop-shadow(0 0 10px #fbbf24);",
	),
	ef(
		"fx-glow-shadow",
		"Shadow Glow",
		"Glow",
		"Drop-shadow style glow",
		{ intensity: 0.8, color: "#000000" },
		"filter:drop-shadow(0 0 10px #000);",
	),

	// ── Distortion (15)
	ef(
		"fx-distort-wave",
		"Wave",
		"Distortion",
		"Horizontal wave warp",
		{ amplitude: 20, frequency: 4 },
		"filter:url(#wave);",
	),
	ef(
		"fx-distort-ripple",
		"Ripple",
		"Distortion",
		"Water ripple distortion",
		{ amplitude: 15 },
		"filter:url(#ripple);",
	),
	ef(
		"fx-distort-swirl",
		"Swirl",
		"Distortion",
		"Circular swirl warp",
		{ angle: 90 },
		"filter:url(#swirl);",
	),
	ef(
		"fx-distort-bulge",
		"Bulge",
		"Distortion",
		"Center bulge distortion",
		{ radius: 100 },
		"filter:url(#bulge);",
	),
	ef(
		"fx-distort-pinch",
		"Pinch",
		"Distortion",
		"Center pinch distortion",
		{ radius: 100 },
		"filter:url(#pinch);",
	),
	ef(
		"fx-distort-twist",
		"Twist",
		"Distortion",
		"Spiral twist warp",
		{ angle: 180 },
		"filter:url(#twist);",
	),
	ef(
		"fx-distort-fisheye",
		"Fisheye",
		"Distortion",
		"Fisheye lens warp",
		{ amount: 0.5 },
		"filter:url(#fisheye);",
	),
	ef(
		"fx-distort-stretch",
		"Stretch",
		"Distortion",
		"Vertical stretch warp",
		{ amount: 1.2 },
		"filter:url(#stretch);",
	),
	ef(
		"fx-distort-glitch-displace",
		"Glitch Displace",
		"Distortion",
		"Glitch displacement",
		{ amount: 10 },
		"filter:url(#glitch);",
	),
	ef(
		"fx-distort-mirror-h",
		"Mirror H",
		"Distortion",
		"Mirror horizontally",
		{ axis: "horizontal" },
		"transform:scaleX(-1);",
	),
	ef(
		"fx-distort-mirror-v",
		"Mirror V",
		"Distortion",
		"Mirror vertically",
		{ axis: "vertical" },
		"transform:scaleY(-1);",
	),
	ef(
		"fx-distort-bend",
		"Bend",
		"Distortion",
		"Subtle bend warp",
		{ amount: 0.3 },
		"filter:url(#bend);",
	),
	ef(
		"fx-distort-flip-h",
		"Flip H",
		"Distortion",
		"Flip horizontally",
		{ axis: "horizontal" },
		"transform:scaleX(-1);",
	),
	ef(
		"fx-distort-flip-v",
		"Flip V",
		"Distortion",
		"Flip vertically",
		{ axis: "vertical" },
		"transform:scaleY(-1);",
	),
	ef(
		"fx-distort-turbulence",
		"Turbulence",
		"Distortion",
		"SVG turbulence warp",
		{ frequency: 0.02 },
		"filter:url(#turb);",
	),

	// ── Stylize (15)
	ef(
		"fx-style-posterize",
		"Posterize",
		"Stylize",
		"Reduce to flat colors",
		{ levels: 4 },
		"filter:contrast(2) saturate(0);",
	),
	ef(
		"fx-style-edge-detect",
		"Edge Detect",
		"Stylize",
		"Edge detection outline",
		{ threshold: 0.5 },
		"filter:url(#edge);",
	),
	ef(
		"fx-style-halftone",
		"Halftone",
		"Stylize",
		"Halftone dot pattern",
		{ size: 8 },
		"background-image:radial-gradient(#000 30%, transparent 35%); background-size:8px 8px;",
	),
	ef(
		"fx-style-mirror",
		"Mirror",
		"Stylize",
		"Mirror tiles",
		{ tiles: 4 },
		"transform:scaleX(-1);",
	),
	ef(
		"fx-style-ascii",
		"ASCII",
		"Stylize",
		"ASCII art conversion",
		{ size: 8 },
		"filter:contrast(2);",
	),
	ef(
		"fx-style-comic",
		"Comic",
		"Stylize",
		"Comic book stylization",
		{ edge: 0.5 },
		"filter:contrast(2) saturate(1.5);",
	),
	ef(
		"fx-style-thermal",
		"Thermal",
		"Stylize",
		"Thermal camera look",
		{ heat: 0.7 },
		"filter:hue-rotate(180deg) saturate(3);",
	),
	ef(
		"fx-style-thermal-warm",
		"Thermal Warm",
		"Stylize",
		"Warm thermal look",
		{ heat: 0.8 },
		"filter:hue-rotate(-30deg) saturate(3);",
	),
	ef(
		"fx-style-mosaic",
		"Mosaic",
		"Stylize",
		"Mosaic tile effect",
		{ tileSize: 16 },
		"filter:contrast(2);",
	),
	ef(
		"fx-style-emboss",
		"Emboss",
		"Stylize",
		"Embossed surface",
		{ strength: 0.8 },
		"filter:contrast(2) brightness(1.2);",
	),
	ef(
		"fx-style-pixelate",
		"Pixelate",
		"Stylize",
		"Pixelated block look",
		{ size: 8 },
		"filter:contrast(2);",
	),
	ef(
		"fx-style-duotone",
		"Duotone",
		"Stylize",
		"Two-tone duotone",
		{ colorA: "#3b82f6", colorB: "#f472b6" },
		"filter:grayscale(1);",
	),
	ef(
		"fx-style-stroke",
		"Stroke",
		"Stylize",
		"Outline stroke effect",
		{ width: 2, color: "#000000" },
		"filter:contrast(2);",
	),
	ef(
		"fx-style-neon-boost",
		"Neon Boost",
		"Stylize",
		"Boosted neon look",
		{ amount: 1.5 },
		"filter:saturate(2) contrast(1.3);",
	),
	ef(
		"fx-style-x-ray",
		"X-Ray",
		"Stylize",
		"X-ray inverted look",
		{ amount: 1 },
		"filter:invert(1) hue-rotate(180deg);",
	),

	// ── Particles (15)
	ef(
		"fx-particles-snow",
		"Snow",
		"Particles",
		"Falling snow particles",
		{ count: 80, speed: 5 },
		"background-color:transparent;",
	),
	ef(
		"fx-particles-rain",
		"Rain",
		"Particles",
		"Falling rain particles",
		{ count: 100, speed: 8 },
		"background-color:transparent;",
	),
	ef(
		"fx-particles-sparkle",
		"Sparkle",
		"Particles",
		"Random sparkles",
		{ count: 60, speed: 3 },
		"background-color:transparent;",
	),
	ef(
		"fx-particles-fireflies",
		"Fireflies",
		"Particles",
		"Floating firefly glows",
		{ count: 40, speed: 2 },
		"background-color:transparent;",
	),
	ef(
		"fx-particles-stars",
		"Stars",
		"Particles",
		"Twinkling star field",
		{ count: 120, speed: 1 },
		"background-color:transparent;",
	),
	ef(
		"fx-particles-bubbles",
		"Bubbles",
		"Particles",
		"Rising bubbles",
		{ count: 30, speed: 4 },
		"background-color:transparent;",
	),
	ef(
		"fx-particles-confetti",
		"Confetti",
		"Particles",
		"Falling confetti",
		{ count: 100, speed: 6 },
		"background-color:transparent;",
	),
	ef(
		"fx-particles-leaves",
		"Leaves",
		"Particles",
		"Falling leaves",
		{ count: 40, speed: 5 },
		"background-color:transparent;",
	),
	ef(
		"fx-particles-ash",
		"Ash",
		"Particles",
		"Floating ash",
		{ count: 80, speed: 3 },
		"background-color:transparent;",
	),
	ef(
		"fx-particles-dust",
		"Dust",
		"Particles",
		"Floating dust motes",
		{ count: 100, speed: 1 },
		"background-color:transparent;",
	),
	ef(
		"fx-particles-pollen",
		"Pollen",
		"Particles",
		"Floating pollen",
		{ count: 80, speed: 2 },
		"background-color:transparent;",
	),
	ef(
		"fx-particles-petals",
		"Petals",
		"Particles",
		"Falling flower petals",
		{ count: 60, speed: 4 },
		"background-color:transparent;",
	),
	ef(
		"fx-particles-embers",
		"Embers",
		"Particles",
		"Rising fire embers",
		{ count: 50, speed: 5 },
		"background-color:transparent;",
	),
	ef(
		"fx-particles-fog-particles",
		"Fog Particles",
		"Particles",
		"Drifting fog particles",
		{ count: 60, speed: 1 },
		"background-color:transparent;",
	),
	ef(
		"fx-particles-glitter",
		"Glitter",
		"Particles",
		"Sparkling glitter",
		{ count: 150, speed: 4 },
		"background-color:transparent;",
	),

	// ── Texture (15)
	ef(
		"fx-tex-grain",
		"Grain",
		"Texture",
		"Film grain texture",
		{ amount: 0.5 },
		"filter:contrast(1.1);",
	),
	ef(
		"fx-tex-noise",
		"Noise",
		"Texture",
		"Random noise overlay",
		{ amount: 0.3 },
		"filter:contrast(1.5);",
	),
	ef(
		"fx-tex-paper",
		"Paper",
		"Texture",
		"Paper grain texture",
		{ amount: 0.4 },
		"filter:contrast(1.1) brightness(1.05);",
	),
	ef(
		"fx-tex-concrete",
		"Concrete",
		"Texture",
		"Concrete texture",
		{ amount: 0.6 },
		"filter:contrast(1.2);",
	),
	ef(
		"fx-tex-grid",
		"Grid",
		"Texture",
		"Grid line texture",
		{ size: 20 },
		"background-image:linear-gradient(#000 1px, transparent 1px), linear-gradient(90deg, #000 1px, transparent 1px); background-size:20px 20px;",
	),
	ef(
		"fx-tex-dots",
		"Dots",
		"Texture",
		"Polka dot texture",
		{ size: 16 },
		"background-image:radial-gradient(#000 30%, transparent 35%); background-size:16px 16px;",
	),
	ef(
		"fx-tex-stripes",
		"Stripes",
		"Texture",
		"Diagonal stripe texture",
		{ width: 4 },
		"background-image:repeating-linear-gradient(45deg, #000 0 2px, transparent 2px 8px);",
	),
	ef(
		"fx-tex-canvas",
		"Canvas",
		"Texture",
		"Canvas weave texture",
		{ amount: 0.4 },
		"filter:contrast(1.1);",
	),
	ef(
		"fx-tex-bricks",
		"Bricks",
		"Texture",
		"Brick wall texture",
		{ rows: 8 },
		"background-image:repeating-linear-gradient(0deg, #000 0 2px, transparent 2px 30px), repeating-linear-gradient(90deg, #000 0 2px, transparent 2px 60px);",
	),
	ef(
		"fx-tex-wood",
		"Wood",
		"Texture",
		"Wood grain texture",
		{ amount: 0.5 },
		"filter:contrast(1.2) saturate(.8);",
	),
	ef(
		"fx-tex-marble",
		"Marble",
		"Texture",
		"Marble texture",
		{ amount: 0.4 },
		"filter:contrast(1.1);",
	),
	ef(
		"fx-tex-fabric",
		"Fabric",
		"Texture",
		"Fabric weave texture",
		{ amount: 0.4 },
		"filter:contrast(1.1);",
	),
	ef(
		"fx-tex-glass",
		"Glass",
		"Texture",
		"Frosted glass texture",
		{ amount: 0.5 },
		"filter:contrast(1.2) brightness(1.1);",
	),
	ef(
		"fx-tex-metal",
		"Metal",
		"Texture",
		"Brushed metal texture",
		{ amount: 0.5 },
		"filter:contrast(1.3) saturate(.5);",
	),
	ef(
		"fx-tex-cracked",
		"Cracked",
		"Texture",
		"Cracked surface texture",
		{ amount: 0.6 },
		"filter:contrast(1.5);",
	),

	// ── Light (15)
	ef(
		"fx-light-flare",
		"Lens Flare",
		"Light",
		"Lens flare overlay",
		{ intensity: 0.7, color: "#ffffff" },
		"filter:brightness(1.3);",
	),
	ef(
		"fx-light-anamorphic",
		"Anamorphic",
		"Light",
		"Anamorphic streak flare",
		{ intensity: 0.8, color: "#6dd6ff" },
		"filter:brightness(1.2);",
	),
	ef(
		"fx-light-leak",
		"Light Leak",
		"Light",
		"Light leak overlay",
		{ intensity: 0.5, color: "#ff5e3a" },
		"filter:brightness(1.2) saturate(1.3);",
	),
	ef(
		"fx-light-bloom",
		"Bloom",
		"Light",
		"Bloom glow",
		{ intensity: 0.6, threshold: 0.7 },
		"filter:brightness(1.3);",
	),
	ef(
		"fx-light-sunburst",
		"Sunburst",
		"Light",
		"Radial sunburst",
		{ intensity: 0.8 },
		"filter:brightness(1.4);",
	),
	ef(
		"fx-light-ray",
		"Light Ray",
		"Light",
		"Volumetric light ray",
		{ angle: 45 },
		"filter:brightness(1.2);",
	),
	ef(
		"fx-light-spotlight",
		"Spotlight",
		"Light",
		"Spotlight beam",
		{ intensity: 0.7 },
		"filter:brightness(1.2);",
	),
	ef(
		"fx-light-vignette",
		"Vignette",
		"Light",
		"Edge darkening",
		{ amount: 0.6 },
		"box-shadow:inset 0 0 80px rgba(0,0,0,.6);",
	),
	ef(
		"fx-light-square-vignette",
		"Square Vignette",
		"Light",
		"Hard rectangular vignette",
		{ amount: 0.7 },
		"box-shadow:inset 0 0 80px rgba(0,0,0,.7);",
	),
	ef(
		"fx-light-spot",
		"Spot",
		"Light",
		"Single light spot",
		{ intensity: 0.5 },
		"filter:brightness(1.1);",
	),
	ef(
		"fx-light-fill",
		"Fill Light",
		"Light",
		"Fill light brightening",
		{ intensity: 0.3 },
		"filter:brightness(1.1);",
	),
	ef(
		"fx-light-rim",
		"Rim Light",
		"Light",
		"Rim light glow",
		{ intensity: 0.6 },
		"filter:brightness(1.2);",
	),
	ef(
		"fx-light-caustic",
		"Caustic",
		"Light",
		"Caustic light patterns",
		{ intensity: 0.5 },
		"filter:brightness(1.1);",
	),
	ef(
		"fx-light-strobe-light",
		"Strobe",
		"Light",
		"Strobe pulse",
		{ rate: 4 },
		"filter:brightness(1.3);",
	),
	ef(
		"fx-light-blink",
		"Blink",
		"Light",
		"On-off blink",
		{ rate: 2 },
		"filter:brightness(1.2);",
	),

	// ── Retro (15)
	ef(
		"fx-retro-vhs",
		"VHS",
		"Retro",
		"VHS tape look",
		{ amount: 0.7 },
		"filter:saturate(1.5) contrast(1.1);",
	),
	ef(
		"fx-retro-scanlines",
		"Scanlines",
		"Retro",
		"CRT scanlines",
		{ intensity: 0.4 },
		"background-image:repeating-linear-gradient(0deg, transparent 0 2px, rgba(0,0,0,.3) 2px 3px);",
	),
	ef(
		"fx-retro-crt",
		"CRT",
		"Retro",
		"Old CRT monitor",
		{ intensity: 0.6 },
		"filter:contrast(1.3);",
	),
	ef(
		"fx-retro-super8",
		"Super 8",
		"Retro",
		"Super 8 film look",
		{ amount: 0.7 },
		"filter:saturate(1.3) contrast(1.2);",
	),
	ef(
		"fx-retro-16mm",
		"16mm",
		"Retro",
		"16mm film look",
		{ amount: 0.6 },
		"filter:saturate(1.2) contrast(1.1);",
	),
	ef(
		"fx-retro-vintage-tv",
		"Vintage TV",
		"Retro",
		"Old TV broadcast",
		{ intensity: 0.7 },
		"filter:contrast(1.3) saturate(.8);",
	),
	ef(
		"fx-retro-broadcast",
		"Broadcast",
		"Retro",
		"TV broadcast look",
		{ intensity: 0.5 },
		"filter:contrast(1.2);",
	),
	ef(
		"fx-retro-polaroid",
		"Polaroid",
		"Retro",
		"Polaroid photo",
		{ amount: 0.6 },
		"filter:contrast(1.2) saturate(1.1);",
	),
	ef(
		"fx-retro-faded-print",
		"Faded Print",
		"Retro",
		"Faded print look",
		{ amount: 0.5 },
		"filter:contrast(.9) saturate(.8);",
	),
	ef(
		"fx-retro-kodak",
		"Kodak",
		"Retro",
		"Kodak film tone",
		{ warmth: 0.3 },
		"filter:hue-rotate(-10deg) saturate(1.2);",
	),
	ef(
		"fx-retro-fuji",
		"Fuji",
		"Retro",
		"Fuji film tone",
		{ warmth: -0.2 },
		"filter:hue-rotate(10deg) saturate(1.1);",
	),
	ef(
		"fx-retro-movie",
		"Movie",
		"Retro",
		"Cinema film tone",
		{ amount: 0.5 },
		"filter:contrast(1.2) saturate(.9);",
	),
	ef(
		"fx-retro-technicolor",
		"Technicolor",
		"Retro",
		"Vibrant technicolor",
		{ saturation: 1.5 },
		"filter:saturate(1.5);",
	),
	ef(
		"fx-retro-agfa",
		"Agfa",
		"Retro",
		"Agfa film tone",
		{ amount: 0.5 },
		"filter:saturate(1.1) hue-rotate(5deg);",
	),
	ef(
		"fx-retro-ilford",
		"Ilford",
		"Retro",
		"Ilford B&W tone",
		{ amount: 0.6 },
		"filter:grayscale(1) contrast(1.2);",
	),

	// ── Cinematic (15)
	ef(
		"fx-cine-letterbox",
		"Letterbox",
		"Cinematic",
		"Cinematic letterbox bars",
		{ barHeight: 12 },
		"background-image:linear-gradient(#000 0 12%, transparent 12% 88%, #000 88% 100%);",
	),
	ef(
		"fx-cine-bleach-bypass",
		"Bleach Bypass",
		"Cinematic",
		"Bleach bypass look",
		{ amount: 0.6 },
		"filter:contrast(1.3) saturate(.7);",
	),
	ef(
		"fx-cine-teal-orange",
		"Teal & Orange",
		"Cinematic",
		"Teal and orange grade",
		{ intensity: 0.7 },
		"filter:saturate(1.2);",
	),
	ef(
		"fx-cine-cinestill",
		"CineStill",
		"Cinematic",
		"CineStill film stock",
		{ warmth: 0.3 },
		"filter:hue-rotate(-15deg) saturate(1.2);",
	),
	ef(
		"fx-cine-anamorphic-cine",
		"Anamorphic Cine",
		"Cinematic",
		"Anamorphic widescreen",
		{ aspect: 2.39 },
		"transform:scaleX(2.39);",
	),
	ef(
		"fx-cine-bokeh-cine",
		"Cinematic Bokeh",
		"Cinematic",
		"Background bokeh",
		{ amount: 0.6 },
		"filter:blur(8px);",
	),
	ef(
		"fx-cine-grade-cool",
		"Cool Grade",
		"Cinematic",
		"Cool cinematic grade",
		{ intensity: 0.5 },
		"filter:hue-rotate(15deg) saturate(1.1);",
	),
	ef(
		"fx-cine-grade-warm",
		"Warm Grade",
		"Cinematic",
		"Warm cinematic grade",
		{ intensity: 0.5 },
		"filter:hue-rotate(-15deg) saturate(1.1);",
	),
	ef(
		"fx-cine-pop",
		"Cinematic Pop",
		"Cinematic",
		"Vibrant cinematic pop",
		{ intensity: 0.7 },
		"filter:contrast(1.2) saturate(1.3);",
	),
	ef(
		"fx-cine-moody",
		"Moody",
		"Cinematic",
		"Moody dark cinematic",
		{ intensity: 0.7 },
		"filter:contrast(1.3) brightness(.9);",
	),
	ef(
		"fx-cine-vintage-cine",
		"Vintage Cine",
		"Cinematic",
		"Vintage cinematic look",
		{ amount: 0.6 },
		"filter:sepia(.4) contrast(1.1);",
	),
	ef(
		"fx-cine-noir-cine",
		"Noir",
		"Cinematic",
		"Film noir cinematic",
		{ intensity: 0.8 },
		"filter:grayscale(1) contrast(1.4);",
	),
	ef(
		"fx-cine-blockbuster",
		"Blockbuster",
		"Cinematic",
		"Blockbuster color grade",
		{ intensity: 0.7 },
		"filter:contrast(1.2) saturate(1.2);",
	),
	ef(
		"fx-cine-spotlight",
		"Spotlight Cinematic",
		"Cinematic",
		"Spotlight cinematic",
		{ intensity: 0.6 },
		"filter:brightness(1.2);",
	),
	ef(
		"fx-cine-pan-speed",
		"Speed Pan",
		"Cinematic",
		"Speed pan blur",
		{ intensity: 0.5 },
		"filter:blur(4px);",
	),

	// ── Artistic (15)
	ef(
		"fx-art-watercolor",
		"Watercolor",
		"Artistic",
		"Watercolor paint look",
		{ intensity: 0.6 },
		"filter:blur(2px) saturate(1.2);",
	),
	ef(
		"fx-art-oil-paint",
		"Oil Paint",
		"Artistic",
		"Oil paint brush look",
		{ intensity: 0.7 },
		"filter:blur(3px) saturate(1.4);",
	),
	ef(
		"fx-art-pencil",
		"Pencil",
		"Artistic",
		"Pencil sketch look",
		{ intensity: 0.8 },
		"filter:grayscale(1) contrast(2);",
	),
	ef(
		"fx-art-charcoal",
		"Charcoal",
		"Artistic",
		"Charcoal drawing look",
		{ intensity: 0.7 },
		"filter:grayscale(1) contrast(1.8);",
	),
	ef(
		"fx-art-ink",
		"Ink",
		"Artistic",
		"Ink illustration look",
		{ intensity: 0.8 },
		"filter:contrast(2) saturate(0);",
	),
	ef(
		"fx-art-pastel",
		"Pastel",
		"Artistic",
		"Pastel drawing look",
		{ intensity: 0.6 },
		"filter:saturate(.7) brightness(1.1);",
	),
	ef(
		"fx-art-marker",
		"Marker",
		"Artistic",
		"Marker pen look",
		{ intensity: 0.7 },
		"filter:contrast(1.5) saturate(1.4);",
	),
	ef(
		"fx-art-stained-glass",
		"Stained Glass",
		"Artistic",
		"Stained glass look",
		{ intensity: 0.7 },
		"filter:saturate(2);",
	),
	ef(
		"fx-art-mosaic-art",
		"Mosaic Art",
		"Artistic",
		"Mosaic art tiles",
		{ size: 12 },
		"filter:contrast(2);",
	),
	ef(
		"fx-art-cubism",
		"Cubism",
		"Artistic",
		"Cubist style",
		{ amount: 0.6 },
		"filter:saturate(1.3);",
	),
	ef(
		"fx-art-impressionist",
		"Impressionist",
		"Artistic",
		"Impressionist painting",
		{ amount: 0.6 },
		"filter:blur(1px) saturate(1.3);",
	),
	ef(
		"fx-art-pop-art",
		"Pop Art",
		"Artistic",
		"Pop art style",
		{ intensity: 0.8 },
		"filter:contrast(1.5) saturate(2);",
	),
	ef(
		"fx-art-anime",
		"Anime",
		"Artistic",
		"Anime-style cel shading",
		{ intensity: 0.7 },
		"filter:contrast(1.3) saturate(1.3);",
	),
	ef(
		"fx-art-comic-art",
		"Comic",
		"Artistic",
		"Comic book art style",
		{ intensity: 0.7 },
		"filter:contrast(1.5) saturate(1.5);",
	),
	ef(
		"fx-art-pixel-art",
		"Pixel Art",
		"Artistic",
		"Pixel art retro",
		{ size: 4 },
		"filter:contrast(2);",
	),

	// ── Generator (15)
	ef(
		"fx-gen-solid",
		"Solid Color",
		"Generator",
		"Flat solid color",
		{ color: "#ff0000" },
		"background-color:#ff0000;",
	),
	ef(
		"fx-gen-gradient",
		"Gradient",
		"Generator",
		"Two-color gradient",
		{ colorA: "#ff0000", colorB: "#0000ff", angle: 90 },
		"background:linear-gradient(90deg, #ff0000, #0000ff);",
	),
	ef(
		"fx-gen-radial-gradient",
		"Radial Gradient",
		"Generator",
		"Radial color gradient",
		{ colorA: "#ff0000", colorB: "#0000ff" },
		"background:radial-gradient(#ff0000, #0000ff);",
	),
	ef(
		"fx-gen-noise",
		"Noise",
		"Generator",
		"Procedural noise",
		{ amount: 0.5 },
		"filter:contrast(2);",
	),
	ef(
		"fx-gen-checkerboard",
		"Checkerboard",
		"Generator",
		"Checkerboard pattern",
		{ size: 20 },
		"background-image:linear-gradient(45deg, #000 25%, transparent 25%), linear-gradient(-45deg, #000 25%, transparent 25%), linear-gradient(45deg, transparent 75%, #000 75%), linear-gradient(-45deg, transparent 75%, #000 75%); background-size:20px 20px;",
	),
	ef(
		"fx-gen-stripes",
		"Stripes",
		"Generator",
		"Stripe pattern",
		{ width: 10 },
		"background-image:repeating-linear-gradient(0deg, #000 0 5px, #fff 5px 10px);",
	),
	ef(
		"fx-gen-grid-gen",
		"Grid",
		"Generator",
		"Grid pattern",
		{ size: 20 },
		"background-image:linear-gradient(#000 1px, transparent 1px), linear-gradient(90deg, #000 1px, transparent 1px); background-size:20px 20px;",
	),
	ef(
		"fx-gen-dots-gen",
		"Dots",
		"Generator",
		"Dot pattern",
		{ size: 16 },
		"background-image:radial-gradient(#000 30%, transparent 35%); background-size:16px 16px;",
	),
	ef(
		"fx-gen-zigzag",
		"Zigzag",
		"Generator",
		"Zigzag pattern",
		{ width: 10 },
		"background:linear-gradient(135deg, #000 25%, transparent 25%) -10px 0, linear-gradient(225deg, #000 25%, transparent 25%) -10px 0; background-size:20px 20px;",
	),
	ef(
		"fx-gen-triangles-gen",
		"Triangles",
		"Generator",
		"Triangle pattern",
		{ size: 30 },
		"background-image:linear-gradient(60deg, #000 25%, transparent 25.5%, transparent 75%, #000 75%, #000), linear-gradient(120deg, #000 25%, transparent 25.5%, transparent 75%, #000 75%, #000); background-size:30px 30px;",
	),
	ef(
		"fx-gen-hexagons-gen",
		"Hexagons",
		"Generator",
		"Hexagon pattern",
		{ size: 30 },
		"background-image:radial-gradient(circle farthest-side at 0% 50%, #000 23.5%, transparent 0) 0 0/30px 60px, radial-gradient(circle farthest-side at 50% 50%, #000 23.5%, transparent 0) 15px 30px/30px 60px;",
	),
	ef(
		"fx-gen-text-overlay",
		"Text Overlay",
		"Generator",
		"Text overlay",
		{ text: "SAMPLE", size: 64, color: "#ffffff" },
		"color:#fff;",
	),
	ef(
		"fx-gen-counter",
		"Counter",
		"Generator",
		"Animated counter",
		{ from: 0, to: 100 },
		"color:#fff;",
	),
	ef(
		"fx-gen-clock",
		"Clock",
		"Generator",
		"Animated clock",
		{ format: "HH:MM:SS" },
		"color:#fff;",
	),
	ef(
		"fx-gen-qr",
		"QR Code",
		"Generator",
		"Procedural QR placeholder",
		{ size: 200 },
		"background-color:#fff;",
	),

	// ── Added: distinct named presets (replacing the old "Effect N" filler).
	ef(
		"fx-color-bleach",
		"Bleach Bypass",
		"Color",
		"High-contrast desaturated film look",
		{ saturation: 0.4, contrast: 1.4 },
		"filter:contrast(1.4) saturate(0.4) brightness(1.05);",
	),
	ef(
		"fx-color-crossprocess",
		"Cross Process",
		"Color",
		"Shifted greens and cyan shadows",
		{ hue: -15, saturation: 1.3 },
		"filter:hue-rotate(-15deg) saturate(1.3) contrast(1.15);",
	),
	ef(
		"fx-color-infrared",
		"Infrared",
		"Color",
		"Surreal channel-swapped tones",
		{ hue: 180, saturation: 1.5 },
		"filter:hue-rotate(180deg) saturate(1.5);",
	),
	ef(
		"fx-glow-dream",
		"Dream Glow",
		"Glow",
		"Soft blooming highlight glow",
		{ radius: 8, intensity: 0.6 },
		"filter:blur(0.5px) brightness(1.15) contrast(0.95);",
	),
	ef(
		"fx-stylize-posterize",
		"Posterize",
		"Stylize",
		"Reduced tonal banding",
		{ levels: 6 },
		"filter:contrast(1.6) saturate(1.2);",
	),
	ef(
		"fx-stylize-solarize",
		"Solarize",
		"Stylize",
		"Partial tonal inversion",
		{ threshold: 0.5 },
		"filter:invert(0.5) contrast(1.3);",
	),
	ef(
		"fx-distort-ripple",
		"Ripple",
		"Distortion",
		"Concentric wave distortion",
		{ amplitude: 8, frequency: 12 },
		"filter:blur(0.4px);",
	),
	ef(
		"fx-distort-pinch",
		"Pinch",
		"Distortion",
		"Center pinch warp",
		{ amount: 0.4 },
		"transform:scale(1.02);",
	),
	ef(
		"fx-retro-crt",
		"CRT Scanlines",
		"Retro",
		"Old monitor scanline overlay",
		{ lineGap: 3, curvature: 0.1 },
		"background:repeating-linear-gradient(0deg,rgba(0,0,0,0.25) 0px,rgba(0,0,0,0.25) 1px,transparent 1px,transparent 3px);",
	),
	ef(
		"fx-retro-sepia",
		"Sepia Reel",
		"Retro",
		"Aged sepia film tone",
		{ amount: 0.8 },
		"filter:sepia(0.8) contrast(1.1) brightness(1.05);",
	),
	ef(
		"fx-cinematic-teal-shadow",
		"Teal Shadows",
		"Cinematic",
		"Cool shadows, warm skin",
		{ shadowHue: 190, highlightHue: 30 },
		"filter:contrast(1.2) saturate(1.1) hue-rotate(-6deg);",
	),
	ef(
		"fx-cinematic-noir",
		"Noir",
		"Cinematic",
		"High-contrast black and white",
		{ contrast: 1.5 },
		"filter:grayscale(1) contrast(1.5) brightness(0.95);",
	),
	ef(
		"fx-artistic-oil",
		"Oil Paint",
		"Artistic",
		"Brushed oil-paint smear",
		{ radius: 4 },
		"filter:saturate(1.4) contrast(1.1);",
	),
	ef(
		"fx-artistic-sketch",
		"Pencil Sketch",
		"Artistic",
		"Edge-traced pencil look",
		{ strength: 0.7 },
		"filter:grayscale(1) contrast(1.8) invert(0.05);",
	),
	ef(
		"fx-texture-grain",
		"Film Grain",
		"Texture",
		"Subtle monochrome grain",
		{ amount: 0.3 },
		"background:repeating-radial-gradient(circle,rgba(255,255,255,0.04) 0,rgba(0,0,0,0.04) 1px);",
	),
	ef(
		"fx-light-rays",
		"God Rays",
		"Light",
		"Volumetric light shafts",
		{ angle: 45, intensity: 0.5 },
		"background:linear-gradient(45deg,transparent 40%,rgba(255,255,255,0.18) 50%,transparent 60%);",
	),
];
