// Motion presets — 150 entries (In 40, Out 40, InOut 35, Loop 35).
// Shape: { id, name, description, category, keyframes, targetProperties }.

import type {
	MotionCategory,
	MotionKeyframe,
	MotionPreset,
	MotionTargetProperty,
} from "./types";

const mp = (
	id: string,
	name: string,
	description: string,
	category: MotionCategory,
	targetProperties: MotionTargetProperty[],
	keyframes: MotionKeyframe[],
): MotionPreset => ({
	id,
	name,
	description,
	category,
	targetProperties,
	keyframes,
});

export const motionPresets: MotionPreset[] = [
	// ── In (40)
	mp(
		"m-in-fade",
		"Fade In",
		"Standard opacity fade in",
		"In",
		["opacity"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-in-fade-fast",
		"Fade In Fast",
		"Quick fade in",
		"In",
		["opacity"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-in-fade-slow",
		"Fade In Slow",
		"Slow fade in",
		"In",
		["opacity"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-in-fade-elastic",
		"Fade In Elastic",
		"Bouncy fade",
		"In",
		["opacity"],
		[
			{ t: 0, value: 0, easing: "cubic-bezier(.68,-.55,.27,1.55)" },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-in-slide-up",
		"Slide Up In",
		"Slide in from below",
		"In",
		["translate"],
		[
			{ t: 0, value: 100 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-slide-down",
		"Slide Down In",
		"Slide in from above",
		"In",
		["translate"],
		[
			{ t: 0, value: -100 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-slide-left",
		"Slide Left In",
		"Slide in from right",
		"In",
		["translate"],
		[
			{ t: 0, value: 100 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-slide-right",
		"Slide Right In",
		"Slide in from left",
		"In",
		["translate"],
		[
			{ t: 0, value: -100 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-slide-up-soft",
		"Slide Up Soft",
		"Soft slide from below",
		"In",
		["translate"],
		[
			{ t: 0, value: 40 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-slide-down-soft",
		"Slide Down Soft",
		"Soft slide from above",
		"In",
		["translate"],
		[
			{ t: 0, value: -40 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-scale-up",
		"Scale Up",
		"Scale from small to full",
		"In",
		["scale"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-in-scale-down",
		"Scale Down",
		"Scale from large to full",
		"In",
		["scale"],
		[
			{ t: 0, value: 1.5 },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-in-pop",
		"Pop In",
		"Spring pop in",
		"In",
		["scale"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: 1, easing: "cubic-bezier(.34,1.56,.64,1)" },
		],
	),
	mp(
		"m-in-bounce",
		"Bounce In",
		"Bouncing entry",
		"In",
		["scale"],
		[
			{ t: 0, value: 0 },
			{ t: 0.6, value: 1.1 },
			{ t: 0.8, value: 0.95 },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-in-elastic",
		"Elastic In",
		"Elastic spring entry",
		"In",
		["scale"],
		[
			{ t: 0, value: 0, easing: "cubic-bezier(.68,-.55,.27,1.55)" },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-in-rotate-cw",
		"Rotate CW",
		"Rotate clockwise in",
		"In",
		["rotate"],
		[
			{ t: 0, value: -180 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-rotate-ccw",
		"Rotate CCW",
		"Rotate counter-clockwise in",
		"In",
		["rotate"],
		[
			{ t: 0, value: 180 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-spin-360",
		"Spin 360",
		"Full spin entry",
		"In",
		["rotate"],
		[
			{ t: 0, value: -360 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-flip-y",
		"Flip Y In",
		"Flip from vertical",
		"In",
		["rotate"],
		[
			{ t: 0, value: -90 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-flip-x",
		"Flip X In",
		"Flip from horizontal",
		"In",
		["rotate"],
		[
			{ t: 0, value: -90 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-zoom-far",
		"Zoom Far",
		"Zoom in from far",
		"In",
		["scale"],
		[
			{ t: 0, value: 3 },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-in-zoom-near",
		"Zoom Near",
		"Zoom in from very near",
		"In",
		["scale"],
		[
			{ t: 0, value: 0.5 },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-in-blur",
		"Blur In",
		"From blurred to sharp",
		"In",
		["blur"],
		[
			{ t: 0, value: 20 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-unblur",
		"Unblur In",
		"From sharp to soft focus",
		"In",
		["blur"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: 10 },
		],
	),
	mp(
		"m-in-fade-slide",
		"Fade & Slide",
		"Combined fade slide",
		"In",
		["opacity", "translate"],
		[
			{ t: 0, value: 0 },
			{ t: 0, value: 50 },
			{ t: 1, value: 1 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-fade-scale",
		"Fade & Scale",
		"Combined fade scale",
		"In",
		["opacity", "scale"],
		[
			{ t: 0, value: 0 },
			{ t: 0, value: 0.8 },
			{ t: 1, value: 1 },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-in-fade-rotate",
		"Fade & Rotate",
		"Combined fade rotate",
		"In",
		["opacity", "rotate"],
		[
			{ t: 0, value: 0 },
			{ t: 0, value: -90 },
			{ t: 1, value: 1 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-stretch-x",
		"Stretch X",
		"Horizontal stretch entry",
		"In",
		["scale"],
		[
			{ t: 0, value: 0 },
			{ t: 0.5, value: 1.2 },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-in-stretch-y",
		"Stretch Y",
		"Vertical stretch entry",
		"In",
		["scale"],
		[
			{ t: 0, value: 0 },
			{ t: 0.5, value: 1.2 },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-in-swing",
		"Swing In",
		"Swinging entry",
		"In",
		["rotate"],
		[
			{ t: 0, value: -45 },
			{ t: 0.5, value: 15 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-fall",
		"Fall In",
		"Falling from above",
		"In",
		["translate", "rotate"],
		[
			{ t: 0, value: -200 },
			{ t: 0, value: -90 },
			{ t: 1, value: 0 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-rise",
		"Rise In",
		"Rising from below",
		"In",
		["translate", "opacity"],
		[
			{ t: 0, value: 100 },
			{ t: 0, value: 0 },
			{ t: 1, value: 0 },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-in-fly-left",
		"Fly From Right",
		"Fly in from right",
		"In",
		["translate"],
		[
			{ t: 0, value: 200 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-fly-right",
		"Fly From Left",
		"Fly in from left",
		"In",
		["translate"],
		[
			{ t: 0, value: -200 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-drop",
		"Drop In",
		"Drop with bounce",
		"In",
		["translate"],
		[
			{ t: 0, value: -300 },
			{ t: 0.7, value: 0 },
			{ t: 0.85, value: -20 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-drawer-left",
		"Drawer Left",
		"Slide in from left like a drawer",
		"In",
		["translate"],
		[
			{ t: 0, value: -100 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-drawer-right",
		"Drawer Right",
		"Slide in from right like a drawer",
		"In",
		["translate"],
		[
			{ t: 0, value: 100 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-mask-up",
		"Mask Up",
		"Reveal by mask sliding up",
		"In",
		["translate"],
		[
			{ t: 0, value: 100 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-mask-left",
		"Mask Left",
		"Reveal by mask sliding left",
		"In",
		["translate"],
		[
			{ t: 0, value: 100 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-typewriter",
		"Typewriter",
		"Character-by-character reveal",
		"In",
		["opacity"],
		[
			{ t: 0, value: 0 },
			{ t: 0.1, value: 1 },
			{ t: 0.2, value: 0 },
			{ t: 0.3, value: 1 },
			{ t: 0.4, value: 0 },
			{ t: 0.5, value: 1 },
		],
	),

	// ── Out (40)
	mp(
		"m-out-fade",
		"Fade Out",
		"Standard opacity fade out",
		"Out",
		["opacity"],
		[
			{ t: 0, value: 1 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-out-fade-fast",
		"Fade Out Fast",
		"Quick fade out",
		"Out",
		["opacity"],
		[
			{ t: 0, value: 1 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-out-fade-slow",
		"Fade Out Slow",
		"Slow fade out",
		"Out",
		["opacity"],
		[
			{ t: 0, value: 1 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-out-fade-elastic",
		"Fade Out Elastic",
		"Bouncy fade out",
		"Out",
		["opacity"],
		[
			{ t: 0, value: 1 },
			{ t: 1, value: 0, easing: "cubic-bezier(.68,-.55,.27,1.55)" },
		],
	),
	mp(
		"m-out-slide-up",
		"Slide Up Out",
		"Slide out upward",
		"Out",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: -100 },
		],
	),
	mp(
		"m-out-slide-down",
		"Slide Down Out",
		"Slide out downward",
		"Out",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: 100 },
		],
	),
	mp(
		"m-out-slide-left",
		"Slide Left Out",
		"Slide out leftward",
		"Out",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: -100 },
		],
	),
	mp(
		"m-out-slide-right",
		"Slide Right Out",
		"Slide out rightward",
		"Out",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: 100 },
		],
	),
	mp(
		"m-out-slide-up-soft",
		"Slide Up Soft Out",
		"Soft slide out upward",
		"Out",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: -40 },
		],
	),
	mp(
		"m-out-slide-down-soft",
		"Slide Down Soft Out",
		"Soft slide out downward",
		"Out",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: 40 },
		],
	),
	mp(
		"m-out-scale-up",
		"Scale Up Out",
		"Scale to large",
		"Out",
		["scale"],
		[
			{ t: 0, value: 1 },
			{ t: 1, value: 1.5 },
		],
	),
	mp(
		"m-out-scale-down",
		"Scale Down Out",
		"Scale to small",
		"Out",
		["scale"],
		[
			{ t: 0, value: 1 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-out-pop",
		"Pop Out",
		"Pop and disappear",
		"Out",
		["scale"],
		[
			{ t: 0, value: 1 },
			{ t: 0.7, value: 1.1 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-out-bounce",
		"Bounce Out",
		"Bouncing exit",
		"Out",
		["scale"],
		[
			{ t: 0, value: 1 },
			{ t: 0.2, value: 1.05 },
			{ t: 0.5, value: 0.95 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-out-elastic",
		"Elastic Out",
		"Elastic spring exit",
		"Out",
		["scale"],
		[
			{ t: 0, value: 1 },
			{ t: 1, value: 0, easing: "cubic-bezier(.68,-.55,.27,1.55)" },
		],
	),
	mp(
		"m-out-rotate-cw",
		"Rotate CW Out",
		"Rotate clockwise out",
		"Out",
		["rotate"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: 180 },
		],
	),
	mp(
		"m-out-rotate-ccw",
		"Rotate CCW Out",
		"Rotate counter-clockwise out",
		"Out",
		["rotate"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: -180 },
		],
	),
	mp(
		"m-out-spin-360",
		"Spin 360 Out",
		"Full spin exit",
		"Out",
		["rotate"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: 360 },
		],
	),
	mp(
		"m-out-flip-y",
		"Flip Y Out",
		"Flip vertical out",
		"Out",
		["rotate"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: 90 },
		],
	),
	mp(
		"m-out-flip-x",
		"Flip X Out",
		"Flip horizontal out",
		"Out",
		["rotate"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: 90 },
		],
	),
	mp(
		"m-out-zoom-far",
		"Zoom Out Far",
		"Zoom out to far",
		"Out",
		["scale"],
		[
			{ t: 0, value: 1 },
			{ t: 1, value: 3 },
		],
	),
	mp(
		"m-out-zoom-near",
		"Zoom Out Near",
		"Zoom out to near",
		"Out",
		["scale"],
		[
			{ t: 0, value: 1 },
			{ t: 1, value: 0.5 },
		],
	),
	mp(
		"m-out-blur",
		"Blur Out",
		"Sharp to blurred",
		"Out",
		["blur"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: 20 },
		],
	),
	mp(
		"m-out-unblur",
		"Unblur Out",
		"Soft to sharp focus",
		"Out",
		["blur"],
		[
			{ t: 0, value: 10 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-out-fade-slide",
		"Fade & Slide Out",
		"Combined fade slide out",
		"Out",
		["opacity", "translate"],
		[
			{ t: 0, value: 1 },
			{ t: 0, value: 0 },
			{ t: 1, value: 0 },
			{ t: 1, value: -50 },
		],
	),
	mp(
		"m-out-fade-scale",
		"Fade & Scale Out",
		"Combined fade scale out",
		"Out",
		["opacity", "scale"],
		[
			{ t: 0, value: 1 },
			{ t: 0, value: 1 },
			{ t: 1, value: 0 },
			{ t: 1, value: 0.8 },
		],
	),
	mp(
		"m-out-fade-rotate",
		"Fade & Rotate Out",
		"Combined fade rotate out",
		"Out",
		["opacity", "rotate"],
		[
			{ t: 0, value: 1 },
			{ t: 0, value: 0 },
			{ t: 1, value: 0 },
			{ t: 1, value: 90 },
		],
	),
	mp(
		"m-out-stretch-x",
		"Stretch X Out",
		"Horizontal stretch exit",
		"Out",
		["scale"],
		[
			{ t: 0, value: 1 },
			{ t: 0.5, value: 1.2 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-out-stretch-y",
		"Stretch Y Out",
		"Vertical stretch exit",
		"Out",
		["scale"],
		[
			{ t: 0, value: 1 },
			{ t: 0.5, value: 1.2 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-out-swing",
		"Swing Out",
		"Swinging exit",
		"Out",
		["rotate"],
		[
			{ t: 0, value: 0 },
			{ t: 0.5, value: -15 },
			{ t: 1, value: 45 },
		],
	),
	mp(
		"m-out-fall",
		"Fall Out",
		"Falling exit",
		"Out",
		["translate", "rotate"],
		[
			{ t: 0, value: 0 },
			{ t: 0, value: 0 },
			{ t: 1, value: 200 },
			{ t: 1, value: 90 },
		],
	),
	mp(
		"m-out-rise",
		"Rise Out",
		"Rising exit",
		"Out",
		["translate", "opacity"],
		[
			{ t: 0, value: 0 },
			{ t: 0, value: 1 },
			{ t: 1, value: -100 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-out-fly-left",
		"Fly Left Out",
		"Fly out to left",
		"Out",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: -200 },
		],
	),
	mp(
		"m-out-fly-right",
		"Fly Right Out",
		"Fly out to right",
		"Out",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: 200 },
		],
	),
	mp(
		"m-out-drop",
		"Drop Out",
		"Drop and disappear",
		"Out",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: 300 },
		],
	),
	mp(
		"m-out-drawer-left",
		"Drawer Left Out",
		"Slide out left like a drawer",
		"Out",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: -100 },
		],
	),
	mp(
		"m-out-drawer-right",
		"Drawer Right Out",
		"Slide out right like a drawer",
		"Out",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: 100 },
		],
	),
	mp(
		"m-out-mask-up",
		"Mask Up Out",
		"Mask slides up to hide",
		"Out",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: -100 },
		],
	),
	mp(
		"m-out-mask-left",
		"Mask Left Out",
		"Mask slides left to hide",
		"Out",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: -100 },
		],
	),
	mp(
		"m-out-vanish",
		"Vanish",
		"Disappear with flash",
		"Out",
		["opacity", "scale"],
		[
			{ t: 0, value: 1 },
			{ t: 0, value: 1 },
			{ t: 0.5, value: 0.5 },
			{ t: 0.5, value: 1.2 },
			{ t: 1, value: 0 },
			{ t: 1, value: 0 },
		],
	),

	// ── InOut (35)
	mp(
		"m-io-fade",
		"Fade In & Out",
		"Symmetric fade in and out",
		"InOut",
		["opacity"],
		[
			{ t: 0, value: 0 },
			{ t: 0.5, value: 1 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-io-fade-soft",
		"Fade Soft",
		"Soft symmetric fade",
		"InOut",
		["opacity"],
		[
			{ t: 0, value: 0 },
			{ t: 0.5, value: 1 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-io-fade-slow",
		"Fade Slow",
		"Slow symmetric fade",
		"InOut",
		["opacity"],
		[
			{ t: 0, value: 0 },
			{ t: 0.5, value: 1 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-io-slide-through",
		"Slide Through",
		"Slide in then slide out opposite",
		"InOut",
		["translate"],
		[
			{ t: 0, value: -100 },
			{ t: 0.5, value: 0 },
			{ t: 1, value: 100 },
		],
	),
	mp(
		"m-io-slide-up-through",
		"Slide Up Through",
		"Up then down",
		"InOut",
		["translate"],
		[
			{ t: 0, value: 100 },
			{ t: 0.5, value: 0 },
			{ t: 1, value: -100 },
		],
	),
	mp(
		"m-io-zoom-pulse",
		"Zoom Pulse",
		"Zoom in then zoom out",
		"InOut",
		["scale"],
		[
			{ t: 0, value: 0 },
			{ t: 0.5, value: 1 },
			{ t: 1, value: 2 },
		],
	),
	mp(
		"m-io-zoom-implode",
		"Zoom Implode",
		"Implode from edges",
		"InOut",
		["scale"],
		[
			{ t: 0, value: 1.5 },
			{ t: 0.5, value: 1 },
			{ t: 1, value: 0.5 },
		],
	),
	mp(
		"m-io-bounce",
		"Bounce In & Out",
		"Bounce at both ends",
		"InOut",
		["scale"],
		[
			{ t: 0, value: 0 },
			{ t: 0.3, value: 1.1 },
			{ t: 0.5, value: 1 },
			{ t: 0.7, value: 1.1 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-io-elastic",
		"Elastic In & Out",
		"Elastic both ways",
		"InOut",
		["scale"],
		[
			{ t: 0, value: 0, easing: "cubic-bezier(.68,-.55,.27,1.55)" },
			{ t: 0.5, value: 1 },
			{ t: 1, value: 0, easing: "cubic-bezier(.68,-.55,.27,1.55)" },
		],
	),
	mp(
		"m-io-spin",
		"Spin In & Out",
		"Spin entry and exit",
		"InOut",
		["rotate"],
		[
			{ t: 0, value: -180 },
			{ t: 0.5, value: 0 },
			{ t: 1, value: 180 },
		],
	),
	mp(
		"m-io-flip",
		"Flip In & Out",
		"Flip both ways",
		"InOut",
		["rotate"],
		[
			{ t: 0, value: -90 },
			{ t: 0.5, value: 0 },
			{ t: 1, value: 90 },
		],
	),
	mp(
		"m-io-pendulum",
		"Pendulum",
		"Swing back and forth",
		"InOut",
		["rotate"],
		[
			{ t: 0, value: -30 },
			{ t: 0.5, value: 30 },
			{ t: 1, value: -30 },
		],
	),
	mp(
		"m-io-fade-slide-in",
		"Fade Slide In Out",
		"Fade and slide on entry/exit",
		"InOut",
		["opacity", "translate"],
		[
			{ t: 0, value: 0 },
			{ t: 0, value: 50 },
			{ t: 0.5, value: 1 },
			{ t: 0.5, value: 0 },
			{ t: 1, value: 0 },
			{ t: 1, value: -50 },
		],
	),
	mp(
		"m-io-fade-scale-in",
		"Fade Scale In Out",
		"Fade and scale on entry/exit",
		"InOut",
		["opacity", "scale"],
		[
			{ t: 0, value: 0 },
			{ t: 0, value: 0.8 },
			{ t: 0.5, value: 1 },
			{ t: 0.5, value: 1 },
			{ t: 1, value: 0 },
			{ t: 1, value: 1.2 },
		],
	),
	mp(
		"m-io-fade-rotate-in",
		"Fade Rotate In Out",
		"Fade and rotate",
		"InOut",
		["opacity", "rotate"],
		[
			{ t: 0, value: 0 },
			{ t: 0, value: -45 },
			{ t: 0.5, value: 1 },
			{ t: 0.5, value: 0 },
			{ t: 1, value: 0 },
			{ t: 1, value: 45 },
		],
	),
	mp(
		"m-io-blink",
		"Blink",
		"Quick on-off-on-off",
		"InOut",
		["opacity"],
		[
			{ t: 0, value: 0 },
			{ t: 0.25, value: 1 },
			{ t: 0.5, value: 1 },
			{ t: 0.75, value: 0 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-io-flicker",
		"Flicker",
		"Irregular flicker",
		"InOut",
		["opacity"],
		[
			{ t: 0, value: 0 },
			{ t: 0.1, value: 1 },
			{ t: 0.2, value: 0 },
			{ t: 0.3, value: 1 },
			{ t: 0.5, value: 1 },
			{ t: 0.7, value: 0 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-io-strobe",
		"Strobe",
		"Fast strobe",
		"InOut",
		["opacity"],
		[
			{ t: 0, value: 0 },
			{ t: 0.2, value: 1 },
			{ t: 0.4, value: 0 },
			{ t: 0.6, value: 1 },
			{ t: 0.8, value: 0 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-io-glitch-in-out",
		"Glitch In & Out",
		"Glitch at start and end",
		"InOut",
		["translate"],
		[
			{ t: 0, value: -10 },
			{ t: 0.1, value: 10 },
			{ t: 0.2, value: 0 },
			{ t: 0.5, value: 0 },
			{ t: 0.8, value: -10 },
			{ t: 0.9, value: 10 },
			{ t: 1, value: 10 },
		],
	),
	mp(
		"m-io-bounce-y",
		"Bounce Y",
		"Vertical bounce",
		"InOut",
		["translate"],
		[
			{ t: 0, value: -50 },
			{ t: 0.5, value: 0 },
			{ t: 1, value: 50 },
		],
	),
	mp(
		"m-io-bounce-x",
		"Bounce X",
		"Horizontal bounce",
		"InOut",
		["translate"],
		[
			{ t: 0, value: -50 },
			{ t: 0.5, value: 0 },
			{ t: 1, value: 50 },
		],
	),
	mp(
		"m-io-wave-in-out",
		"Wave",
		"Wave motion in and out",
		"InOut",
		["translate"],
		[
			{ t: 0, value: -30 },
			{ t: 0.25, value: 30 },
			{ t: 0.75, value: -30 },
			{ t: 1, value: 30 },
		],
	),
	mp(
		"m-io-swing",
		"Swing",
		"Pendulum swing",
		"InOut",
		["rotate"],
		[
			{ t: 0, value: -45 },
			{ t: 0.5, value: 45 },
			{ t: 1, value: -45 },
		],
	),
	mp(
		"m-io-sway",
		"Sway",
		"Gentle sway",
		"InOut",
		["rotate"],
		[
			{ t: 0, value: -10 },
			{ t: 0.5, value: 10 },
			{ t: 1, value: -10 },
		],
	),
	mp(
		"m-io-jelly",
		"Jelly",
		"Jelly wobble",
		"InOut",
		["scale"],
		[
			{ t: 0, value: 0.8 },
			{ t: 0.25, value: 1.1 },
			{ t: 0.5, value: 0.95 },
			{ t: 0.75, value: 1.05 },
			{ t: 1, value: 1.2 },
		],
	),
	mp(
		"m-io-jelly-y",
		"Jelly Y",
		"Vertical jelly wobble",
		"InOut",
		["scale"],
		[
			{ t: 0, value: 0.8 },
			{ t: 0.25, value: 1.1 },
			{ t: 0.5, value: 0.95 },
			{ t: 0.75, value: 1.05 },
			{ t: 1, value: 1.2 },
		],
	),
	mp(
		"m-io-pendulum-y",
		"Pendulum Y",
		"Vertical pendulum",
		"InOut",
		["translate"],
		[
			{ t: 0, value: -30 },
			{ t: 0.5, value: 30 },
			{ t: 1, value: -30 },
		],
	),
	mp(
		"m-io-blink-twice",
		"Blink Twice",
		"Two quick blinks",
		"InOut",
		["opacity"],
		[
			{ t: 0, value: 0 },
			{ t: 0.1, value: 1 },
			{ t: 0.2, value: 0 },
			{ t: 0.3, value: 1 },
			{ t: 0.5, value: 1 },
			{ t: 0.7, value: 0 },
			{ t: 0.8, value: 1 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-io-double-pop",
		"Double Pop",
		"Two pop bounces",
		"InOut",
		["scale"],
		[
			{ t: 0, value: 0 },
			{ t: 0.25, value: 1.2 },
			{ t: 0.4, value: 0.9 },
			{ t: 0.5, value: 1 },
			{ t: 0.75, value: 1.2 },
			{ t: 0.9, value: 0.9 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-io-scale-pulse",
		"Scale Pulse",
		"Pulse in and out",
		"InOut",
		["scale"],
		[
			{ t: 0, value: 0.5 },
			{ t: 0.5, value: 1.1 },
			{ t: 1, value: 1.5 },
		],
	),
	mp(
		"m-io-fade-blink",
		"Fade Blink",
		"Fade with blinking",
		"InOut",
		["opacity"],
		[
			{ t: 0, value: 0 },
			{ t: 0.2, value: 1 },
			{ t: 0.4, value: 0.3 },
			{ t: 0.5, value: 1 },
			{ t: 0.7, value: 0.5 },
			{ t: 0.85, value: 1 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-io-glitch-jitter",
		"Glitch Jitter",
		"Jitter at start and end",
		"InOut",
		["translate"],
		[
			{ t: 0, value: -5 },
			{ t: 0.05, value: 5 },
			{ t: 0.1, value: -3 },
			{ t: 0.15, value: 3 },
			{ t: 0.5, value: 0 },
			{ t: 0.85, value: 3 },
			{ t: 0.9, value: -3 },
			{ t: 0.95, value: 5 },
			{ t: 1, value: -5 },
		],
	),
	mp(
		"m-io-blink-slow",
		"Slow Blink",
		"Slow blink",
		"InOut",
		["opacity"],
		[
			{ t: 0, value: 0 },
			{ t: 0.3, value: 1 },
			{ t: 0.5, value: 1 },
			{ t: 0.7, value: 0 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-io-rubber",
		"Rubber Band",
		"Rubber band effect",
		"InOut",
		["scale"],
		[
			{ t: 0, value: 0 },
			{ t: 0.4, value: 1.3 },
			{ t: 0.55, value: 0.9 },
			{ t: 0.7, value: 1.1 },
			{ t: 0.85, value: 0.95 },
			{ t: 1, value: 1.1 },
		],
	),
	mp(
		"m-io-swing-zoom",
		"Swing Zoom",
		"Combined swing and zoom",
		"InOut",
		["rotate", "scale"],
		[
			{ t: 0, value: -30 },
			{ t: 0, value: 0 },
			{ t: 0.5, value: 0 },
			{ t: 0.5, value: 1 },
			{ t: 1, value: 30 },
			{ t: 1, value: 1.2 },
		],
	),

	// ── Loop (35)
	mp(
		"m-loop-pulse",
		"Pulse",
		"Steady pulse",
		"Loop",
		["scale"],
		[
			{ t: 0, value: 1 },
			{ t: 0.5, value: 1.1 },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-loop-pulse-strong",
		"Pulse Strong",
		"Strong pulse",
		"Loop",
		["scale"],
		[
			{ t: 0, value: 1 },
			{ t: 0.5, value: 1.3 },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-loop-pulse-fade",
		"Pulse Fade",
		"Pulse with fade",
		"Loop",
		["scale", "opacity"],
		[
			{ t: 0, value: 1 },
			{ t: 0, value: 1 },
			{ t: 0.5, value: 1.2 },
			{ t: 0.5, value: 0.5 },
			{ t: 1, value: 1 },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-loop-breathe",
		"Breathe",
		"Calm breathing",
		"Loop",
		["scale"],
		[
			{ t: 0, value: 1 },
			{ t: 0.5, value: 1.05 },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-loop-heartbeat",
		"Heartbeat",
		"Heartbeat double-thump",
		"Loop",
		["scale"],
		[
			{ t: 0, value: 1 },
			{ t: 0.1, value: 1.15 },
			{ t: 0.2, value: 1 },
			{ t: 0.3, value: 1.15 },
			{ t: 0.4, value: 1 },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-loop-spin",
		"Spin",
		"Continuous spin",
		"Loop",
		["rotate"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: 360 },
		],
	),
	mp(
		"m-loop-spin-reverse",
		"Spin Reverse",
		"Reverse spin",
		"Loop",
		["rotate"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: -360 },
		],
	),
	mp(
		"m-loop-spin-slow",
		"Spin Slow",
		"Slow continuous spin",
		"Loop",
		["rotate"],
		[
			{ t: 0, value: 0 },
			{ t: 1, value: 360 },
		],
	),
	mp(
		"m-loop-swing",
		"Swing",
		"Continuous swing",
		"Loop",
		["rotate"],
		[
			{ t: 0, value: -30 },
			{ t: 0.5, value: 30 },
			{ t: 1, value: -30 },
		],
	),
	mp(
		"m-loop-sway",
		"Sway",
		"Continuous gentle sway",
		"Loop",
		["rotate"],
		[
			{ t: 0, value: -10 },
			{ t: 0.5, value: 10 },
			{ t: 1, value: -10 },
		],
	),
	mp(
		"m-loop-rock",
		"Rock",
		"Rocking motion",
		"Loop",
		["rotate"],
		[
			{ t: 0, value: -15 },
			{ t: 0.5, value: 15 },
			{ t: 1, value: -15 },
		],
	),
	mp(
		"m-loop-float",
		"Float",
		"Floating up and down",
		"Loop",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 0.5, value: -15 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-loop-float-h",
		"Float H",
		"Floating side to side",
		"Loop",
		["translate"],
		[
			{ t: 0, value: -15 },
			{ t: 0.5, value: 15 },
			{ t: 1, value: -15 },
		],
	),
	mp(
		"m-loop-bob",
		"Bob",
		"Vertical bobbing",
		"Loop",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 0.5, value: 10 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-loop-blink",
		"Blink",
		"Steady blink",
		"Loop",
		["opacity"],
		[
			{ t: 0, value: 1 },
			{ t: 0.5, value: 0 },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-loop-fade",
		"Fade",
		"Continuous fade in/out",
		"Loop",
		["opacity"],
		[
			{ t: 0, value: 0.2 },
			{ t: 0.5, value: 1 },
			{ t: 1, value: 0.2 },
		],
	),
	mp(
		"m-loop-flash",
		"Flash",
		"Quick flashes",
		"Loop",
		["opacity"],
		[
			{ t: 0, value: 1 },
			{ t: 0.1, value: 0 },
			{ t: 0.2, value: 1 },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-loop-strobe",
		"Strobe",
		"Fast strobe",
		"Loop",
		["opacity"],
		[
			{ t: 0, value: 1 },
			{ t: 0.2, value: 0 },
			{ t: 0.4, value: 1 },
			{ t: 0.6, value: 0 },
			{ t: 0.8, value: 1 },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-loop-shake",
		"Shake",
		"Random shake",
		"Loop",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 0.1, value: -3 },
			{ t: 0.2, value: 3 },
			{ t: 0.3, value: -2 },
			{ t: 0.4, value: 2 },
			{ t: 0.5, value: 0 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-loop-jitter",
		"Jitter",
		"Subtle jitter",
		"Loop",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 0.25, value: -2 },
			{ t: 0.5, value: 2 },
			{ t: 0.75, value: -1 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-loop-bounce",
		"Bounce",
		"Continuous bounce",
		"Loop",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 0.5, value: -30 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-loop-wiggle",
		"Wiggle",
		"Wiggling rotation",
		"Loop",
		["rotate"],
		[
			{ t: 0, value: -5 },
			{ t: 0.25, value: 5 },
			{ t: 0.5, value: -5 },
			{ t: 0.75, value: 5 },
			{ t: 1, value: -5 },
		],
	),
	mp(
		"m-loop-jelly",
		"Jelly",
		"Jelly wobble",
		"Loop",
		["scale"],
		[
			{ t: 0, value: 1 },
			{ t: 0.3, value: 1.1 },
			{ t: 0.5, value: 0.95 },
			{ t: 0.7, value: 1.05 },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-loop-zoom-breath",
		"Zoom Breath",
		"Breathing zoom",
		"Loop",
		["scale"],
		[
			{ t: 0, value: 1 },
			{ t: 0.5, value: 1.05 },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-loop-pan-left",
		"Pan Left",
		"Continuous pan left",
		"Loop",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 0.5, value: -50 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-loop-pan-right",
		"Pan Right",
		"Continuous pan right",
		"Loop",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 0.5, value: 50 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-loop-orbit",
		"Orbit",
		"Circular orbit",
		"Loop",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 0.25, value: 30 },
			{ t: 0.5, value: 0 },
			{ t: 0.75, value: -30 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-loop-orbit-y",
		"Orbit Y",
		"Vertical orbit",
		"Loop",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 0.25, value: -30 },
			{ t: 0.5, value: 0 },
			{ t: 0.75, value: 30 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-loop-figure-eight",
		"Figure 8",
		"Figure 8 motion",
		"Loop",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 0.25, value: 30 },
			{ t: 0.5, value: 0 },
			{ t: 0.75, value: -30 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-loop-twist",
		"Twist",
		"Continuous twist",
		"Loop",
		["rotate"],
		[
			{ t: 0, value: 0 },
			{ t: 0.5, value: 15 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-loop-wave",
		"Wave",
		"Wave motion",
		"Loop",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 0.25, value: -20 },
			{ t: 0.5, value: 0 },
			{ t: 0.75, value: 20 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-loop-wave-y",
		"Wave Y",
		"Vertical wave motion",
		"Loop",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 0.25, value: 20 },
			{ t: 0.5, value: 0 },
			{ t: 0.75, value: -20 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-loop-spin-3d",
		"Spin 3D",
		"3D continuous rotation",
		"Loop",
		["rotate"],
		[
			{ t: 0, value: 0 },
			{ t: 0.5, value: 180 },
			{ t: 1, value: 360 },
		],
	),
	mp(
		"m-loop-pulse-rotate",
		"Pulse Rotate",
		"Combined pulse and rotate",
		"Loop",
		["scale", "rotate"],
		[
			{ t: 0, value: 1 },
			{ t: 0, value: 0 },
			{ t: 0.5, value: 1.1 },
			{ t: 0.5, value: 5 },
			{ t: 1, value: 1 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-loop-pendulum",
		"Pendulum",
		"Continuous pendulum",
		"Loop",
		["rotate"],
		[
			{ t: 0, value: -45 },
			{ t: 0.5, value: 45 },
			{ t: 1, value: -45 },
		],
	),

	// ── Added: distinct named presets (replacing the old "Motion N" filler).
	mp(
		"m-in-drift-up",
		"Drift Up",
		"Floats up into place while fading in",
		"In",
		["opacity", "translate"],
		[
			{ t: 0, value: 0 },
			{ t: 0, value: 40, easing: "ease-out-cubic" },
			{ t: 1, value: 1 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-spring-pop",
		"Spring Pop",
		"Overshoots then settles with a springy scale",
		"In",
		["opacity", "scale"],
		[
			{ t: 0, value: 0 },
			{ t: 0, value: 0.4, easing: "cubic-bezier(.34,1.56,.64,1)" },
			{ t: 0.6, value: 1 },
			{ t: 0.6, value: 1.12 },
			{ t: 1, value: 1 },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-in-skew-slide",
		"Skew In",
		"Slides in from the left with a slight skew",
		"In",
		["opacity", "translate"],
		[
			{ t: 0, value: 0 },
			{ t: 0, value: -60, easing: "ease-out-back" },
			{ t: 1, value: 1 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-unblur",
		"Unblur",
		"Resolves from a blur into focus",
		"In",
		["opacity", "blur"],
		[
			{ t: 0, value: 0 },
			{ t: 0, value: 12 },
			{ t: 1, value: 1 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-swing-down",
		"Swing Down",
		"Drops in rotating from above",
		"In",
		["opacity", "rotate", "translate"],
		[
			{ t: 0, value: 0 },
			{ t: 0, value: -18, easing: "ease-out-back" },
			{ t: 0, value: -50 },
			{ t: 1, value: 1 },
			{ t: 1, value: 0 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-in-zoom-blur",
		"Zoom Blur In",
		"Rushes in from large with motion blur",
		"In",
		["opacity", "scale", "blur"],
		[
			{ t: 0, value: 0 },
			{ t: 0, value: 1.6, easing: "ease-out-expo" },
			{ t: 0, value: 8 },
			{ t: 1, value: 1 },
			{ t: 1, value: 1 },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-out-drift-down",
		"Drift Down",
		"Sinks down while fading out",
		"Out",
		["opacity", "translate"],
		[
			{ t: 0, value: 1 },
			{ t: 0, value: 0, easing: "ease-in-cubic" },
			{ t: 1, value: 0 },
			{ t: 1, value: 40 },
		],
	),
	mp(
		"m-out-collapse",
		"Collapse",
		"Shrinks to nothing on exit",
		"Out",
		["opacity", "scale"],
		[
			{ t: 0, value: 1 },
			{ t: 0, value: 1, easing: "ease-in-back" },
			{ t: 1, value: 0 },
			{ t: 1, value: 0.2 },
		],
	),
	mp(
		"m-out-spin-away",
		"Spin Away",
		"Spins and shrinks out",
		"Out",
		["opacity", "rotate", "scale"],
		[
			{ t: 0, value: 1 },
			{ t: 0, value: 0 },
			{ t: 0, value: 1 },
			{ t: 1, value: 0 },
			{ t: 1, value: 180 },
			{ t: 1, value: 0.4 },
		],
	),
	mp(
		"m-out-reblur",
		"Reblur",
		"Blurs out of focus on exit",
		"Out",
		["opacity", "blur"],
		[
			{ t: 0, value: 1 },
			{ t: 0, value: 0 },
			{ t: 1, value: 0 },
			{ t: 1, value: 14 },
		],
	),
	mp(
		"m-inout-pop-settle",
		"Pop & Settle",
		"Pops in, holds, eases out",
		"InOut",
		["opacity", "scale"],
		[
			{ t: 0, value: 0 },
			{ t: 0, value: 0.6, easing: "cubic-bezier(.34,1.56,.64,1)" },
			{ t: 0.2, value: 1 },
			{ t: 0.2, value: 1 },
			{ t: 0.8, value: 1 },
			{ t: 0.8, value: 1 },
			{ t: 1, value: 0 },
			{ t: 1, value: 0.9 },
		],
	),
	mp(
		"m-inout-slide-through",
		"Slide Through",
		"Enters from left, exits to right",
		"InOut",
		["opacity", "translate"],
		[
			{ t: 0, value: 0 },
			{ t: 0, value: -60, easing: "ease-out-cubic" },
			{ t: 0.25, value: 1 },
			{ t: 0.25, value: 0 },
			{ t: 0.75, value: 1 },
			{ t: 0.75, value: 0, easing: "ease-in-cubic" },
			{ t: 1, value: 0 },
			{ t: 1, value: 60 },
		],
	),
	mp(
		"m-loop-bob",
		"Bob",
		"Gentle vertical bobbing",
		"Loop",
		["translate"],
		[
			{ t: 0, value: 0 },
			{ t: 0.5, value: -14, easing: "ease-in-out" },
			{ t: 1, value: 0 },
		],
	),
	mp(
		"m-loop-sway",
		"Sway",
		"Soft side-to-side sway",
		"Loop",
		["rotate"],
		[
			{ t: 0, value: -6 },
			{ t: 0.5, value: 6, easing: "ease-in-out" },
			{ t: 1, value: -6 },
		],
	),
	mp(
		"m-loop-throb",
		"Throb",
		"Slow scale breathing",
		"Loop",
		["scale"],
		[
			{ t: 0, value: 1 },
			{ t: 0.5, value: 1.08, easing: "ease-in-out" },
			{ t: 1, value: 1 },
		],
	),
	mp(
		"m-loop-flicker",
		"Flicker",
		"Irregular opacity flicker",
		"Loop",
		["opacity"],
		[
			{ t: 0, value: 1 },
			{ t: 0.2, value: 0.4 },
			{ t: 0.35, value: 1 },
			{ t: 0.6, value: 0.6 },
			{ t: 0.75, value: 1 },
			{ t: 1, value: 0.85 },
		],
	),
];
