// Overlays — 161 entries.
// Extracted from docs/asset-library-research.ts.txt (overlays section). The
// source file was truncated mid-stream at ov-ne-003; the Neon category is
// completed here with synthetic entries to round it out to 8.

import type { Overlay, OverlayParticle, OverlaySubcategory } from "./types";

const ov = (
	id: string,
	name: string,
	sub: OverlaySubcategory,
	desc: string,
	blend: Overlay["blendMode"],
	opacity: number,
	css: string,
	visual: string,
	particle?: OverlayParticle,
): Overlay => ({
	id,
	name,
	description: desc,
	category: "overlay",
	subcategory: sub,
	visual,
	blendMode: blend,
	opacity,
	css,
	particle,
});

export const overlays: Overlay[] = [
	// ── LightLeak (15)
	ov("ov-ll-001", "Sunset Leak", "LightLeak", "Warm orange leak from upper-right", "screen", 0.6,
		"background: radial-gradient(circle at 80% 20%, #ffb347 0%, #ff5e3a 35%, transparent 70%);",
		"Soft orange-red glow bleeding diagonally from corner."),
	ov("ov-ll-002", "Magenta Burn", "LightLeak", "Pink magenta flash", "screen", 0.55,
		"background: linear-gradient(135deg, transparent 30%, #ff2bd6 60%, transparent 90%);",
		"Diagonal pink band across the frame."),
	ov("ov-ll-003", "Cyan Wash", "LightLeak", "Cool cyan side leak", "screen", 0.5,
		"background: linear-gradient(90deg, #00e5ff 0%, transparent 50%);",
		"Cyan fade from left edge."),
	ov("ov-ll-004", "Golden Hour", "LightLeak", "Honey gold streak", "soft-light", 0.7,
		"background: linear-gradient(45deg, transparent 40%, #ffcb74 55%, #ff8c42 70%, transparent 85%);",
		"Diagonal gold ribbon."),
	ov("ov-ll-005", "Vintage Burn", "LightLeak", "Aged red corner burn", "overlay", 0.5,
		"background: radial-gradient(ellipse at 0% 100%, #c2410c 0%, transparent 60%);",
		"Red burnt corner like old film."),
	ov("ov-ll-006", "Prism Leak", "LightLeak", "Multi-color rainbow", "screen", 0.45,
		"background: linear-gradient(110deg, #ff0080, #ff8c00, #ffd700, #00ff88, #00b3ff, #a100ff);",
		"Soft rainbow band across diagonal."),
	ov("ov-ll-007", "Studio Flash", "LightLeak", "Center white flash", "screen", 0.8,
		"background: radial-gradient(circle at 50% 50%, #fff 0%, transparent 35%);",
		"White circular flash from center."),
	ov("ov-ll-008", "Cinema Amber", "LightLeak", "Amber edge leak", "screen", 0.55,
		"background: radial-gradient(ellipse at 100% 50%, #ffb155 0%, transparent 55%);",
		"Amber leak on right side."),
	ov("ov-ll-009", "Indigo Drift", "LightLeak", "Cool indigo wash", "soft-light", 0.6,
		"background: linear-gradient(225deg, #4c1d95 0%, transparent 60%);",
		"Indigo gradient from upper-right."),
	ov("ov-ll-010", "Pink Daydream", "LightLeak", "Dream pink overlay", "screen", 0.5,
		"background: radial-gradient(circle at 30% 70%, #ff6ec7 0%, transparent 60%);",
		"Dreamy pink glow lower-left."),
	ov("ov-ll-011", "Lemon Soda", "LightLeak", "Citrus yellow", "screen", 0.5,
		"background: linear-gradient(0deg, #fff200 0%, transparent 50%);",
		"Bright yellow from bottom edge."),
	ov("ov-ll-012", "Vapor Mint", "LightLeak", "Mint green wash", "screen", 0.5,
		"background: radial-gradient(ellipse at 70% 30%, #6effbf 0%, transparent 65%);",
		"Mint green leak upper-right."),
	ov("ov-ll-013", "Dual Burn", "LightLeak", "Two corner burns", "overlay", 0.55,
		"background: radial-gradient(at 0% 0%, #ff7a45 0%, transparent 35%), radial-gradient(at 100% 100%, #ff2dab 0%, transparent 35%);",
		"Orange upper-left and pink lower-right corners burning."),
	ov("ov-ll-014", "Storm Sliver", "LightLeak", "Thin vertical leak", "screen", 0.6,
		"background: linear-gradient(90deg, transparent 45%, #ffe070 50%, transparent 55%);",
		"Thin gold vertical sliver."),
	ov("ov-ll-015", "Solar Flare", "LightLeak", "Off-axis solar bloom", "screen", 0.7,
		"background: radial-gradient(circle at 85% 15%, #fff5b8 0%, #ffbe55 25%, #ff4a3d 50%, transparent 75%);",
		"Layered orange-red solar flare upper right."),

	// ── Dust (10)
	ov("ov-du-001", "Light Dust", "Dust", "Floating fine dust particles", "screen", 0.4,
		"background-color: transparent;",
		"Tiny scattered white specks slowly drifting.",
		{ count: 60, sizePx: [1, 3], speedSec: [8, 16], color: "#ffffff" }),
	ov("ov-du-002", "Heavy Dust", "Dust", "Dense dust particles", "screen", 0.5,
		"background-color: transparent;",
		"Dense field of white dust motes.",
		{ count: 150, sizePx: [1, 4], speedSec: [6, 14], color: "#ffffff" }),
	ov("ov-du-003", "Studio Dust", "Dust", "Backlit dust beams", "screen", 0.35,
		"background: linear-gradient(180deg, transparent, rgba(255,255,200,.05));",
		"Soft warm haze with floating motes.",
		{ count: 80, sizePx: [1, 3], speedSec: [10, 20], color: "#fffacd" }),
	ov("ov-du-004", "Attic Dust", "Dust", "Old yellowed motes", "multiply", 0.6,
		"background-color: transparent;",
		"Yellow-tinted floating particles.",
		{ count: 90, sizePx: [2, 5], speedSec: [12, 20], color: "#e8d28a" }),
	ov("ov-du-005", "Sparkle Dust", "Dust", "Tiny glittering specks", "screen", 0.45,
		"background-color: transparent;",
		"Twinkling tiny dust sparkles.",
		{ count: 100, sizePx: [1, 2], speedSec: [4, 10], color: "#ffffff" }),
	ov("ov-du-006", "Drift Dust", "Dust", "Horizontal drifting dust", "screen", 0.4,
		"background-color: transparent;",
		"Dust drifting horizontally with wind.",
		{ count: 70, sizePx: [1, 3], speedSec: [3, 7], color: "#f5f5f5" }),
	ov("ov-du-007", "Macro Dust", "Dust", "Large soft bokeh dust", "screen", 0.4,
		"background: radial-gradient(circle at 30% 40%, rgba(255,255,255,.4), transparent 6%), radial-gradient(circle at 70% 70%, rgba(255,255,255,.4), transparent 6%);",
		"Out-of-focus large dust orbs."),
	ov("ov-du-008", "Pollen", "Dust", "Yellow pollen drift", "screen", 0.5,
		"background-color: transparent;",
		"Golden pollen drifting upward.",
		{ count: 120, sizePx: [2, 4], speedSec: [6, 12], color: "#facc15" }),
	ov("ov-du-009", "Cold Dust", "Dust", "Blue-tinted dust", "screen", 0.35,
		"background-color: transparent;",
		"Cool blue dust particles.",
		{ count: 80, sizePx: [1, 3], speedSec: [8, 16], color: "#bae6fd" }),
	ov("ov-du-010", "Burnt Dust", "Dust", "Sooty floating ash", "multiply", 0.5,
		"background-color: transparent;",
		"Dark gray ash drifting.",
		{ count: 60, sizePx: [1, 4], speedSec: [10, 20], color: "#374151" }),

	// ── Scratch (10)
	ov("ov-sc-001", "Film Scratches", "Scratch", "Vertical film scratches", "screen", 0.4,
		"background: repeating-linear-gradient(90deg, transparent 0 6px, rgba(255,255,255,.06) 6px 7px, transparent 7px 30px);",
		"Vertical white scratch lines like old film."),
	ov("ov-sc-002", "Heavy Scratches", "Scratch", "Dense damaged scratches", "screen", 0.5,
		"background: repeating-linear-gradient(91deg, transparent 0 4px, rgba(255,255,255,.1) 4px 5px, transparent 5px 12px);",
		"Heavy scratched film surface."),
	ov("ov-sc-003", "Hair Scratches", "Scratch", "Thin hair-like marks", "screen", 0.3,
		"background: repeating-linear-gradient(89deg, transparent 0 15px, rgba(255,255,255,.05) 15px 15.5px, transparent 15.5px 40px);",
		"Very thin hair-line scratches."),
	ov("ov-sc-004", "Vertical Burn", "Scratch", "Burnt streaks", "overlay", 0.45,
		"background: repeating-linear-gradient(90deg, transparent 0 30px, rgba(255,80,0,.08) 30px 31px, transparent 31px 80px);",
		"Orange-red vertical burn streaks."),
	ov("ov-sc-005", "Diagonal Scratches", "Scratch", "Slanted marks", "screen", 0.35,
		"background: repeating-linear-gradient(110deg, transparent 0 25px, rgba(255,255,255,.06) 25px 26px, transparent 26px 60px);",
		"Diagonally oriented scratches."),
	ov("ov-sc-006", "Cracked", "Scratch", "Cracked surface look", "overlay", 0.5,
		"background: conic-gradient(from 0deg at 50% 50%, transparent 0 30%, rgba(0,0,0,.15) 31%, transparent 32%);",
		"Crack-like shapes radiating from center."),
	ov("ov-sc-007", "Old Tape", "Scratch", "Tape-style horizontal scratch", "screen", 0.4,
		"background: repeating-linear-gradient(0deg, transparent 0 60px, rgba(255,255,255,.07) 60px 61px, transparent 61px 100px);",
		"Long horizontal scratches across."),
	ov("ov-sc-008", "Splice Mark", "Scratch", "Single splice line", "overlay", 0.6,
		"background: linear-gradient(180deg, transparent 48%, rgba(0,0,0,.6) 49%, rgba(0,0,0,.6) 51%, transparent 52%);",
		"Single horizontal splice mark across mid-frame."),
	ov("ov-sc-009", "Color Scratches", "Scratch", "RGB-split scratches", "screen", 0.4,
		"background: repeating-linear-gradient(90deg, transparent 0 10px, rgba(255,0,0,.06) 10px 11px, rgba(0,255,255,.06) 11px 12px, transparent 12px 30px);",
		"Red and cyan scratch pairs."),
	ov("ov-sc-010", "Erosion", "Scratch", "Worn corner damage", "multiply", 0.5,
		"background: radial-gradient(ellipse at 50% 100%, transparent 70%, rgba(0,0,0,.4) 100%);",
		"Damaged darker edges."),

	// ── FilmGrain (8)
	ov("ov-fg-001", "Fine Grain", "FilmGrain", "Subtle fine grain", "overlay", 0.25,
		"background-image: url(\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='120' height='120'><filter id='n'><feTurbulence baseFrequency='0.9'/></filter><rect width='100%' height='100%' filter='url(%23n)' opacity='0.5'/></svg>\");",
		"Almost imperceptible fine film grain."),
	ov("ov-fg-002", "Medium Grain", "FilmGrain", "Standard 35mm grain", "overlay", 0.4,
		"background-image: url(\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='180' height='180'><filter id='n'><feTurbulence baseFrequency='0.65'/></filter><rect width='100%' height='100%' filter='url(%23n)' opacity='0.6'/></svg>\");",
		"Standard analog film grain."),
	ov("ov-fg-003", "Heavy Grain", "FilmGrain", "16mm coarse grain", "overlay", 0.55,
		"background-image: url(\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='240' height='240'><filter id='n'><feTurbulence baseFrequency='0.45'/></filter><rect width='100%' height='100%' filter='url(%23n)' opacity='0.7'/></svg>\");",
		"Coarse visible film grain."),
	ov("ov-fg-004", "Color Grain", "FilmGrain", "Multi-hue grain", "screen", 0.3,
		"background-image: url(\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='200'><filter id='n'><feTurbulence baseFrequency='0.7' type='fractalNoise'/></filter><rect width='100%' height='100%' filter='url(%23n)' opacity='0.5'/></svg>\");",
		"Lightly colored film grain."),
	ov("ov-fg-005", "Push Process", "FilmGrain", "Pushed-grain look", "overlay", 0.5,
		"background-image: url(\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='220' height='220'><filter id='n'><feTurbulence baseFrequency='0.55' numOctaves='3'/></filter><rect width='100%' height='100%' filter='url(%23n)' opacity='0.75'/></svg>\");",
		"Increased contrast grain from pushed exposure."),
	ov("ov-fg-006", "Kodak 500T", "FilmGrain", "Tungsten film grain", "overlay", 0.4,
		"background-image: url(\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='200'><filter id='n'><feTurbulence baseFrequency='0.6'/></filter><rect width='100%' height='100%' filter='url(%23n)' opacity='0.6'/></svg>\");",
		"Warm-leaning grain texture."),
	ov("ov-fg-007", "Super8 Grain", "FilmGrain", "Heavy retro 8mm", "overlay", 0.6,
		"background-image: url(\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='160' height='160'><filter id='n'><feTurbulence baseFrequency='0.35'/></filter><rect width='100%' height='100%' filter='url(%23n)' opacity='0.85'/></svg>\");",
		"Big chunky Super-8 grain."),
	ov("ov-fg-008", "Mono Grain", "FilmGrain", "Pure black & white grain", "overlay", 0.5,
		"background-image: url(\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='200'><filter id='n'><feTurbulence baseFrequency='0.75'/><feColorMatrix values='0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 1 0'/></filter><rect width='100%' height='100%' filter='url(%23n)' opacity='0.7'/></svg>\");",
		"High-contrast B&W grain."),

	// ── LensFlare (12)
	ov("ov-lf-001", "Anamorphic Streak", "LensFlare", "Horizontal cyan streak", "screen", 0.7,
		"background: linear-gradient(90deg, transparent 30%, #6dd6ff 50%, transparent 70%);",
		"Long horizontal cyan anamorphic flare across center."),
	ov("ov-lf-002", "JJ Abrams", "LensFlare", "Cinematic blue streaks", "screen", 0.7,
		"background: linear-gradient(85deg, transparent 35%, #b1e3ff 50%, transparent 65%), radial-gradient(circle at 75% 25%, #fff 0%, transparent 8%);",
		"Bright cyan horizontal streak with bloom hotspot."),
	ov("ov-lf-003", "Sun Hotspot", "LensFlare", "Bright single hotspot", "screen", 0.85,
		"background: radial-gradient(circle at 50% 50%, #ffffff 0%, #ffe7a0 10%, transparent 30%);",
		"Single hot white-yellow spot with glow."),
	ov("ov-lf-004", "Hexagonal Flare", "LensFlare", "Hex bokeh chain", "screen", 0.5,
		"background: radial-gradient(circle at 20% 80%, rgba(255,200,120,.35) 0 12px, transparent 13px), radial-gradient(circle at 40% 60%, rgba(255,200,120,.35) 0 9px, transparent 10px), radial-gradient(circle at 60% 40%, rgba(255,200,120,.35) 0 6px, transparent 7px), radial-gradient(circle at 80% 20%, rgba(255,200,120,.35) 0 14px, transparent 15px);",
		"Diagonal chain of hex bokeh flares."),
	ov("ov-lf-005", "Veil Flare", "LensFlare", "Soft full-frame veil", "screen", 0.45,
		"background: radial-gradient(circle at 70% 20%, rgba(255,210,140,.55) 0%, transparent 60%);",
		"Soft warm veil across upper-right."),
	ov("ov-lf-006", "Greenish Flare", "LensFlare", "Green coating flare", "screen", 0.45,
		"background: radial-gradient(circle at 30% 70%, rgba(120,255,180,.4) 0%, transparent 30%);",
		"Cool green lens-coating flare."),
	ov("ov-lf-007", "Star Burst", "LensFlare", "Pointed star rays", "screen", 0.6,
		"background: conic-gradient(from 0deg at 50% 50%, transparent 0deg, #fff 10deg, transparent 20deg, transparent 80deg, #fff 90deg, transparent 100deg, transparent 170deg, #fff 180deg, transparent 190deg, transparent 260deg, #fff 270deg, transparent 280deg);",
		"Four-point star burst from center."),
	ov("ov-lf-008", "Magenta Coating", "LensFlare", "Magenta coating reflection", "screen", 0.5,
		"background: radial-gradient(circle at 25% 50%, rgba(255,80,200,.45) 0%, transparent 25%);",
		"Magenta coating reflection circle."),
	ov("ov-lf-009", "Lens Streak Pair", "LensFlare", "Two parallel streaks", "screen", 0.5,
		"background: linear-gradient(90deg, transparent 40%, rgba(255,255,255,.4) 50%, transparent 60%), linear-gradient(90deg, transparent 30%, rgba(255,255,255,.2) 70%, transparent 80%);",
		"Two parallel horizontal lens streaks."),
	ov("ov-lf-010", "Bokeh Chain", "LensFlare", "Soft circle bokeh trail", "screen", 0.55,
		"background: radial-gradient(circle at 25% 75%, rgba(255,235,180,.35) 0 22px, transparent 25px), radial-gradient(circle at 50% 50%, rgba(255,235,180,.35) 0 14px, transparent 16px), radial-gradient(circle at 75% 25%, rgba(255,235,180,.35) 0 28px, transparent 30px);",
		"Three warm bokeh circles diagonally."),
	ov("ov-lf-011", "Wide Anamorphic", "LensFlare", "Wide horizontal streak", "screen", 0.65,
		"background: linear-gradient(90deg, transparent 10%, #6dd6ff 50%, transparent 90%);",
		"Long full-width cyan streak."),
	ov("ov-lf-012", "Pin Lens", "LensFlare", "Tiny pinpoint flare", "screen", 0.8,
		"background: radial-gradient(circle at 50% 30%, #fff 0 4px, transparent 6px);",
		"Tiny pinpoint highlight upper-middle."),

	// ── Snow (8)
	ov("ov-sn-001", "Soft Snow", "Snow", "Gentle falling snow", "screen", 0.7,
		"background-color: transparent;",
		"Slow falling white snowflakes.",
		{ count: 80, sizePx: [3, 6], speedSec: [10, 20], color: "#ffffff" }),
	ov("ov-sn-002", "Blizzard", "Snow", "Dense fast snow", "screen", 0.8,
		"background-color: transparent;",
		"Heavy fast-moving snowfall.",
		{ count: 250, sizePx: [2, 5], speedSec: [3, 7], color: "#ffffff" }),
	ov("ov-sn-003", "Big Flakes", "Snow", "Large slow flakes", "screen", 0.75,
		"background-color: transparent;",
		"Large white flakes drifting slowly.",
		{ count: 40, sizePx: [8, 14], speedSec: [12, 24], color: "#ffffff" }),
	ov("ov-sn-004", "Sideways Snow", "Snow", "Wind-driven snow", "screen", 0.7,
		"background-color: transparent;",
		"Snowflakes blowing sideways.",
		{ count: 150, sizePx: [3, 6], speedSec: [4, 8], color: "#ffffff" }),
	ov("ov-sn-005", "Pixel Snow", "Snow", "Tiny pixel-style snow", "screen", 0.6,
		"background-color: transparent;",
		"Tiny crisp pixel snowflakes.",
		{ count: 200, sizePx: [1, 2], speedSec: [6, 12], color: "#ffffff" }),
	ov("ov-sn-006", "Christmas Snow", "Snow", "Festive twinkling snow", "screen", 0.7,
		"background-color: transparent;",
		"Twinkling holiday snowflakes.",
		{ count: 120, sizePx: [4, 8], speedSec: [10, 18], color: "#f0f9ff" }),
	ov("ov-sn-007", "Magic Snow", "Snow", "Sparkly snowfall", "screen", 0.65,
		"background-color: transparent;",
		"Snowflakes with magical glint.",
		{ count: 100, sizePx: [3, 7], speedSec: [8, 16], color: "#e0f2fe" }),
	ov("ov-sn-008", "Snow Accumulation", "Snow", "Snow building up on bottom", "screen", 0.8,
		"background: linear-gradient(0deg, rgba(255,255,255,.5) 0%, transparent 20%);",
		"Falling snow with bottom buildup.",
		{ count: 100, sizePx: [3, 5], speedSec: [8, 16], color: "#ffffff" }),

	// ── Rain (8)
	ov("ov-rn-001", "Light Rain", "Rain", "Gentle rain drops", "screen", 0.5,
		"background-color: transparent;",
		"Thin diagonal rain streaks.",
		{ count: 100, sizePx: [1, 2], speedSec: [1, 3], color: "rgba(180,210,255,.7)" }),
	ov("ov-rn-002", "Heavy Rain", "Rain", "Pouring rain", "screen", 0.65,
		"background-color: transparent;",
		"Dense rapid rain streaks.",
		{ count: 350, sizePx: [1, 2], speedSec: [0.5, 1.5], color: "rgba(200,220,255,.8)" }),
	ov("ov-rn-003", "Storm Rain", "Rain", "Wind-blown sideways rain", "screen", 0.6,
		"background-color: transparent;",
		"Steeply angled storm rain.",
		{ count: 250, sizePx: [2, 3], speedSec: [0.4, 1], color: "rgba(200,220,255,.85)" }),
	ov("ov-rn-004", "Rain on Glass", "Rain", "Static droplets", "screen", 0.5,
		"background: radial-gradient(circle at 22% 13%, rgba(255,255,255,.6) 0 3px, transparent 5px), radial-gradient(circle at 65% 40%, rgba(255,255,255,.6) 0 4px, transparent 6px), radial-gradient(circle at 30% 70%, rgba(255,255,255,.6) 0 2px, transparent 4px);",
		"Static water droplets clinging to glass."),
	ov("ov-rn-005", "Mist Rain", "Rain", "Very light misty rain", "screen", 0.3,
		"background-color: transparent;",
		"Almost invisible misty rain.",
		{ count: 80, sizePx: [1, 1], speedSec: [2, 5], color: "rgba(220,235,255,.5)" }),
	ov("ov-rn-006", "Rain Splash", "Rain", "Ground splash effect", "screen", 0.5,
		"background: radial-gradient(circle at 50% 100%, rgba(180,210,255,.3) 0%, transparent 30%);",
		"Splash haze near bottom."),
	ov("ov-rn-007", "Anime Rain", "Rain", "Stylized cel-shaded rain", "screen", 0.65,
		"background: repeating-linear-gradient(105deg, transparent 0 8px, rgba(220,240,255,.4) 8px 9px, transparent 9px 16px);",
		"Stylized diagonal rain lines like anime."),
	ov("ov-rn-008", "Acid Rain", "Rain", "Greenish rain", "screen", 0.55,
		"background-color: transparent;",
		"Sickly green-tinted rain streaks.",
		{ count: 200, sizePx: [1, 2], speedSec: [0.8, 1.5], color: "rgba(160,255,170,.6)" }),

	// ── Fog (8)
	ov("ov-fo-001", "Light Fog", "Fog", "Soft mist haze", "screen", 0.4,
		"background: radial-gradient(ellipse at 50% 80%, rgba(255,255,255,.4), transparent 60%);",
		"Low rolling mist near bottom."),
	ov("ov-fo-002", "Dense Fog", "Fog", "Heavy fog blanket", "screen", 0.7,
		"background: linear-gradient(0deg, rgba(255,255,255,.7) 0%, rgba(255,255,255,.2) 100%);",
		"Thick white fog covering scene."),
	ov("ov-fo-003", "Mountain Mist", "Fog", "Drifting bands of mist", "screen", 0.5,
		"background: linear-gradient(180deg, transparent, rgba(255,255,255,.4) 40%, transparent 80%);",
		"Horizontal band of mountain mist."),
	ov("ov-fo-004", "Eerie Fog", "Fog", "Greenish ground fog", "screen", 0.55,
		"background: linear-gradient(0deg, rgba(180,255,200,.5), transparent 50%);",
		"Sickly green ground fog."),
	ov("ov-fo-005", "Sunset Fog", "Fog", "Warm orange fog", "screen", 0.5,
		"background: linear-gradient(0deg, rgba(255,200,150,.5), transparent 60%);",
		"Warm orange-tinted fog."),
	ov("ov-fo-006", "Dream Fog", "Fog", "Soft purple haze", "screen", 0.4,
		"background: radial-gradient(ellipse at 50% 50%, rgba(220,200,255,.5), transparent 70%);",
		"Dreamy lavender haze."),
	ov("ov-fo-007", "Layered Fog", "Fog", "Multiple fog bands", "screen", 0.55,
		"background: linear-gradient(0deg, rgba(255,255,255,.4) 10%, transparent 30%, rgba(255,255,255,.3) 50%, transparent 70%);",
		"Multiple horizontal fog layers."),
	ov("ov-fo-008", "Cinematic Haze", "Fog", "Atmospheric depth haze", "screen", 0.35,
		"background: radial-gradient(ellipse at 50% 50%, transparent 30%, rgba(255,255,255,.3) 100%);",
		"Soft atmospheric haze around edges."),

	// ── Smoke (8)
	ov("ov-sm-001", "Cigarette Smoke", "Smoke", "Wisps of smoke", "screen", 0.4,
		"background: radial-gradient(ellipse at 20% 70%, rgba(255,255,255,.3), transparent 40%);",
		"Single column of wispy smoke."),
	ov("ov-sm-002", "Smoke Bomb", "Smoke", "Colorful smoke burst", "screen", 0.6,
		"background: radial-gradient(circle at 50% 60%, rgba(255,100,200,.5), transparent 50%);",
		"Pink smoke billow."),
	ov("ov-sm-003", "Industrial Smoke", "Smoke", "Dark factory smoke", "multiply", 0.5,
		"background: radial-gradient(ellipse at 30% 100%, rgba(60,60,60,.7), transparent 60%);",
		"Dark gray industrial smoke plume."),
	ov("ov-sm-004", "Fire Smoke", "Smoke", "Hot smoke from flame", "screen", 0.5,
		"background: radial-gradient(ellipse at 50% 100%, rgba(255,180,100,.4), rgba(80,40,20,.5) 30%, transparent 70%);",
		"Hot smoke rising from fire base."),
	ov("ov-sm-005", "Mystic Smoke", "Smoke", "Magical purple smoke", "screen", 0.5,
		"background: radial-gradient(ellipse at 60% 80%, rgba(180,100,255,.5), transparent 50%);",
		"Mystical purple smoke."),
	ov("ov-sm-006", "Steam", "Smoke", "White rising steam", "screen", 0.4,
		"background: radial-gradient(ellipse at 50% 80%, rgba(255,255,255,.5), transparent 50%);",
		"Soft white rising steam."),
	ov("ov-sm-007", "Color Smoke Red", "Smoke", "Red smoke billow", "screen", 0.55,
		"background: radial-gradient(circle at 50% 60%, rgba(255,80,60,.6), transparent 50%);",
		"Red smoke cloud."),
	ov("ov-sm-008", "Smoke Trail", "Smoke", "Diagonal smoke trail", "screen", 0.45,
		"background: linear-gradient(45deg, transparent 60%, rgba(200,200,200,.5) 75%, transparent 90%);",
		"Diagonal smoke streak."),

	// ── Glitter (8)
	ov("ov-gl-001", "Gold Glitter", "Glitter", "Gold sparkle field", "screen", 0.7,
		"background-color: transparent;",
		"Gold glitter particles twinkling.",
		{ count: 150, sizePx: [1, 3], speedSec: [2, 5], color: "#fcd34d" }),
	ov("ov-gl-002", "Silver Glitter", "Glitter", "Silver sparkle", "screen", 0.7,
		"background-color: transparent;",
		"Silver glitter particles.",
		{ count: 150, sizePx: [1, 3], speedSec: [2, 5], color: "#e5e7eb" }),
	ov("ov-gl-003", "Rainbow Glitter", "Glitter", "Multi-color glitter", "screen", 0.7,
		"background-color: transparent;",
		"Random hue glitter particles.",
		{ count: 180, sizePx: [1, 3], speedSec: [2, 4], color: "#ffffff" }),
	ov("ov-gl-004", "Pink Glitter", "Glitter", "Pink sparkle", "screen", 0.7,
		"background-color: transparent;",
		"Pink glitter sparks.",
		{ count: 150, sizePx: [1, 3], speedSec: [2, 5], color: "#f9a8d4" }),
	ov("ov-gl-005", "Cyber Glitter", "Glitter", "Neon cyan glitter", "screen", 0.8,
		"background-color: transparent;",
		"Cyan neon glitter particles.",
		{ count: 180, sizePx: [1, 4], speedSec: [1, 3], color: "#22d3ee" }),
	ov("ov-gl-006", "Falling Glitter", "Glitter", "Gravity-affected glitter", "screen", 0.75,
		"background-color: transparent;",
		"Glitter falling like snow.",
		{ count: 200, sizePx: [2, 4], speedSec: [4, 8], color: "#fcd34d" }),
	ov("ov-gl-007", "Burst Glitter", "Glitter", "Center-burst glitter", "screen", 0.8,
		"background-color: transparent;",
		"Glitter exploding from center.",
		{ count: 250, sizePx: [2, 4], speedSec: [0.8, 2], color: "#fde68a" }),
	ov("ov-gl-008", "Hologlitter", "Glitter", "Iridescent glitter", "screen", 0.7,
		"background-color: transparent;",
		"Iridescent shifting glitter.",
		{ count: 180, sizePx: [1, 3], speedSec: [2, 5], color: "#a78bfa" }),

	// ── Sparkle (8)
	ov("ov-sp-001", "Magic Sparkle", "Sparkle", "4-point stars", "screen", 0.7,
		"background: radial-gradient(circle at 20% 30%, #fff 0 1px, transparent 2px), radial-gradient(circle at 60% 70%, #fff 0 1.5px, transparent 3px), radial-gradient(circle at 80% 15%, #fff 0 1px, transparent 2px);",
		"Scattered tiny 4-point sparkle stars."),
	ov("ov-sp-002", "Diamond Sparkle", "Sparkle", "Crisp diamond sparks", "screen", 0.8,
		"background: radial-gradient(circle at 30% 50%, #fff 0 2px, transparent 4px), radial-gradient(circle at 70% 30%, #fff 0 3px, transparent 5px);",
		"Two bright diamond highlights."),
	ov("ov-sp-003", "Star Field", "Sparkle", "Dense star sparkles", "screen", 0.7,
		"background-color: transparent;",
		"Many tiny twinkling stars.",
		{ count: 120, sizePx: [1, 2], speedSec: [3, 6], color: "#ffffff" }),
	ov("ov-sp-004", "Glow Sparkle", "Sparkle", "Soft glowing sparks", "screen", 0.6,
		"background: radial-gradient(circle at 25% 40%, rgba(255,255,255,.6) 0 4px, transparent 12px), radial-gradient(circle at 75% 60%, rgba(255,255,255,.6) 0 5px, transparent 14px);",
		"Soft glowing sparkle points."),
	ov("ov-sp-005", "Pixie Dust", "Sparkle", "Trail of pixie sparks", "screen", 0.7,
		"background-color: transparent;",
		"Curving trail of pixie sparkles.",
		{ count: 100, sizePx: [1, 3], speedSec: [2, 4], color: "#fde047" }),
	ov("ov-sp-006", "Glitter Spark", "Sparkle", "Sharp sparkle pops", "screen", 0.8,
		"background-color: transparent;",
		"Sharp sparkle pops at random.",
		{ count: 80, sizePx: [2, 5], speedSec: [1, 2], color: "#ffffff" }),
	ov("ov-sp-007", "Snow Sparkle", "Sparkle", "Cool sparkle", "screen", 0.7,
		"background-color: transparent;",
		"Cool blue-white sparkles.",
		{ count: 100, sizePx: [1, 3], speedSec: [3, 7], color: "#e0f2fe" }),
	ov("ov-sp-008", "Heart Sparkle", "Sparkle", "Pink sparkle hearts", "screen", 0.7,
		"background-color: transparent;",
		"Pink heart-shaped sparkles.",
		{ count: 60, sizePx: [4, 8], speedSec: [3, 6], color: "#f472b6" }),

	// ── Bokeh (10)
	ov("ov-bk-001", "Warm Bokeh", "Bokeh", "Warm soft bokeh circles", "screen", 0.6,
		"background: radial-gradient(circle at 20% 30%, rgba(255,200,120,.5) 0 30px, transparent 60px), radial-gradient(circle at 70% 70%, rgba(255,200,120,.5) 0 40px, transparent 80px);",
		"Two large warm bokeh balls."),
	ov("ov-bk-002", "Cool Bokeh", "Bokeh", "Cool bokeh circles", "screen", 0.6,
		"background: radial-gradient(circle at 25% 75%, rgba(150,200,255,.5) 0 35px, transparent 70px), radial-gradient(circle at 75% 25%, rgba(150,200,255,.5) 0 45px, transparent 90px);",
		"Two cool blue bokeh balls."),
	ov("ov-bk-003", "Christmas Bokeh", "Bokeh", "Red green bokeh", "screen", 0.55,
		"background: radial-gradient(circle at 30% 30%, rgba(255,80,80,.5) 0 30px, transparent 60px), radial-gradient(circle at 70% 60%, rgba(80,255,120,.5) 0 35px, transparent 70px);",
		"Festive red and green bokeh."),
	ov("ov-bk-004", "Rainbow Bokeh", "Bokeh", "Multi-color bokeh", "screen", 0.6,
		"background: radial-gradient(circle at 20% 30%, rgba(255,100,150,.5) 0 30px, transparent 60px), radial-gradient(circle at 50% 70%, rgba(100,200,255,.5) 0 30px, transparent 60px), radial-gradient(circle at 80% 40%, rgba(180,100,255,.5) 0 30px, transparent 60px);",
		"Three differently-colored bokeh balls."),
	ov("ov-bk-005", "City Lights", "Bokeh", "Tiny city light bokeh", "screen", 0.7,
		"background: radial-gradient(circle at 15% 80%, rgba(255,200,80,.7) 0 6px, transparent 12px), radial-gradient(circle at 35% 70%, rgba(255,140,80,.6) 0 8px, transparent 14px), radial-gradient(circle at 60% 60%, rgba(255,200,80,.7) 0 6px, transparent 12px), radial-gradient(circle at 80% 75%, rgba(255,160,80,.7) 0 7px, transparent 14px);",
		"Small city light bokeh near bottom."),
	ov("ov-bk-006", "Gold Bokeh", "Bokeh", "Pure gold bokeh", "screen", 0.6,
		"background: radial-gradient(circle at 30% 40%, rgba(252,211,77,.55) 0 40px, transparent 80px), radial-gradient(circle at 70% 65%, rgba(252,211,77,.55) 0 30px, transparent 60px);",
		"Two warm gold bokeh circles."),
	ov("ov-bk-007", "Heart Bokeh", "Bokeh", "Heart-shape aperture bokeh", "screen", 0.55,
		"background: radial-gradient(circle at 30% 40%, rgba(255,150,180,.6) 0 30px, transparent 60px);",
		"Heart-shaped pink bokeh."),
	ov("ov-bk-008", "Mini Bokeh", "Bokeh", "Lots of tiny bokeh", "screen", 0.5,
		"background-color: transparent;",
		"Many small soft bokeh dots.",
		{ count: 60, sizePx: [6, 14], speedSec: [10, 18], color: "rgba(255,235,150,.6)" }),
	ov("ov-bk-009", "Studio Bokeh", "Bokeh", "Single big studio bokeh", "screen", 0.6,
		"background: radial-gradient(circle at 50% 50%, rgba(255,255,255,.4) 0 80px, transparent 160px);",
		"Single huge soft white bokeh."),
	ov("ov-bk-010", "Mixed Bokeh", "Bokeh", "Mixed warm-cool", "screen", 0.6,
		"background: radial-gradient(circle at 25% 35%, rgba(255,180,80,.5) 0 30px, transparent 60px), radial-gradient(circle at 65% 60%, rgba(100,180,255,.5) 0 40px, transparent 80px);",
		"Warm and cool bokeh combined."),

	// ── Halftone (8)
	ov("ov-ht-001", "Pop Halftone", "Halftone", "Comic book halftone", "multiply", 0.5,
		"background-image: radial-gradient(circle, #000 30%, transparent 35%); background-size: 6px 6px;",
		"Classic comic dotted halftone pattern."),
	ov("ov-ht-002", "Large Halftone", "Halftone", "Big dot halftone", "multiply", 0.5,
		"background-image: radial-gradient(circle, #000 25%, transparent 30%); background-size: 14px 14px;",
		"Large halftone dots."),
	ov("ov-ht-003", "CMYK Halftone", "Halftone", "4-color print halftone", "multiply", 0.4,
		"background: radial-gradient(circle, #06c 30%, transparent 35%) 0 0/8px 8px, radial-gradient(circle, #f0c 30%, transparent 35%) 2px 2px/8px 8px, radial-gradient(circle, #ee0 30%, transparent 35%) 4px 4px/8px 8px;",
		"CMYK rosette halftone print look."),
	ov("ov-ht-004", "Gradient Halftone", "Halftone", "Gradient density halftone", "multiply", 0.5,
		"background-image: radial-gradient(circle, #000 30%, transparent 35%); background-size: 8px 8px; mask: linear-gradient(180deg, #000, transparent);",
		"Halftone fading from top to bottom."),
	ov("ov-ht-005", "White Halftone", "Halftone", "Inverted white dots", "screen", 0.5,
		"background-image: radial-gradient(circle, #fff 30%, transparent 35%); background-size: 6px 6px;",
		"White halftone on transparent."),
	ov("ov-ht-006", "Stripe Halftone", "Halftone", "Striped halftone", "multiply", 0.5,
		"background-image: repeating-linear-gradient(45deg, #000 0 2px, transparent 2px 6px);",
		"Diagonal stripe halftone."),
	ov("ov-ht-007", "Square Halftone", "Halftone", "Square pixel halftone", "multiply", 0.5,
		"background: conic-gradient(#000 25%, transparent 0) 0 0/8px 8px;",
		"Square-grid halftone."),
	ov("ov-ht-008", "Radial Halftone", "Halftone", "Halftone radiating out", "multiply", 0.5,
		"background-image: radial-gradient(circle, #000 30%, transparent 35%); background-size: 6px 6px; mask: radial-gradient(circle at 50% 50%, transparent 20%, #000 70%);",
		"Halftone density increasing toward edges."),

	// ── Halo (8)
	ov("ov-ha-001", "Soft Halo", "Halo", "Soft glow ring", "screen", 0.55,
		"background: radial-gradient(circle at 50% 50%, transparent 30%, rgba(255,255,255,.4) 38%, transparent 50%);",
		"Soft white halo ring at center."),
	ov("ov-ha-002", "Angel Halo", "Halo", "Golden halo ring", "screen", 0.6,
		"background: radial-gradient(circle at 50% 30%, transparent 12%, rgba(255,220,120,.6) 16%, transparent 22%);",
		"Golden halo over head area."),
	ov("ov-ha-003", "Neon Halo", "Halo", "Neon glow ring", "screen", 0.7,
		"background: radial-gradient(circle at 50% 50%, transparent 30%, rgba(255,80,200,.7) 35%, transparent 45%);",
		"Hot pink neon halo."),
	ov("ov-ha-004", "Eclipse", "Halo", "Solar eclipse halo", "screen", 0.7,
		"background: radial-gradient(circle at 50% 50%, #000 25%, rgba(255,200,80,.7) 30%, transparent 50%);",
		"Black disc with corona ring."),
	ov("ov-ha-005", "Lunar Halo", "Halo", "Cool blue moon halo", "screen", 0.5,
		"background: radial-gradient(circle at 50% 40%, transparent 25%, rgba(160,200,255,.5) 30%, transparent 40%);",
		"Cool blue moon halo."),
	ov("ov-ha-006", "Saint Halo", "Halo", "Religious style halo", "screen", 0.65,
		"background: radial-gradient(circle at 50% 30%, transparent 14%, rgba(255,235,150,.6) 18%, transparent 26%);",
		"Religious figure halo glow."),
	ov("ov-ha-007", "Tech Halo", "Halo", "Sci-fi tech ring", "screen", 0.7,
		"background: radial-gradient(circle at 50% 50%, transparent 28%, rgba(0,200,255,.7) 32%, transparent 38%);",
		"Cyan tech-style halo ring."),
	ov("ov-ha-008", "Double Halo", "Halo", "Two concentric halos", "screen", 0.55,
		"background: radial-gradient(circle at 50% 50%, transparent 25%, rgba(255,255,255,.4) 30%, transparent 35%, transparent 45%, rgba(255,255,255,.3) 50%, transparent 55%);",
		"Two concentric halo rings."),

	// ── Vignette (8)
	ov("ov-vg-001", "Soft Vignette", "Vignette", "Gentle dark edges", "multiply", 0.6,
		"background: radial-gradient(ellipse at 50% 50%, transparent 50%, rgba(0,0,0,.6) 100%);",
		"Soft dark vignette around edges."),
	ov("ov-vg-002", "Heavy Vignette", "Vignette", "Strong dark edges", "multiply", 0.85,
		"background: radial-gradient(ellipse at 50% 50%, transparent 30%, rgba(0,0,0,.9) 100%);",
		"Strong black vignette."),
	ov("ov-vg-003", "White Vignette", "Vignette", "High-key white edges", "screen", 0.6,
		"background: radial-gradient(ellipse at 50% 50%, transparent 50%, rgba(255,255,255,.6) 100%);",
		"White soft vignette."),
	ov("ov-vg-004", "Color Vignette", "Vignette", "Warm orange edges", "overlay", 0.5,
		"background: radial-gradient(ellipse at 50% 50%, transparent 50%, rgba(255,120,50,.6) 100%);",
		"Warm orange vignette."),
	ov("ov-vg-005", "Square Vignette", "Vignette", "Hard rectangular vignette", "multiply", 0.7,
		"background: linear-gradient(90deg, rgba(0,0,0,.7), transparent 15%, transparent 85%, rgba(0,0,0,.7)), linear-gradient(0deg, rgba(0,0,0,.7), transparent 15%, transparent 85%, rgba(0,0,0,.7));",
		"Hard rectangular black vignette."),
	ov("ov-vg-006", "Top Bottom Bars", "Vignette", "Cinematic letterbox", "normal", 1,
		"background: linear-gradient(180deg, #000 0 12%, transparent 12% 88%, #000 88% 100%);",
		"Cinematic black bars top and bottom."),
	ov("ov-vg-007", "Asymmetric Vignette", "Vignette", "Off-center vignette", "multiply", 0.7,
		"background: radial-gradient(ellipse at 30% 30%, transparent 40%, rgba(0,0,0,.8) 100%);",
		"Off-center dark vignette."),
	ov("ov-vg-008", "Burnt Edges", "Vignette", "Brown burnt vignette", "multiply", 0.7,
		"background: radial-gradient(ellipse at 50% 50%, transparent 40%, rgba(60,30,10,.85) 100%);",
		"Burnt-edge sepia vignette."),

	// ── Glitch (8)
	ov("ov-gx-001", "RGB Split", "Glitch", "Chromatic aberration shift", "screen", 0.6,
		"background: linear-gradient(90deg, rgba(255,0,0,.3) 0 5px, transparent 5px), linear-gradient(90deg, transparent 0 calc(100% - 5px), rgba(0,255,255,.3) calc(100% - 5px));",
		"Red and cyan channel offset on edges."),
	ov("ov-gx-002", "Scan Glitch", "Glitch", "Scrolling scan glitch", "overlay", 0.5,
		"background: repeating-linear-gradient(0deg, transparent 0 30px, rgba(255,255,255,.05) 30px 32px, transparent 32px 80px);",
		"Periodic scan glitch lines."),
	ov("ov-gx-003", "Block Glitch", "Glitch", "Pixel block displacement", "normal", 0.7,
		"background: repeating-linear-gradient(0deg, transparent 0 50px, rgba(255,0,80,.2) 50px 65px, transparent 65px 120px);",
		"Horizontal pink block glitches."),
	ov("ov-gx-004", "Datamosh", "Glitch", "Macroblock smear", "overlay", 0.65,
		"background: repeating-linear-gradient(45deg, transparent 0 16px, rgba(0,255,200,.15) 16px 18px, transparent 18px 40px);",
		"Diagonal data-moshed pixel smears."),
	ov("ov-gx-005", "Static Noise", "Glitch", "TV static glitch", "screen", 0.4,
		"background-image: url(\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='160' height='160'><filter id='n'><feTurbulence baseFrequency='2'/></filter><rect width='100%' height='100%' filter='url(%23n)'/></svg>\");",
		"High-frequency analog noise."),
	ov("ov-gx-006", "Bar Glitch", "Glitch", "Color bar interrupt", "overlay", 0.7,
		"background: linear-gradient(180deg, transparent 30%, rgba(255,0,150,.5) 31%, rgba(0,255,180,.5) 33%, transparent 35%);",
		"Single color glitch bar mid-frame."),
	ov("ov-gx-007", "CRT Roll", "Glitch", "Vertical roll bar", "overlay", 0.5,
		"background: linear-gradient(0deg, transparent 70%, rgba(255,255,255,.15) 75%, transparent 80%);",
		"Rolling vertical hold bar."),
	ov("ov-gx-008", "Pixel Sort", "Glitch", "Vertical pixel sort streaks", "normal", 0.8,
		"background: repeating-linear-gradient(180deg, transparent 0 60px, rgba(200,50,200,.4) 60px 120px, transparent 120px 200px);",
		"Vertical pixel-sort streaks."),

	// ── Paper (8)
	ov("ov-pa-001", "Notebook Paper", "Paper", "Lined notebook paper", "multiply", 0.4,
		"background-color: #fffdf7; background-image: repeating-linear-gradient(0deg, transparent 0 23px, #b4d6ff 23px 24px);",
		"White paper with blue ruled lines."),
	ov("ov-pa-002", "Kraft Paper", "Paper", "Brown kraft texture", "multiply", 0.55,
		"background-color: #c9a978;",
		"Solid brown kraft paper."),
	ov("ov-pa-003", "Crumpled Paper", "Paper", "Crumpled white", "multiply", 0.5,
		"background: url(\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='200'><filter id='n'><feTurbulence baseFrequency='0.03' numOctaves='4'/></filter><rect width='100%' height='100%' filter='url(%23n)' opacity='0.4'/></svg>\") #fff;",
		"Soft creased crumpled paper texture."),
	ov("ov-pa-004", "Old Parchment", "Paper", "Yellowed old parchment", "multiply", 0.6,
		"background: radial-gradient(ellipse at 50% 50%, #f3e2b6 30%, #c2a460 100%);",
		"Aged yellowed parchment."),
	ov("ov-pa-005", "Graph Paper", "Paper", "Engineering graph grid", "multiply", 0.4,
		"background-color: #fff; background-image: linear-gradient(0deg, #aac6e8 1px, transparent 1px), linear-gradient(90deg, #aac6e8 1px, transparent 1px); background-size: 20px 20px;",
		"White paper with blue grid."),
	ov("ov-pa-006", "Newspaper", "Paper", "Newsprint texture", "multiply", 0.5,
		"background-color: #e8e2d0;",
		"Off-white newsprint paper."),
	ov("ov-pa-007", "Cardboard", "Paper", "Corrugated cardboard", "multiply", 0.6,
		"background-color: #a87854; background-image: repeating-linear-gradient(0deg, transparent 0 4px, rgba(0,0,0,.08) 4px 5px);",
		"Brown corrugated cardboard."),
	ov("ov-pa-008", "Watercolor Paper", "Paper", "Textured watercolor paper", "multiply", 0.4,
		"background: url(\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='200'><filter id='n'><feTurbulence baseFrequency='0.6'/></filter><rect width='100%' height='100%' filter='url(%23n)' opacity='0.2'/></svg>\") #fafaf3;",
		"Subtle textured watercolor paper."),

	// ── Neon (8 — first 2 from source; remaining 6 fill the truncated slot)
	ov("ov-ne-001", "Pink Neon Outline", "Neon", "Pink neon edge glow", "screen", 0.9,
		"box-shadow: inset 0 0 30px 5px #ff00aa, inset 0 0 60px 15px #ff00aa; background: transparent;",
		"Pink neon edge glow around the frame."),
	ov("ov-ne-002", "Cyan Neon Outline", "Neon", "Cyan edge glow", "screen", 0.9,
		"box-shadow: inset 0 0 30px 5px #00e5ff, inset 0 0 60px 15px #00e5ff; background: transparent;",
		"Cyan neon edge glow."),
	ov("ov-ne-003", "Purple Neon Outline", "Neon", "Purple edge glow", "screen", 0.9,
		"box-shadow: inset 0 0 30px 5px #a855f7, inset 0 0 60px 15px #a855f7; background: transparent;",
		"Purple neon edge glow."),
	ov("ov-ne-004", "Green Neon Outline", "Neon", "Green edge glow", "screen", 0.9,
		"box-shadow: inset 0 0 30px 5px #22c55e, inset 0 0 60px 15px #22c55e; background: transparent;",
		"Green neon edge glow."),
	ov("ov-ne-005", "Yellow Neon Outline", "Neon", "Yellow edge glow", "screen", 0.9,
		"box-shadow: inset 0 0 30px 5px #facc15, inset 0 0 60px 15px #facc15; background: transparent;",
		"Yellow neon edge glow."),
	ov("ov-ne-006", "Orange Neon Outline", "Neon", "Orange edge glow", "screen", 0.9,
		"box-shadow: inset 0 0 30px 5px #fb923c, inset 0 0 60px 15px #fb923c; background: transparent;",
		"Orange neon edge glow."),
	ov("ov-ne-007", "Red Neon Outline", "Neon", "Red edge glow", "screen", 0.9,
		"box-shadow: inset 0 0 30px 5px #ef4444, inset 0 0 60px 15px #ef4444; background: transparent;",
		"Red neon edge glow."),
	ov("ov-ne-008", "White Neon Outline", "Neon", "White edge glow", "screen", 0.9,
		"box-shadow: inset 0 0 30px 5px #ffffff, inset 0 0 60px 15px #ffffff; background: transparent;",
		"White neon edge glow."),
];
