// Stickers — 185 entries (Emotions 30, Animals 25, Food 25, Tech 15, Travel 15,
// Sports 15, Music 15, Weather 15, Celebration 15, Gaming 15).
// Extracted verbatim from docs/asset-library-research.ts.txt (stickers section).
// No external imports; emoji glyphs render as-is.

import type { Sticker, StickerSubcategory } from "./types";

const emojiSticker = (
	id: string,
	name: string,
	sub: StickerSubcategory,
	char: string,
	desc: string,
): Sticker => ({
	id,
	name,
	description: desc,
	category: "sticker",
	subcategory: sub,
	visual: `Flat ${char} emoji rendered at high resolution on transparent background.`,
	asset: { kind: "emoji", char },
});

export const stickers: Sticker[] = [
	// ── Emotions (30)
	emojiSticker(
		"st-emo-001",
		"Grinning",
		"Emotions",
		"😀",
		"Bright cheerful smile",
	),
	emojiSticker(
		"st-emo-002",
		"Joy Tears",
		"Emotions",
		"😂",
		"Laughing crying face",
	),
	emojiSticker(
		"st-emo-003",
		"Heart Eyes",
		"Emotions",
		"😍",
		"In-love expression",
	),
	emojiSticker("st-emo-004", "Wink", "Emotions", "😉", "Playful wink"),
	emojiSticker("st-emo-005", "Cool", "Emotions", "😎", "Sunglasses face"),
	emojiSticker("st-emo-006", "Star Struck", "Emotions", "🤩", "Stars in eyes"),
	emojiSticker("st-emo-007", "Thinking", "Emotions", "🤔", "Thinking pose"),
	emojiSticker("st-emo-008", "Smirk", "Emotions", "😏", "Sly smile"),
	emojiSticker("st-emo-009", "Sad", "Emotions", "😢", "Single tear"),
	emojiSticker("st-emo-010", "Sob", "Emotions", "😭", "Loud crying"),
	emojiSticker("st-emo-011", "Angry", "Emotions", "😠", "Angry red face"),
	emojiSticker("st-emo-012", "Rage", "Emotions", "🤬", "Cursing symbols"),
	emojiSticker("st-emo-013", "Shocked", "Emotions", "😱", "Scream face"),
	emojiSticker("st-emo-014", "Mind Blown", "Emotions", "🤯", "Exploding head"),
	emojiSticker("st-emo-015", "Hug", "Emotions", "🤗", "Open arms hug"),
	emojiSticker("st-emo-016", "Pray", "Emotions", "🙏", "Folded hands"),
	emojiSticker("st-emo-017", "Clap", "Emotions", "👏", "Applause hands"),
	emojiSticker("st-emo-018", "Thumbs Up", "Emotions", "👍", "Approval gesture"),
	emojiSticker(
		"st-emo-019",
		"Thumbs Down",
		"Emotions",
		"👎",
		"Disapproval gesture",
	),
	emojiSticker("st-emo-020", "OK", "Emotions", "👌", "OK hand"),
	emojiSticker("st-emo-021", "Peace", "Emotions", "✌️", "Two-finger peace"),
	emojiSticker("st-emo-022", "Rock On", "Emotions", "🤘", "Rock horns"),
	emojiSticker("st-emo-023", "Wave", "Emotions", "👋", "Hello wave"),
	emojiSticker("st-emo-024", "Heart", "Emotions", "❤️", "Red heart"),
	emojiSticker("st-emo-025", "Broken Heart", "Emotions", "💔", "Cracked heart"),
	emojiSticker(
		"st-emo-026",
		"Sparkle Heart",
		"Emotions",
		"💖",
		"Sparkly pink heart",
	),
	emojiSticker("st-emo-027", "Fire", "Emotions", "🔥", "Lit fire icon"),
	emojiSticker("st-emo-028", "Hundred", "Emotions", "💯", "Bold 100 symbol"),
	emojiSticker("st-emo-029", "Sleepy", "Emotions", "😴", "Sleeping ZZZ face"),
	emojiSticker("st-emo-030", "Sick", "Emotions", "🤒", "Thermometer face"),

	// ── Animals (25)
	emojiSticker("st-ani-001", "Dog", "Animals", "🐶", "Puppy face"),
	emojiSticker("st-ani-002", "Cat", "Animals", "🐱", "Kitten face"),
	emojiSticker("st-ani-003", "Fox", "Animals", "🦊", "Orange fox face"),
	emojiSticker("st-ani-004", "Bear", "Animals", "🐻", "Brown bear"),
	emojiSticker("st-ani-005", "Panda", "Animals", "🐼", "Panda face"),
	emojiSticker("st-ani-006", "Lion", "Animals", "🦁", "Lion mane"),
	emojiSticker("st-ani-007", "Tiger", "Animals", "🐯", "Tiger face"),
	emojiSticker("st-ani-008", "Koala", "Animals", "🐨", "Koala face"),
	emojiSticker("st-ani-009", "Frog", "Animals", "🐸", "Green frog"),
	emojiSticker("st-ani-010", "Owl", "Animals", "🦉", "Wise owl"),
	emojiSticker("st-ani-011", "Unicorn", "Animals", "🦄", "Pastel unicorn"),
	emojiSticker("st-ani-012", "Dragon", "Animals", "🐉", "Long dragon"),
	emojiSticker("st-ani-013", "Butterfly", "Animals", "🦋", "Blue butterfly"),
	emojiSticker("st-ani-014", "Bee", "Animals", "🐝", "Honey bee"),
	emojiSticker("st-ani-015", "Octopus", "Animals", "🐙", "Pink octopus"),
	emojiSticker("st-ani-016", "Whale", "Animals", "🐳", "Spouting whale"),
	emojiSticker("st-ani-017", "Penguin", "Animals", "🐧", "Standing penguin"),
	emojiSticker("st-ani-018", "Horse", "Animals", "🐴", "Horse head"),
	emojiSticker("st-ani-019", "Pig", "Animals", "🐷", "Pink pig"),
	emojiSticker("st-ani-020", "Cow", "Animals", "🐮", "Cow face"),
	emojiSticker("st-ani-021", "Monkey", "Animals", "🐵", "Monkey face"),
	emojiSticker("st-ani-022", "Rabbit", "Animals", "🐰", "White rabbit"),
	emojiSticker("st-ani-023", "Hamster", "Animals", "🐹", "Hamster face"),
	emojiSticker("st-ani-024", "Hedgehog", "Animals", "🦔", "Spiky hedgehog"),
	emojiSticker("st-ani-025", "Dinosaur", "Animals", "🦖", "T-Rex silhouette"),

	// ── Food (25)
	emojiSticker("st-foo-001", "Pizza", "Food", "🍕", "Pizza slice"),
	emojiSticker("st-foo-002", "Burger", "Food", "🍔", "Cheeseburger"),
	emojiSticker("st-foo-003", "Fries", "Food", "🍟", "Fry box"),
	emojiSticker("st-foo-004", "Hot Dog", "Food", "🌭", "Hot dog"),
	emojiSticker("st-foo-005", "Taco", "Food", "🌮", "Folded taco"),
	emojiSticker("st-foo-006", "Sushi", "Food", "🍣", "Salmon nigiri"),
	emojiSticker("st-foo-007", "Ramen", "Food", "🍜", "Noodle bowl"),
	emojiSticker("st-foo-008", "Donut", "Food", "🍩", "Pink donut"),
	emojiSticker("st-foo-009", "Cake", "Food", "🍰", "Strawberry cake"),
	emojiSticker("st-foo-010", "Ice Cream", "Food", "🍦", "Soft serve"),
	emojiSticker("st-foo-011", "Cookie", "Food", "🍪", "Chip cookie"),
	emojiSticker("st-foo-012", "Chocolate", "Food", "🍫", "Chocolate bar"),
	emojiSticker("st-foo-013", "Coffee", "Food", "☕", "Coffee mug"),
	emojiSticker("st-foo-014", "Tea", "Food", "🍵", "Green tea cup"),
	emojiSticker("st-foo-015", "Cocktail", "Food", "🍹", "Tropical drink"),
	emojiSticker("st-foo-016", "Beer", "Food", "🍺", "Beer mug"),
	emojiSticker("st-foo-017", "Wine", "Food", "🍷", "Red wine glass"),
	emojiSticker("st-foo-018", "Apple", "Food", "🍎", "Red apple"),
	emojiSticker("st-foo-019", "Banana", "Food", "🍌", "Yellow banana"),
	emojiSticker("st-foo-020", "Strawberry", "Food", "🍓", "Strawberry"),
	emojiSticker("st-foo-021", "Avocado", "Food", "🥑", "Halved avocado"),
	emojiSticker("st-foo-022", "Watermelon", "Food", "🍉", "Watermelon slice"),
	emojiSticker("st-foo-023", "Grapes", "Food", "🍇", "Purple grapes"),
	emojiSticker("st-foo-024", "Pineapple", "Food", "🍍", "Pineapple"),
	emojiSticker("st-foo-025", "Popcorn", "Food", "🍿", "Popcorn tub"),

	// ── Tech (15) — SVG mix
	emojiSticker("st-tec-001", "Laptop", "Tech", "💻", "Laptop computer"),
	emojiSticker("st-tec-002", "Phone", "Tech", "📱", "Smartphone"),
	emojiSticker("st-tec-003", "Camera", "Tech", "📷", "Compact camera"),
	emojiSticker("st-tec-004", "Headphones", "Tech", "🎧", "Over-ear headphones"),
	emojiSticker("st-tec-005", "Battery", "Tech", "🔋", "Charged battery"),
	emojiSticker("st-tec-006", "Plug", "Tech", "🔌", "Electric plug"),
	emojiSticker("st-tec-007", "Bulb", "Tech", "💡", "Light bulb"),
	emojiSticker("st-tec-008", "Disk", "Tech", "💿", "CD disc"),
	emojiSticker("st-tec-009", "Keyboard", "Tech", "⌨️", "Keyboard"),
	emojiSticker("st-tec-010", "Robot", "Tech", "🤖", "Robot face"),
	{
		id: "st-tec-011",
		name: "WiFi",
		description: "Wifi signal arcs",
		category: "sticker",
		subcategory: "Tech",
		visual: "Three concentric arcs and a dot representing wifi.",
		asset: {
			kind: "svg",
			viewBox: "0 0 24 24",
			fill: "#3b82f6",
			paths: [
				"M12 18a2 2 0 1 1 0 4 2 2 0 0 1 0-4z",
				"M5 11.5a10 10 0 0 1 14 0l-2 2a7 7 0 0 0-10 0l-2-2z",
				"M1 7.5a16 16 0 0 1 22 0l-2 2a13 13 0 0 0-18 0l-2-2z",
			],
		},
	},
	{
		id: "st-tec-012",
		name: "Cloud Sync",
		description: "Cloud with refresh arrow",
		category: "sticker",
		subcategory: "Tech",
		visual: "A puffy cloud with a circular sync arrow at its base.",
		asset: {
			kind: "svg",
			viewBox: "0 0 24 24",
			fill: "#0ea5e9",
			paths: [
				"M7 18a5 5 0 1 1 .4-9.98A6 6 0 0 1 19 10a4 4 0 0 1-1 7.87V18H7z",
				"M12 14l2 2-2 2v-1.2a3 3 0 1 1 3-3h-1.2A1.8 1.8 0 1 0 12 15.2V14z",
			],
		},
	},
	{
		id: "st-tec-013",
		name: "Code Brackets",
		description: "Angled brackets",
		category: "sticker",
		subcategory: "Tech",
		visual: "Two angled brackets <> in monospace style.",
		asset: {
			kind: "svg",
			viewBox: "0 0 32 24",
			fill: "#a78bfa",
			paths: [
				"M9 4 1 12l8 8 2-2-6-6 6-6-2-2z",
				"M23 4l8 8-8 8-2-2 6-6-6-6 2-2z",
			],
		},
	},
	{
		id: "st-tec-014",
		name: "Rocket",
		description: "Stylized rocket launch",
		category: "sticker",
		subcategory: "Tech",
		visual: "Vertical rocket with flame and stars.",
		asset: {
			kind: "svg",
			viewBox: "0 0 24 24",
			fill: "#ef4444",
			paths: [
				"M12 2c3 3 5 7 5 11l-3 3h-4l-3-3c0-4 2-8 5-11z",
				"M10 18l-2 4 4-2 4 2-2-4z",
			],
		},
	},
	{
		id: "st-tec-015",
		name: "Bug",
		description: "Stylized debugging bug",
		category: "sticker",
		subcategory: "Tech",
		visual: "Round bug body with six legs and antennae.",
		asset: {
			kind: "svg",
			viewBox: "0 0 24 24",
			fill: "#22c55e",
			paths: [
				"M12 6a4 4 0 0 1 4 4v4a4 4 0 0 1-8 0v-4a4 4 0 0 1 4-4z",
				"M2 12h4M18 12h4M3 7l3 2M21 7l-3 2M3 17l3-2M21 17l-3-2",
			],
		},
	},

	// ── Travel (15)
	emojiSticker("st-trv-001", "Plane", "Travel", "✈️", "Airplane"),
	emojiSticker("st-trv-002", "Rocket", "Travel", "🚀", "Rocket launch"),
	emojiSticker("st-trv-003", "Car", "Travel", "🚗", "Red car"),
	emojiSticker("st-trv-004", "Bus", "Travel", "🚌", "School bus"),
	emojiSticker("st-trv-005", "Train", "Travel", "🚆", "High-speed train"),
	emojiSticker("st-trv-006", "Ship", "Travel", "🚢", "Cruise ship"),
	emojiSticker("st-trv-007", "Bike", "Travel", "🚲", "Bicycle"),
	emojiSticker("st-trv-008", "Scooter", "Travel", "🛴", "Kick scooter"),
	emojiSticker("st-trv-009", "Sailboat", "Travel", "⛵", "Sailboat"),
	emojiSticker("st-trv-010", "Map", "Travel", "🗺️", "World map"),
	emojiSticker("st-trv-011", "Compass", "Travel", "🧭", "Compass"),
	emojiSticker("st-trv-012", "Suitcase", "Travel", "🧳", "Travel suitcase"),
	emojiSticker(
		"st-trv-013",
		"Camera Travel",
		"Travel",
		"📸",
		"Camera with flash",
	),
	emojiSticker("st-trv-014", "Beach", "Travel", "🏖️", "Beach with umbrella"),
	emojiSticker("st-trv-015", "Mountain", "Travel", "🏔️", "Snowy peak"),

	// ── Sports (15)
	emojiSticker("st-spo-001", "Soccer", "Sports", "⚽", "Soccer ball"),
	emojiSticker("st-spo-002", "Basketball", "Sports", "🏀", "Orange ball"),
	emojiSticker("st-spo-003", "Football", "Sports", "🏈", "American football"),
	emojiSticker("st-spo-004", "Baseball", "Sports", "⚾", "Baseball"),
	emojiSticker("st-spo-005", "Tennis", "Sports", "🎾", "Tennis ball"),
	emojiSticker("st-spo-006", "Volleyball", "Sports", "🏐", "Volleyball"),
	emojiSticker("st-spo-007", "Rugby", "Sports", "🏉", "Rugby ball"),
	emojiSticker("st-spo-008", "Eight Ball", "Sports", "🎱", "Pool ball"),
	emojiSticker("st-spo-009", "Bowling", "Sports", "🎳", "Bowling pins"),
	emojiSticker("st-spo-010", "Boxing", "Sports", "🥊", "Boxing glove"),
	emojiSticker("st-spo-011", "Skis", "Sports", "🎿", "Ski pair"),
	emojiSticker("st-spo-012", "Snowboard", "Sports", "🏂", "Snowboarder"),
	emojiSticker("st-spo-013", "Surfer", "Sports", "🏄", "Surfing person"),
	emojiSticker("st-spo-014", "Trophy", "Sports", "🏆", "Gold trophy"),
	emojiSticker("st-spo-015", "Medal", "Sports", "🥇", "Gold medal"),

	// ── Music (15)
	emojiSticker("st-mus-001", "Note", "Music", "🎵", "Single music note"),
	emojiSticker("st-mus-002", "Notes", "Music", "🎶", "Multiple notes"),
	emojiSticker("st-mus-003", "Mic", "Music", "🎤", "Studio mic"),
	emojiSticker("st-mus-004", "Guitar", "Music", "🎸", "Electric guitar"),
	emojiSticker("st-mus-005", "Piano", "Music", "🎹", "Piano keys"),
	emojiSticker("st-mus-006", "Drum", "Music", "🥁", "Snare drum"),
	emojiSticker("st-mus-007", "Trumpet", "Music", "🎺", "Brass trumpet"),
	emojiSticker("st-mus-008", "Sax", "Music", "🎷", "Saxophone"),
	emojiSticker("st-mus-009", "Violin", "Music", "🎻", "Violin"),
	emojiSticker("st-mus-010", "Headphones", "Music", "🎧", "DJ headphones"),
	emojiSticker("st-mus-011", "Vinyl", "Music", "💽", "Minidisc"),
	emojiSticker("st-mus-012", "Radio", "Music", "📻", "Retro radio"),
	emojiSticker("st-mus-013", "Speaker", "Music", "🔊", "Loud speaker"),
	emojiSticker("st-mus-014", "Mute", "Music", "🔇", "Muted speaker"),
	emojiSticker("st-mus-015", "Bell", "Music", "🔔", "Notification bell"),

	// ── Weather (15)
	emojiSticker("st-wth-001", "Sun", "Weather", "☀️", "Bright sun"),
	emojiSticker("st-wth-002", "Cloud", "Weather", "☁️", "Single cloud"),
	emojiSticker("st-wth-003", "Partly", "Weather", "⛅", "Sun behind cloud"),
	emojiSticker("st-wth-004", "Rain", "Weather", "🌧️", "Rain cloud"),
	emojiSticker("st-wth-005", "Snow", "Weather", "🌨️", "Snow cloud"),
	emojiSticker("st-wth-006", "Thunder", "Weather", "⛈️", "Storm cloud"),
	emojiSticker("st-wth-007", "Lightning", "Weather", "⚡", "Lightning bolt"),
	emojiSticker("st-wth-008", "Rainbow", "Weather", "🌈", "Color rainbow"),
	emojiSticker("st-wth-009", "Tornado", "Weather", "🌪️", "Spinning tornado"),
	emojiSticker("st-wth-010", "Fog", "Weather", "🌫️", "Fog band"),
	emojiSticker("st-wth-011", "Snowflake", "Weather", "❄️", "Snowflake"),
	emojiSticker("st-wth-012", "Snowman", "Weather", "⛄", "Cute snowman"),
	emojiSticker("st-wth-013", "Umbrella", "Weather", "☔", "Rainy umbrella"),
	emojiSticker("st-wth-014", "Moon", "Weather", "🌙", "Crescent moon"),
	emojiSticker("st-wth-015", "Star", "Weather", "⭐", "Single star"),

	// ── Celebration (15)
	emojiSticker("st-cel-001", "Party", "Celebration", "🎉", "Party popper"),
	emojiSticker("st-cel-002", "Confetti", "Celebration", "🎊", "Confetti ball"),
	emojiSticker("st-cel-003", "Balloon", "Celebration", "🎈", "Red balloon"),
	emojiSticker("st-cel-004", "Gift", "Celebration", "🎁", "Wrapped gift"),
	emojiSticker("st-cel-005", "Cake", "Celebration", "🎂", "Birthday cake"),
	emojiSticker("st-cel-006", "Candle", "Celebration", "🕯️", "Lit candle"),
	emojiSticker(
		"st-cel-007",
		"Fireworks",
		"Celebration",
		"🎆",
		"Fireworks burst",
	),
	emojiSticker("st-cel-008", "Sparkler", "Celebration", "🎇", "Sparkler"),
	emojiSticker(
		"st-cel-009",
		"Champagne",
		"Celebration",
		"🍾",
		"Champagne bottle",
	),
	emojiSticker("st-cel-010", "Cheers", "Celebration", "🥂", "Toasting glasses"),
	emojiSticker("st-cel-011", "Crown", "Celebration", "👑", "Gold crown"),
	emojiSticker(
		"st-cel-012",
		"Star Sparkle",
		"Celebration",
		"✨",
		"Magic sparkles",
	),
	emojiSticker("st-cel-013", "Ribbon", "Celebration", "🎀", "Pink ribbon"),
	emojiSticker("st-cel-014", "Roses", "Celebration", "🌹", "Red rose"),
	emojiSticker("st-cel-015", "Bouquet", "Celebration", "💐", "Flower bouquet"),

	// ── Gaming (15)
	emojiSticker("st-gam-001", "Joystick", "Gaming", "🕹️", "Arcade joystick"),
	emojiSticker("st-gam-002", "Gamepad", "Gaming", "🎮", "Game controller"),
	emojiSticker("st-gam-003", "Dice", "Gaming", "🎲", "Game dice"),
	emojiSticker("st-gam-004", "Chess", "Gaming", "♟️", "Chess pawn"),
	emojiSticker("st-gam-005", "Slot", "Gaming", "🎰", "Slot machine"),
	emojiSticker("st-gam-006", "Crystal", "Gaming", "🔮", "Crystal ball"),
	emojiSticker("st-gam-007", "Sword", "Gaming", "⚔️", "Crossed swords"),
	emojiSticker("st-gam-008", "Shield", "Gaming", "🛡️", "Knight shield"),
	emojiSticker("st-gam-009", "Bow", "Gaming", "🏹", "Bow and arrow"),
	emojiSticker("st-gam-010", "Ghost", "Gaming", "👻", "Cute ghost"),
	emojiSticker("st-gam-011", "Alien", "Gaming", "👾", "Pixel alien"),
	emojiSticker("st-gam-012", "Skull", "Gaming", "💀", "Skull icon"),
	emojiSticker("st-gam-013", "Pinball", "Gaming", "🎯", "Bullseye target"),
	emojiSticker("st-gam-014", "Mage", "Gaming", "🧙", "Wizard"),
	emojiSticker("st-gam-015", "Mushroom", "Gaming", "🍄", "Power-up mushroom"),
];
