// Transitions — 162 entries (Fade 14, Slide 14, Push 13, Zoom 14, Rotate 13,
// Wipe 14, Morph 13, Glitch 14, Liquid 13, Light 13, 3D 14, Geometric 13).
// Typed against the existing TransitionDefinition at @/lib/transitions/types.
// The 12 user-categories are encoded as keywords + baseCategory mapping
// (TRANSITION_PRESET_BASE in ./types).

import type {
	TransitionDefinition,
	TransitionDirection,
	TransitionParams,
} from "@/lib/transitions/types";
import type { TransitionBaseCategory } from "./types";

const DEFAULT_DIRS: TransitionDirection[] = ["in", "out", "cross"];

const tx = (
	type: string,
	name: string,
	baseCat: TransitionBaseCategory,
	easing: string,
	keyframes: string,
	keywords: string[] = [],
	directions: TransitionDirection[] = DEFAULT_DIRS,
	defaultDuration = 1000,
	minDuration = 200,
	maxDuration = 3000,
): TransitionDefinition => ({
	type,
	name,
	keywords,
	category: baseCat,
	defaultDuration,
	minDuration,
	maxDuration,
	directions,
	previewStyle: ({ direction }: TransitionParams) =>
		`@keyframes ${type}-${direction}{${keyframes}}`,
	easing,
});

export const transitions: TransitionDefinition[] = [
	// ── Fade (14) → fade
	tx("tx-fade-crossfade", "Crossfade", "fade", "ease-in-out",
		"0%{opacity:0;}100%{opacity:1;}", ["fade", "crossfade", "opacity"]),
	tx("tx-fade-fade-to-black", "Fade to Black", "fade", "ease-in-out",
		"0%{opacity:1;}100%{opacity:0;}", ["fade", "black", "opacity"]),
	tx("tx-fade-fade-to-white", "Fade to White", "fade", "ease-in-out",
		"0%{opacity:1;}100%{opacity:0;background:#fff;}", ["fade", "white", "opacity"]),
	tx("tx-fade-dip-to-color", "Dip to Color", "fade", "ease-in-out",
		"0%{opacity:1;background:transparent;}50%{opacity:0;background:#000;}100%{opacity:1;}", ["fade", "color", "dip"]),
	tx("tx-fade-soft-fade", "Soft Fade", "fade", "ease-out",
		"0%{opacity:0;}100%{opacity:1;}", ["fade", "soft"]),
	tx("tx-fade-linear-fade", "Linear Fade", "fade", "linear",
		"0%{opacity:0;}100%{opacity:1;}", ["fade", "linear"]),
	tx("tx-fade-ease-fade", "Eased Fade", "fade", "cubic-bezier(.65,0,.35,1)",
		"0%{opacity:0;}100%{opacity:1;}", ["fade", "ease"]),
	tx("tx-fade-blur-fade", "Blur Fade", "fade", "ease-in-out",
		"0%{opacity:0;filter:blur(20px);}100%{opacity:1;filter:blur(0);}", ["fade", "blur"]),
	tx("tx-fade-fade-and-scale", "Fade & Scale", "fade", "ease-out",
		"0%{opacity:0;transform:scale(.8);}100%{opacity:1;transform:scale(1);}", ["fade", "scale"]),
	tx("tx-fade-fade-and-rotate", "Fade & Rotate", "fade", "ease-out",
		"0%{opacity:0;transform:rotate(-15deg);}100%{opacity:1;transform:rotate(0);}", ["fade", "rotate"]),
	tx("tx-fade-fade-blur-out", "Fade Blur Out", "fade", "ease-in",
		"0%{opacity:1;filter:blur(0);}100%{opacity:0;filter:blur(20px);}", ["fade", "blur"]),
	tx("tx-fade-color-fade", "Color Fade", "fade", "ease-in-out",
		"0%{opacity:0;filter:grayscale(1);}100%{opacity:1;filter:grayscale(0);}", ["fade", "color", "saturation"]),
	tx("tx-fade-ease-elastic", "Elastic Fade", "fade", "cubic-bezier(.68,-.55,.27,1.55)",
		"0%{opacity:0;transform:scale(.5);}100%{opacity:1;transform:scale(1);}", ["fade", "elastic", "bounce"]),
	tx("tx-fade-instant", "Instant Cut", "fade", "steps(1,end)",
		"0%{opacity:0;}100%{opacity:1;}", ["fade", "cut", "hard"]),

	// ── Slide (14) → slide
	tx("tx-slide-left", "Slide Left", "slide", "ease-in-out",
		"0%{transform:translateX(100%);}100%{transform:translateX(0);}", ["slide", "left", "pan"]),
	tx("tx-slide-right", "Slide Right", "slide", "ease-in-out",
		"0%{transform:translateX(-100%);}100%{transform:translateX(0);}", ["slide", "right", "pan"]),
	tx("tx-slide-up", "Slide Up", "slide", "ease-in-out",
		"0%{transform:translateY(100%);}100%{transform:translateY(0);}", ["slide", "up", "pan"]),
	tx("tx-slide-down", "Slide Down", "slide", "ease-in-out",
		"0%{transform:translateY(-100%);}100%{transform:translateY(0);}", ["slide", "down", "pan"]),
	tx("tx-slide-diagonal-tl", "Diagonal TL", "slide", "ease-in-out",
		"0%{transform:translate(100%,100%);}100%{transform:translate(0,0);}", ["slide", "diagonal"]),
	tx("tx-slide-diagonal-tr", "Diagonal TR", "slide", "ease-in-out",
		"0%{transform:translate(-100%,100%);}100%{transform:translate(0,0);}", ["slide", "diagonal"]),
	tx("tx-slide-diagonal-bl", "Diagonal BL", "slide", "ease-in-out",
		"0%{transform:translate(100%,-100%);}100%{transform:translate(0,0);}", ["slide", "diagonal"]),
	tx("tx-slide-diagonal-br", "Diagonal BR", "slide", "ease-in-out",
		"0%{transform:translate(-100%,-100%);}100%{transform:translate(0,0);}", ["slide", "diagonal"]),
	tx("tx-slide-split-v", "Split Vertical", "slide", "ease-in-out",
		"0%{transform:translateX(-100%);}50%{transform:translateX(0);}100%{transform:translateX(100%);}", ["slide", "split"]),
	tx("tx-slide-split-h", "Split Horizontal", "slide", "ease-in-out",
		"0%{transform:translateY(-100%);}50%{transform:translateY(0);}100%{transform:translateY(100%);}", ["slide", "split"]),
	tx("tx-slide-rebound", "Rebound Slide", "slide", "cubic-bezier(.34,1.56,.64,1)",
		"0%{transform:translateX(-100%);}100%{transform:translateX(0);}", ["slide", "bounce", "spring"]),
	tx("tx-slide-smooth", "Smooth Slide", "slide", "cubic-bezier(.65,0,.35,1)",
		"0%{transform:translateX(100%);}100%{transform:translateX(0);}", ["slide", "smooth"]),
	tx("tx-slide-fast", "Fast Slide", "slide", "ease-out",
		"0%{transform:translateX(100%);}100%{transform:translateX(0);}", ["slide", "fast", "whip"], DEFAULT_DIRS, 600, 100, 2000),
	tx("tx-slide-slow", "Slow Slide", "slide", "ease-in-out",
		"0%{transform:translateX(100%);}100%{transform:translateX(0);}", ["slide", "slow"], DEFAULT_DIRS, 1500, 400, 4000),

	// ── Push (13) → slide
	tx("tx-push-left", "Push Left", "slide", "ease-in-out",
		"0%{transform:translateX(0);}50%{transform:translateX(-50%);}100%{transform:translateX(-100%);}", ["push", "left"]),
	tx("tx-push-right", "Push Right", "slide", "ease-in-out",
		"0%{transform:translateX(0);}50%{transform:translateX(50%);}100%{transform:translateX(100%);}", ["push", "right"]),
	tx("tx-push-up", "Push Up", "slide", "ease-in-out",
		"0%{transform:translateY(0);}50%{transform:translateY(-50%);}100%{transform:translateY(-100%);}", ["push", "up"]),
	tx("tx-push-down", "Push Down", "slide", "ease-in-out",
		"0%{transform:translateY(0);}50%{transform:translateY(50%);}100%{transform:translateY(100%);}", ["push", "down"]),
	tx("tx-push-cross-left", "Cross Push Left", "slide", "ease-in-out",
		"0%{transform:translateX(100%);}100%{transform:translateX(-100%);}", ["push", "cross"]),
	tx("tx-push-cross-right", "Cross Push Right", "slide", "ease-in-out",
		"0%{transform:translateX(-100%);}100%{transform:translateX(100%);}", ["push", "cross"]),
	tx("tx-push-up-with-ease", "Push Up Ease", "slide", "ease-out",
		"0%{transform:translateY(0);}100%{transform:translateY(-100%);}", ["push", "up", "ease"]),
	tx("tx-push-down-with-ease", "Push Down Ease", "slide", "ease-out",
		"0%{transform:translateY(0);}100%{transform:translateY(100%);}", ["push", "down", "ease"]),
	tx("tx-push-cover", "Cover Push", "slide", "ease-in-out",
		"0%{clip-path:inset(0 100% 0 0);}100%{clip-path:inset(0 0 0 0);}", ["push", "cover", "wipe"]),
	tx("tx-push-reveal", "Reveal Push", "slide", "ease-in-out",
		"0%{clip-path:inset(0 0 0 100%);}100%{clip-path:inset(0 0 0 0);}", ["push", "reveal", "wipe"]),
	tx("tx-push-half", "Half Push", "slide", "ease-in-out",
		"0%{transform:translateX(0);}100%{transform:translateX(-50%);}", ["push", "half"]),
	tx("tx-push-quarter", "Quarter Push", "slide", "ease-in-out",
		"0%{transform:translateX(0);}100%{transform:translateX(-25%);}", ["push", "quarter"]),
	tx("tx-push-elastic", "Elastic Push", "slide", "cubic-bezier(.68,-.55,.27,1.55)",
		"0%{transform:translateX(0);}100%{transform:translateX(-100%);}", ["push", "elastic", "bounce"]),

	// ── Zoom (14) → zoom
	tx("tx-zoom-in", "Zoom In", "zoom", "ease-in-out",
		"0%{transform:scale(.5);opacity:0;}100%{transform:scale(1);opacity:1;}", ["zoom", "in", "scale"]),
	tx("tx-zoom-out", "Zoom Out", "zoom", "ease-in-out",
		"0%{transform:scale(1.5);opacity:0;}100%{transform:scale(1);opacity:1;}", ["zoom", "out", "scale"]),
	tx("tx-zoom-in-cross", "Zoom In Cross", "zoom", "ease-in-out",
		"0%{transform:scale(.5);opacity:0;}100%{transform:scale(1);opacity:1;}", ["zoom", "cross", "scale"]),
	tx("tx-zoom-out-cross", "Zoom Out Cross", "zoom", "ease-in-out",
		"0%{transform:scale(1.5);opacity:0;}100%{transform:scale(1);opacity:1;}", ["zoom", "cross", "scale"]),
	tx("tx-zoom-pinch", "Pinch Zoom", "zoom", "ease-in-out",
		"0%{transform:scale(2);}100%{transform:scale(1);}", ["zoom", "pinch"]),
	tx("tx-zoom-blast", "Blast Zoom", "zoom", "cubic-bezier(.87,0,.13,1)",
		"0%{transform:scale(0);}100%{transform:scale(1);}", ["zoom", "blast", "fast"], DEFAULT_DIRS, 700, 100, 2000),
	tx("tx-zoom-ken-burns", "Ken Burns", "zoom", "linear",
		"0%{transform:scale(1);}100%{transform:scale(1.2);}", ["zoom", "kenburns", "slow"], DEFAULT_DIRS, 3000, 1000, 8000),
	tx("tx-zoom-spin", "Spin Zoom", "zoom", "ease-in-out",
		"0%{transform:scale(0) rotate(-180deg);}100%{transform:scale(1) rotate(0);}", ["zoom", "spin"]),
	tx("tx-zoom-rush", "Rush Zoom", "zoom", "cubic-bezier(.87,0,.13,1)",
		"0%{transform:scale(.2);}100%{transform:scale(1);}", ["zoom", "rush", "fast"]),
	tx("tx-zoom-bounce", "Bounce Zoom", "zoom", "cubic-bezier(.68,-.55,.27,1.55)",
		"0%{transform:scale(0);}100%{transform:scale(1);}", ["zoom", "bounce"]),
	tx("tx-zoom-elastic", "Elastic Zoom", "zoom", "cubic-bezier(.34,1.56,.64,1)",
		"0%{transform:scale(0);}100%{transform:scale(1);}", ["zoom", "elastic", "spring"]),
	tx("tx-zoom-slow", "Slow Zoom", "zoom", "ease-in-out",
		"0%{transform:scale(.8);}100%{transform:scale(1);}", ["zoom", "slow"], DEFAULT_DIRS, 1500, 400, 4000),
	tx("tx-zoom-fast", "Fast Zoom", "zoom", "ease-out",
		"0%{transform:scale(0);}100%{transform:scale(1);}", ["zoom", "fast"], DEFAULT_DIRS, 500, 100, 1500),
	tx("tx-zoom-from-corner", "Corner Zoom", "zoom", "ease-in-out",
		"0%{transform:scale(0);transform-origin:0 0;}100%{transform:scale(1);transform-origin:0 0;}", ["zoom", "corner"]),

	// ── Rotate (13) → zoom
	tx("tx-rotate-90", "Rotate 90", "zoom", "ease-in-out",
		"0%{transform:rotate(-90deg);opacity:0;}100%{transform:rotate(0);opacity:1;}", ["rotate", "spin"]),
	tx("tx-rotate-180", "Rotate 180", "zoom", "ease-in-out",
		"0%{transform:rotate(-180deg);}100%{transform:rotate(0);}", ["rotate", "spin"]),
	tx("tx-rotate-360", "Rotate 360", "zoom", "ease-in-out",
		"0%{transform:rotate(-360deg);}100%{transform:rotate(0);}", ["rotate", "spin", "full"]),
	tx("tx-rotate-half-spin", "Half Spin", "zoom", "ease-in-out",
		"0%{transform:rotate(-180deg);opacity:0;}100%{transform:rotate(0);opacity:1;}", ["rotate", "spin"]),
	tx("tx-rotate-quarter-spin", "Quarter Spin", "zoom", "ease-in-out",
		"0%{transform:rotate(-90deg);}100%{transform:rotate(0);}", ["rotate", "spin"]),
	tx("tx-rotate-swing", "Swing Rotate", "zoom", "cubic-bezier(.34,1.56,.64,1)",
		"0%{transform:rotate(-30deg);}100%{transform:rotate(0);}", ["rotate", "swing"]),
	tx("tx-rotate-flip-y", "Flip Y", "zoom", "ease-in-out",
		"0%{transform:rotateY(-180deg);}100%{transform:rotateY(0);}", ["rotate", "flip", "3d"]),
	tx("tx-rotate-flip-x", "Flip X", "zoom", "ease-in-out",
		"0%{transform:rotateX(-180deg);}100%{transform:rotateX(0);}", ["rotate", "flip", "3d"]),
	tx("tx-rotate-bars", "Bars Rotate", "zoom", "ease-in-out",
		"0%{transform:rotate(-15deg) scale(.9);}100%{transform:rotate(0) scale(1);}", ["rotate", "bars"]),
	tx("tx-rotate-clockwise", "Clockwise", "zoom", "ease-in-out",
		"0%{transform:rotate(-360deg) scale(0);}100%{transform:rotate(0) scale(1);}", ["rotate", "clockwise"]),
	tx("tx-rotate-counter", "Counter", "zoom", "ease-in-out",
		"0%{transform:rotate(360deg) scale(0);}100%{transform:rotate(0) scale(1);}", ["rotate", "counter"]),
	tx("tx-rotate-fast-spin", "Fast Spin", "zoom", "ease-out",
		"0%{transform:rotate(-720deg);}100%{transform:rotate(0);}", ["rotate", "spin", "fast"], DEFAULT_DIRS, 700, 100, 2000),
	tx("tx-rotate-slow-spin", "Slow Spin", "zoom", "ease-in-out",
		"0%{transform:rotate(-360deg);}100%{transform:rotate(0);}", ["rotate", "spin", "slow"], DEFAULT_DIRS, 2000, 500, 5000),

	// ── Wipe (14) → wipe
	tx("tx-wipe-left", "Wipe Left", "wipe", "ease-in-out",
		"0%{clip-path:inset(0 0 0 100%);}100%{clip-path:inset(0 0 0 0);}", ["wipe", "left"]),
	tx("tx-wipe-right", "Wipe Right", "wipe", "ease-in-out",
		"0%{clip-path:inset(0 100% 0 0);}100%{clip-path:inset(0 0 0 0);}", ["wipe", "right"]),
	tx("tx-wipe-up", "Wipe Up", "wipe", "ease-in-out",
		"0%{clip-path:inset(0 0 100% 0);}100%{clip-path:inset(0 0 0 0);}", ["wipe", "up"]),
	tx("tx-wipe-down", "Wipe Down", "wipe", "ease-in-out",
		"0%{clip-path:inset(100% 0 0 0);}100%{clip-path:inset(0 0 0 0);}", ["wipe", "down"]),
	tx("tx-wipe-diagonal", "Diagonal Wipe", "wipe", "ease-in-out",
		"0%{clip-path:polygon(0 0,0 0,0 100%);}100%{clip-path:polygon(0 0,100% 0,100% 100%);}", ["wipe", "diagonal"]),
	tx("tx-wipe-clock", "Clock Wipe", "wipe", "ease-in-out",
		"0%{clip-path:polygon(50% 50%,50% 50%,50% 50%);}100%{clip-path:polygon(50% 50%,50% 0,100% 50%,50% 100%,50% 100%);}", ["wipe", "clock"]),
	tx("tx-wipe-counter", "Counter Wipe", "wipe", "ease-in-out",
		"0%{clip-path:polygon(50% 50%,50% 50%,50% 50%);}100%{clip-path:polygon(50% 50%,50% 0,0 50%,50% 100%,50% 100%);}", ["wipe", "counter"]),
	tx("tx-wipe-circle", "Circle Wipe", "wipe", "ease-in-out",
		"0%{clip-path:circle(0 at 50% 50%);}100%{clip-path:circle(75% at 50% 50%);}", ["wipe", "circle"]),
	tx("tx-wipe-iris", "Iris", "wipe", "ease-in-out",
		"0%{clip-path:circle(0 at 50% 50%);}100%{clip-path:circle(100% at 50% 50%);}", ["wipe", "iris", "circle"]),
	tx("tx-wipe-barn", "Barn Door", "wipe", "ease-in-out",
		"0%{clip-path:polygon(0 0,0 0,0 100%,0 100%);}100%{clip-path:polygon(0 0,50% 0,50% 100%,0 100%);}", ["wipe", "barn", "split"]),
	tx("tx-wipe-venetian", "Venetian Blinds", "wipe", "ease-in-out",
		"0%{clip-path:inset(0 0 100% 0);}100%{clip-path:inset(0 0 0 0);}", ["wipe", "blinds", "venetian"]),
	tx("tx-wipe-checker", "Checker Wipe", "wipe", "steps(8,end)",
		"0%{clip-path:inset(0 50% 0 50%);}100%{clip-path:inset(0 0 0 0);}", ["wipe", "checker", "pixel"]),
	tx("tx-wipe-diagonal-br", "Diagonal BR", "wipe", "ease-in-out",
		"0%{clip-path:polygon(0 0,0 0,0 0);}100%{clip-path:polygon(0 0,100% 100%,100% 100%);}", ["wipe", "diagonal"]),
	tx("tx-wipe-stripe", "Stripe Wipe", "wipe", "ease-in-out",
		"0%{clip-path:inset(0 0 0 100%);}100%{clip-path:inset(0 0 0 0);}", ["wipe", "stripe"]),

	// ── Morph (13) → fade
	tx("tx-morph-blob", "Blob Morph", "fade", "ease-in-out",
		"0%{clip-path:circle(50% at 50% 50%);}50%{clip-path:circle(40% at 60% 40%);}100%{clip-path:circle(50% at 50% 50%);}", ["morph", "blob"]),
	tx("tx-morph-liquid", "Liquid Morph", "fade", "ease-in-out",
		"0%{filter:url(#liquid);opacity:0;}100%{filter:none;opacity:1;}", ["morph", "liquid"]),
	tx("tx-morph-blur-morph", "Blur Morph", "fade", "ease-in-out",
		"0%{opacity:0;filter:blur(30px);}100%{opacity:1;filter:blur(0);}", ["morph", "blur"]),
	tx("tx-morph-color-morph", "Color Morph", "fade", "ease-in-out",
		"0%{opacity:0;filter:hue-rotate(180deg);}100%{opacity:1;filter:hue-rotate(0);}", ["morph", "color"]),
	tx("tx-morph-page-turn", "Page Turn", "fade", "ease-in-out",
		"0%{transform:perspective(800px) rotateY(-90deg);}100%{transform:perspective(800px) rotateY(0);}", ["morph", "page", "flip"]),
	tx("tx-morph-swirl", "Swirl Morph", "fade", "ease-in-out",
		"0%{transform:rotate(-90deg) scale(.5);filter:blur(10px);}100%{transform:rotate(0) scale(1);filter:blur(0);}", ["morph", "swirl"]),
	tx("tx-morph-distort", "Distort Morph", "fade", "ease-in-out",
		"0%{filter:url(#distort);}100%{filter:none;}", ["morph", "distort"]),
	tx("tx-morph-pixelate", "Pixelate Morph", "fade", "steps(8,end)",
		"0%{filter:pixelate(20);}100%{filter:pixelate(0);}", ["morph", "pixelate"]),
	tx("tx-morph-smooth-blend", "Smooth Blend", "fade", "cubic-bezier(.65,0,.35,1)",
		"0%{opacity:0;}100%{opacity:1;}", ["morph", "blend", "smooth"]),
	tx("tx-morph-quick", "Quick Morph", "fade", "ease-out",
		"0%{opacity:0;transform:scale(.95);}100%{opacity:1;transform:scale(1);}", ["morph", "quick"], DEFAULT_DIRS, 400, 100, 1500),
	tx("tx-morph-slow", "Slow Morph", "fade", "ease-in-out",
		"0%{opacity:0;}100%{opacity:1;}", ["morph", "slow"], DEFAULT_DIRS, 2000, 500, 5000),
	tx("tx-morph-burn", "Burn Morph", "fade", "ease-in-out",
		"0%{opacity:1;filter:contrast(2) brightness(2);}100%{opacity:1;filter:none;}", ["morph", "burn"]),
	tx("tx-morph-flow", "Flow Morph", "fade", "ease-in-out",
		"0%{opacity:0;transform:translateY(20px);}100%{opacity:1;transform:translateY(0);}", ["morph", "flow"]),

	// ── Glitch (14) → glitch
	tx("tx-glitch-rgb", "RGB Split", "glitch", "steps(4,end)",
		"0%{transform:translate(0);filter:hue-rotate(0);}25%{transform:translate(-5px,2px);filter:hue-rotate(90deg);}50%{transform:translate(3px,-3px);filter:hue-rotate(180deg);}75%{transform:translate(-2px,1px);filter:hue-rotate(270deg);}100%{transform:translate(0);filter:hue-rotate(0);}", ["glitch", "rgb", "chromatic"]),
	tx("tx-glitch-pixelate", "Pixelate", "glitch", "steps(6,end)",
		"0%{filter:pixelate(30);}100%{filter:pixelate(0);}", ["glitch", "pixelate"]),
	tx("tx-glitch-datamosh", "Datamosh", "glitch", "steps(5,end)",
		"0%{transform:translate(20px,-10px);}50%{transform:translate(-10px,15px);}100%{transform:translate(0);}", ["glitch", "datamosh"]),
	tx("tx-glitch-scan", "Scan Glitch", "glitch", "steps(8,end)",
		"0%{transform:translate(0);}25%{transform:translate(10px,0);}50%{transform:translate(-5px,0);}75%{transform:translate(2px,5px);}100%{transform:translate(0);}", ["glitch", "scan"]),
	tx("tx-glitch-block", "Block Glitch", "glitch", "steps(4,end)",
		"0%{clip-path:inset(0 0 80% 0);}50%{clip-path:inset(60% 0 0 0);}100%{clip-path:inset(0);}", ["glitch", "block"]),
	tx("tx-glitch-bar", "Bar Glitch", "glitch", "steps(3,end)",
		"0%{clip-path:inset(45% 0 50% 0);}100%{clip-path:inset(0);}", ["glitch", "bar"]),
	tx("tx-glitch-static", "Static Noise", "glitch", "steps(8,end)",
		"0%{opacity:1;filter:contrast(3);}50%{opacity:.8;filter:contrast(5) hue-rotate(45deg);}100%{opacity:1;filter:none;}", ["glitch", "static", "noise"]),
	tx("tx-glitch-displace", "Displacement", "glitch", "steps(6,end)",
		"0%{transform:translate(0,0);}33%{transform:translate(-8px,4px);}66%{transform:translate(6px,-6px);}100%{transform:translate(0);}", ["glitch", "displace"]),
	tx("tx-glitch-vhs", "VHS", "glitch", "steps(6,end)",
		"0%{transform:translateY(0);filter:saturate(1.5);}50%{transform:translateY(2px);filter:saturate(2) hue-rotate(20deg);}100%{transform:translateY(0);filter:saturate(1.5);}", ["glitch", "vhs", "retro"]),
	tx("tx-glitch-crt", "CRT", "glitch", "steps(8,end)",
		"0%{transform:scaleY(1.02);filter:brightness(1.2);}50%{transform:scaleY(1);filter:brightness(1.5);}100%{transform:scaleY(1.02);filter:brightness(1.2);}", ["glitch", "crt", "retro"]),
	tx("tx-glitch-mosaic", "Mosaic", "glitch", "steps(10,end)",
		"0%{clip-path:polygon(0 0,0 0,0 0);}100%{clip-path:polygon(0 0,100% 0,100% 100%,0 100%);}", ["glitch", "mosaic", "pixel"]),
	tx("tx-glitch-shake", "Shake", "glitch", "steps(6,end)",
		"0%{transform:translate(0);}20%{transform:translate(-3px,2px);}40%{transform:translate(3px,-2px);}60%{transform:translate(-2px,1px);}80%{transform:translate(2px,-1px);}100%{transform:translate(0);}", ["glitch", "shake"]),
	tx("tx-glitch-strobe", "Strobe", "glitch", "steps(8,end)",
		"0%{opacity:1;}50%{opacity:0;}100%{opacity:1;}", ["glitch", "strobe"]),
	tx("tx-glitch-hard-cut", "Hard Cut", "glitch", "steps(1,end)",
		"0%{opacity:0;}100%{opacity:1;}", ["glitch", "cut", "hard"]),

	// ── Liquid (13) → wipe
	tx("tx-liquid-wave", "Wave", "wipe", "ease-in-out",
		"0%{clip-path:path('M0,0 L0,0 L0,100% L0,100% Z');}100%{clip-path:path('M0,0 L100%,0 L100%,100% L0,100% Z');}", ["liquid", "wave"]),
	tx("tx-liquid-ripple", "Ripple", "wipe", "ease-in-out",
		"0%{clip-path:circle(0 at 50% 50%);}100%{clip-path:circle(100% at 50% 50%);}", ["liquid", "ripple"]),
	tx("tx-liquid-melt", "Melt", "wipe", "ease-in",
		"0%{transform:translateY(0);filter:blur(0);}100%{transform:translateY(100%);filter:blur(20px);}", ["liquid", "melt"]),
	tx("tx-liquid-bubble", "Bubble", "wipe", "ease-in-out",
		"0%{clip-path:circle(0 at 50% 50%);}50%{clip-path:circle(40% at 50% 50%);}100%{clip-path:circle(100% at 50% 50%);}", ["liquid", "bubble"]),
	tx("tx-liquid-fluid", "Fluid", "wipe", "ease-in-out",
		"0%{filter:url(#fluid);opacity:0;}100%{filter:none;opacity:1;}", ["liquid", "fluid"]),
	tx("tx-liquid-drip", "Drip", "wipe", "ease-in",
		"0%{transform:translateY(-100%);opacity:0;}50%{opacity:1;}100%{transform:translateY(0);opacity:1;}", ["liquid", "drip"]),
	tx("tx-liquid-pour", "Pour", "wipe", "ease-in-out",
		"0%{clip-path:polygon(0 0,0 0,0 100%,0 100%);}100%{clip-path:polygon(0 0,100% 0,100% 100%,0 100%);}", ["liquid", "pour"]),
	tx("tx-liquid-splash", "Splash", "wipe", "cubic-bezier(.68,-.55,.27,1.55)",
		"0%{transform:scale(0);}100%{transform:scale(1);}", ["liquid", "splash"]),
	tx("tx-liquid-dissolve", "Liquid Dissolve", "wipe", "ease-in-out",
		"0%{opacity:1;filter:contrast(1.5) brightness(1.5);}100%{opacity:1;filter:none;}", ["liquid", "dissolve"]),
	tx("tx-liquid-pulse", "Pulse Liquid", "wipe", "ease-in-out",
		"0%{transform:scale(.9);}50%{transform:scale(1.05);}100%{transform:scale(1);}", ["liquid", "pulse"]),
	tx("tx-liquid-elastic", "Elastic Liquid", "wipe", "cubic-bezier(.34,1.56,.64,1)",
		"0%{clip-path:circle(0 at 50% 50%);}100%{clip-path:circle(100% at 50% 50%);}", ["liquid", "elastic"]),
	tx("tx-liquid-mesh", "Mesh", "wipe", "ease-in-out",
		"0%{clip-path:polygon(0 0,50% 0,50% 100%,0 100%);}100%{clip-path:polygon(0 0,100% 0,100% 100%,0 100%);}", ["liquid", "mesh"]),
	tx("tx-liquid-soft", "Soft Liquid", "wipe", "ease-in-out",
		"0%{filter:blur(20px);opacity:0;}100%{filter:blur(0);opacity:1;}", ["liquid", "soft"]),

	// ── Light (13) → fade
	tx("tx-light-leak", "Light Leak", "fade", "ease-in-out",
		"0%{opacity:0;background:radial-gradient(circle at 80% 20%, #ffb347 0%, transparent 70%);}100%{opacity:1;background:transparent;}", ["light", "leak"]),
	tx("tx-light-flash", "Flash", "fade", "ease-in-out",
		"0%{opacity:0;background:#fff;}50%{opacity:1;background:#fff;}100%{opacity:1;background:transparent;}", ["light", "flash"]),
	tx("tx-light-flash-white", "Flash White", "fade", "ease-out",
		"0%{opacity:0;background:#fff;}100%{opacity:1;background:transparent;}", ["light", "flash", "white"]),
	tx("tx-light-flash-color", "Flash Color", "fade", "ease-out",
		"0%{opacity:0;background:#ff00aa;}100%{opacity:1;background:transparent;}", ["light", "flash", "color"]),
	tx("tx-light-strobe", "Light Strobe", "fade", "steps(4,end)",
		"0%{opacity:1;}50%{opacity:0;}100%{opacity:1;}", ["light", "strobe"]),
	tx("tx-light-burst", "Burst", "fade", "ease-out",
		"0%{opacity:1;transform:scale(.95);filter:brightness(2);}100%{opacity:1;transform:scale(1);filter:brightness(1);}", ["light", "burst"]),
	tx("tx-light-pop", "Pop", "fade", "cubic-bezier(.68,-.55,.27,1.55)",
		"0%{opacity:0;transform:scale(.8);}100%{opacity:1;transform:scale(1);}", ["light", "pop"]),
	tx("tx-light-fade-bright", "Bright Fade", "fade", "ease-in-out",
		"0%{opacity:0;filter:brightness(2);}100%{opacity:1;filter:brightness(1);}", ["light", "bright"]),
	tx("tx-light-warm-glow", "Warm Glow", "fade", "ease-in-out",
		"0%{opacity:0;filter:brightness(1.5) sepia(.5);}100%{opacity:1;filter:none;}", ["light", "warm", "glow"]),
	tx("tx-light-cool-glow", "Cool Glow", "fade", "ease-in-out",
		"0%{opacity:0;filter:brightness(1.5) hue-rotate(180deg);}100%{opacity:1;filter:none;}", ["light", "cool", "glow"]),
	tx("tx-light-iris", "Light Iris", "fade", "ease-in-out",
		"0%{opacity:1;clip-path:circle(0 at 50% 50%);}100%{opacity:1;clip-path:circle(100% at 50% 50%);}", ["light", "iris"]),
	tx("tx-light-haze", "Haze", "fade", "ease-in-out",
		"0%{opacity:0;filter:blur(10px);}100%{opacity:1;filter:blur(0);}", ["light", "haze"]),
	tx("tx-light-chroma", "Chroma", "fade", "ease-in-out",
		"0%{opacity:0;background:#0f0;}50%{opacity:1;background:#0f0;}100%{opacity:1;background:transparent;}", ["light", "chroma", "green"]),

	// ── 3D (14) → zoom
	tx("tx-3d-cube", "Cube", "zoom", "ease-in-out",
		"0%{transform:perspective(800px) rotateY(-90deg);}100%{transform:perspective(800px) rotateY(0);}", ["3d", "cube", "flip"]),
	tx("tx-3d-cube-up", "Cube Up", "zoom", "ease-in-out",
		"0%{transform:perspective(800px) rotateX(90deg);}100%{transform:perspective(800px) rotateX(0);}", ["3d", "cube"]),
	tx("tx-3d-cube-down", "Cube Down", "zoom", "ease-in-out",
		"0%{transform:perspective(800px) rotateX(-90deg);}100%{transform:perspective(800px) rotateX(0);}", ["3d", "cube"]),
	tx("tx-3d-cube-left", "Cube Left", "zoom", "ease-in-out",
		"0%{transform:perspective(800px) rotateY(90deg);}100%{transform:perspective(800px) rotateY(0);}", ["3d", "cube"]),
	tx("tx-3d-cube-right", "Cube Right", "zoom", "ease-in-out",
		"0%{transform:perspective(800px) rotateY(-90deg);}100%{transform:perspective(800px) rotateY(0);}", ["3d", "cube"]),
	tx("tx-3d-flip-x", "3D Flip X", "zoom", "ease-in-out",
		"0%{transform:perspective(800px) rotateX(-180deg);}100%{transform:perspective(800px) rotateX(0);}", ["3d", "flip"]),
	tx("tx-3d-flip-y", "3D Flip Y", "zoom", "ease-in-out",
		"0%{transform:perspective(800px) rotateY(-180deg);}100%{transform:perspective(800px) rotateY(0);}", ["3d", "flip"]),
	tx("tx-3d-rotate-x", "3D Rotate X", "zoom", "ease-in-out",
		"0%{transform:perspective(800px) rotateX(-360deg);}100%{transform:perspective(800px) rotateX(0);}", ["3d", "rotate"]),
	tx("tx-3d-rotate-y", "3D Rotate Y", "zoom", "ease-in-out",
		"0%{transform:perspective(800px) rotateY(-360deg);}100%{transform:perspective(800px) rotateY(0);}", ["3d", "rotate"]),
	tx("tx-3d-door", "Door", "zoom", "ease-in-out",
		"0%{transform:perspective(800px) rotateY(-110deg);transform-origin:0 50%;}100%{transform:perspective(800px) rotateY(0);transform-origin:0 50%;}", ["3d", "door"]),
	tx("tx-3d-card-flip", "Card Flip", "zoom", "ease-in-out",
		"0%{transform:perspective(800px) rotateY(-180deg);}100%{transform:perspective(800px) rotateY(0);}", ["3d", "card"]),
	tx("tx-3d-page-curl", "Page Curl", "zoom", "ease-in-out",
		"0%{transform:perspective(800px) rotateY(-30deg);}100%{transform:perspective(800px) rotateY(0);}", ["3d", "page"]),
	tx("tx-3d-perspective", "Perspective", "zoom", "ease-in-out",
		"0%{transform:perspective(400px) translateZ(-500px);}100%{transform:perspective(400px) translateZ(0);}", ["3d", "perspective"]),
	tx("tx-3d-zoom-3d", "3D Zoom", "zoom", "ease-in-out",
		"0%{transform:perspective(800px) scale(.5) translateZ(-200px);}100%{transform:perspective(800px) scale(1) translateZ(0);}", ["3d", "zoom"]),

	// ── Geometric (13) → wipe
	tx("tx-geo-checker", "Checker", "wipe", "steps(8,end)",
		"0%{clip-path:inset(0 50% 0 50%);}100%{clip-path:inset(0 0 0 0);}", ["geometric", "checker"]),
	tx("tx-geo-dots", "Dots", "wipe", "steps(12,end)",
		"0%{clip-path:circle(0 at 50% 50%);}100%{clip-path:circle(100% at 50% 50%);}", ["geometric", "dots"]),
	tx("tx-geo-triangles", "Triangles", "wipe", "ease-in-out",
		"0%{clip-path:polygon(50% 50%,50% 50%,50% 50%);}100%{clip-path:polygon(0 0,100% 0,100% 100%);}", ["geometric", "triangles"]),
	tx("tx-geo-hexagons", "Hexagons", "wipe", "ease-in-out",
		"0%{clip-path:polygon(25% 0,75% 0,100% 50%,75% 100%,25% 100%,0 50%);transform:scale(0);}100%{clip-path:polygon(25% 0,75% 0,100% 50%,75% 100%,25% 100%,0 50%);transform:scale(1);}", ["geometric", "hexagon"]),
	tx("tx-geo-stripes", "Stripes", "wipe", "ease-in-out",
		"0%{clip-path:inset(0 100% 0 0);}100%{clip-path:inset(0 0 0 0);}", ["geometric", "stripes"]),
	tx("tx-geo-grid", "Grid", "wipe", "steps(6,end)",
		"0%{clip-path:inset(0 100% 100% 0);}100%{clip-path:inset(0 0 0 0);}", ["geometric", "grid"]),
	tx("tx-geo-spiral", "Spiral", "wipe", "ease-in-out",
		"0%{clip-path:polygon(50% 50%,50% 45%,55% 50%);}100%{clip-path:polygon(0 0,100% 0,100% 100%,0 100%);}", ["geometric", "spiral"]),
	tx("tx-geo-sawtooth", "Sawtooth", "wipe", "ease-in-out",
		"0%{clip-path:polygon(0 0,0 0,0 100%);}100%{clip-path:polygon(0 0,100% 50%,0 100%);}", ["geometric", "sawtooth"]),
	tx("tx-geo-circles", "Circles", "wipe", "ease-in-out",
		"0%{clip-path:circle(0 at 50% 50%);}100%{clip-path:circle(100% at 50% 50%);}", ["geometric", "circles"]),
	tx("tx-geo-blinds", "Blinds", "wipe", "ease-in-out",
		"0%{clip-path:inset(0 0 100% 0);}100%{clip-path:inset(0 0 0 0);}", ["geometric", "blinds"]),
	tx("tx-geo-pixels", "Pixels", "wipe", "steps(10,end)",
		"0%{clip-path:inset(0 100% 0 0);}100%{clip-path:inset(0 0 0 0);}", ["geometric", "pixels"]),
	tx("tx-geo-curtain", "Curtain", "wipe", "ease-in-out",
		"0%{clip-path:polygon(0 0,0 0,0 100%,0 100%);}100%{clip-path:polygon(0 0,100% 0,100% 100%,0 100%);}", ["geometric", "curtain"]),
	tx("tx-geo-shutter", "Shutter", "wipe", "ease-in-out",
		"0%{clip-path:polygon(0 0,50% 0,50% 0,0 0);}100%{clip-path:polygon(0 0,50% 0,50% 100%,0 100%);}", ["geometric", "shutter"]),
];
